### ISSUE TITLE
Any command to display Compiler (or neo-go) version?

### ISSUE THREAD

**Issue by igormcoelho** [nspcc-dev/neo-go#102]
Hi all! It would be nice to have a command to display neo-go version (or compiler version).
I'm trying to put that on neocompiler.io, to give a better feedback on which compiler version is being used.

Congratulations for the amazing work!

**Comment by anthdm** [comment]
@igormcoelho This will done when the new and improved compiler from neo-storm is merged again with `neo-go`

**Comment by hal0x2328** [comment]
@anthdm Is there a timeline on integration of neo-storm we can add to the roadmap?
