### ISSUE TITLE
Get rid of duplication in VM's interops

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#1075]
Currently each of the interops which is default is declared in both `vm` and `core`.
We should either declare them only in VM package or provide them only for tests.
List of interops: `System.Iterator.*`, `System.Enumerator.*`, `System.Binary.*`, `System.Runtime.Log`, `System.Runtime.Notify`.
Maybe it is also worth to add JSON serialization interops.

**Comment by roman-khimov** [comment]
We only have Log/Notify left now, but I think we can only remove them after #2528 (at the moment they can be useful for some simple scripts).
