### ISSUE TITLE
Update debug info generation for Neo3 (preview2 compatible)

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#1088]
There is an updated specification (v1.1) for debug info: https://github.com/ngdseattle/design-notes/blob/master/NDX-DN11%20-%20NEO%20Debug%20Info%20Specification.md

And compatible builds:
https://github.com/neo-project/neo-express/releases/tag/v1.2.1-insiders 
https://github.com/neo-project/neo-debugger/releases/tag/v1.2.10-preview

The changes are quite trivial: `hash` goes in, `entrypoint` goes out, we need to implement them and test for compatibility with the new debugger.

**Comment by roman-khimov** [comment]
Waiting for neo-project/neo-devpack-dotnet#298 to add proper field names.

Also linking neo-project/neo-debugger#63 here (though it doesn't block this one).

**Comment by devhawk** [comment]
Note, the debug info spec was out of date with the implementation. Updates to the debug info spec are in PR: https://github.com/ngdseattle/design-notes/pull/7

**Comment by roman-khimov** [comment]
Fixed with #1100, #1108.
