### ISSUE TITLE
Extend RPC client tests

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#1107]
We should check the request that is formed and sent on the server. Otherwise we are mostly checking correctness of response parsing.

**Comment by roman-khimov** [comment]
I think we can just add a set of tests that would reuse our server, that should be enough.

**Comment by roman-khimov** [comment]
We have `client_test.go` in the `server` package now, I think it's pretty good, even though it doesn't test all methods it tests many complex ones. So this issue seems to be solved to me, any particular extensions for specific methods can be discussed in separate issues.
