### ISSUE TITLE
NEO-GO version 2

### ISSUE THREAD

**Issue by anthdm** [nspcc-dev/neo-go#113]
Let's start a discussion on how to approach the fresh and optimized version of neo-go.

I know that @decentralisedkev has done some amazing job on some parts of the v2 yet. I will start factoring out the `wire` package into the master branch.

**Comment by im-kulikov** [comment]
👍 thx for discus..
mb we can go another way (https://github.com/CityOfZion/neo-go/issues/110#issuecomment-444515401)?

By splitting repo into small parts we can make it more useful like libp2p or neo-python

**Comment by anthdm** [comment]
@im-kulikov Ok fine I will share my thoughts on this also after the weekend, then we can compare and pick the best of both worlds. Are you already on the CoZ slack channel? I think you should start getting rewards for you work on `neo-go` soonish.

**Comment by decentralisedkev** [comment]
@anthdm What do you mean by factoring out?

**Comment by im-kulikov** [comment]
> Ok fine I will share my thoughts on this also after the weekend, then we can compare and pick the best of both worlds
> I think you should start getting rewards for you work on neo-go soonish.

sounds cool

> Are you already on the CoZ slack channel?

can you invite me?

**Comment by im-kulikov** [comment]
@decentralisedkev can you share your `some amazing job on some parts of the v2`, mb we can based on it?

**Comment by decentralisedkev** [comment]
@im-kulikov Yeah that's the one.

The link to the Slack channel is in this document: https://github.com/CityOfZion/standards/blob/master/Introduction.md

**Comment by roman-khimov** [comment]
Closing this issue as the `dev` (or `v2`) code reusage will be done in package-specific tasks and any other refactoring is gonna be problem-oriented (and not just rewriting everything again).
