### ISSUE TITLE
Adjust RPC-calls JSON fields naming after preview2

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#1130]
Follow https://github.com/neo-project/neo-modules/issues/261, there's a standard coming.

**Comment by roman-khimov** [comment]
I think we're done here, aren't we?

**Comment by AnnaShaleva** [comment]
#1182, #1183, #1184 and #1185 are also concern about this task, but they have their own issues, so we are.

**Comment by roman-khimov** [comment]
BTW, why this one is not closed yet? I think we're done here.
