### ISSUE TITLE
Use big.Int to store NEP5Balances 

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#1133]
We store these balance as int64 now, but some tokens may easily overflow it and even GAS might become inflationary at some point and also require wider value. So it's better to switch to big.Int here.

**Comment by roman-khimov** [comment]
Use it for claimable info too.

**Comment by fyrchik** [comment]
This is a bit tricky, as our optimization for `TransferLog` storage assumes `NEP5TransferSize` to be known. It is used for calculating starting position of each transfer in raw `[]byte`. This must be changed somehow.
