### ISSUE TITLE
NEP5 balance tracking info should be updated when contract migrates

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#1144]
Upon contract migration NEP5 balance tracking info should also be migrated from old script hash to the new one.

**Comment by fyrchik** [comment]
Should transfer log be also migrated? Possible complication is that stored tx invokes old contract and I am not sure if this won't lead to bugs somewhere.

**Comment by roman-khimov** [comment]
> Should transfer log be also migrated?

I don't think so, it's historic and it has to stay as is.

**Comment by roman-khimov** [comment]
Fixed with #1149.
