### ISSUE TITLE
Support for variable and constant exports for packages in the compiler

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#1154]
Given the following `foo`:
```
package foo

const Const = 42

// NewBar return an integer \o/
func NewBar() int {
        return 10
}
```
This test should work:
```
func TestImportConst(t *testing.T) {
       src := `
               package importconst

               import "github.com/nspcc-dev/neo-go/pkg/compiler/testdata/foo"

               func Main() int {
                       return foo.Const
               }
       `
       eval(t, src, big.NewInt(42))
}
```
But it doesn't and it also fails if we're to change `foo` to export a variable. It's a bit complicated to fix because `traverseGlobals` is assumed to be called once as it emits an `INITSSLOT` opcode and `convertGlobals` shouldn't ignore constants for subpackages. `ast.SelectorExpr` handling at line 808 of `codegen.go` also should be made aware of package-level constants and variables.

It's also somewhat related to #1150 as at the moment these variables/constants would end up in the same namespace.

**Comment by fyrchik** [comment]
Somewhat depends on #1228 , where `Main` func is no longer special.
