### ISSUE TITLE
util.Equals returns false on equal slices of bytes

### ISSUE THREAD

**Issue by AlexVanin** [nspcc-dev/neo-go#1176]
neo-go version 0.90.0-pre-679-g090936aa

In test below `Main()` expected to return `true`, but returns `false`

```go
package main
import "github.com/nspcc-dev/neo-go/pkg/interop/util"
func Main() bool {
	var one = []byte{1,2}
	var two = []byte{1,2}
	return util.Equals(one, two)
}
```

**Comment by roman-khimov** [comment]
Well, that's a feature of Neo 3 VM. `[]byte` is a buffer inside a VM and it's a reference type, so `EQUAL` opcode basically works the same way `==` would for this case. `util.Equals` is just an alias for `EQUAL`, it's not supposed to do anything else. Something like
```
        var one = string([]byte{1, 2})
        var two = string([]byte{1, 2})
```
would give `true` result.

**Comment by roman-khimov** [comment]
Yes, it's quite a big change compared to Neo 2 VM, but I don't think there is anything to fix there.

**Comment by AlexVanin** [comment]
@roman-khimov  I see. Then what will be the best practice for slice of byte comparison? String conversion as in the example?

**Comment by roman-khimov** [comment]
Yep, converting to strings is the best option for now.
