### ISSUE TITLE
Update binary TestConsensusPayload_Verify data

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#1178]
There's a binary representation of signed commit payload from testnet ([testfile](https://github.com/nspcc-dev/neo-go/blob/master/pkg/consensus/payload_test.go)). It should be updated after stable post-preview2 release of neo-cli and LevelDBStore plugin. Changes are related to #1175.

**Comment by roman-khimov** [comment]
We can get one now from the preview3 testnet.
