### ISSUE TITLE
rpc: adjust `getrawmempool` RPC-call

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#1182]
There should present verified and non-verified transactions, so it may affects the mempool itself.

**Comment by roman-khimov** [comment]
We only store verified transactions, non-verified transactions just don't exist in neo-go.

**Comment by roman-khimov** [comment]
So what we need to do here is to add support for boolean parameter and change the response accordingly. But our unverified list will always be empty.
