### ISSUE TITLE
rpc: add VMState to getrawtransaction

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#1183]
At the current moment we don't have TransactionState and use transaction with block index to store them in `(dao*Simple).StoreAsTransaction` method. One more field was added to TransactionState in C# implementation: `VMState`, so, perhaps, it's time to implement TransactionState in our project.

`getrawtransaction` RPC method also affected by these changes.

**Comment by roman-khimov** [comment]
I'm not sure we really need `TransactionState`, we need to fix `getrawtransaction` and for that we need `VMState`, but (unlike C# node) we always store a complete `AppExecResult` and can get a `VMState` from it. The only thing I'd change here is to store `VMState` as a `byte` and not `string`, other than that it's perfectly fine already.
