### ISSUE TITLE
core: move transaction cosigners to signers

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#1184]
Cosigners are Signers now (include transaction's sender). Related changes should be implemented:
1. New witness scope `FeeOnly`.
2. Take into account the number of signers while deserialising transaction's attributes.
3. Adjust `getrawtransaction` RPC-call.
4. Refactor transaction-related `cli` commands in order to include transaction sender in Signers list with `FeeOnly` witness scope (if needed).

**Comment by roman-khimov** [comment]
> include transaction sender in Signers list with FeeOnly witness scope (if needed).

Usually it's `CalledByEntry`, that's the whole point of this change. Though for deployments it can be `FeeOnly`.
