### ISSUE TITLE
Check stackitem jsonization

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#1190]
neo-project/neo#1569 added direct stack item jsonization, we already have one defined in our code, but we need to check that it conforms to this format.

**Comment by roman-khimov** [comment]
And we need to apply it to app exec results (both exec result's `stack` and notification's `state` now use it). It also should be used for vm stack prints.

**Comment by roman-khimov** [comment]
RPC invocations results also use it now.

**Comment by fyrchik** [comment]
C# `ToJson` fails for recursive structures, which may or may not be what we want for execution results, especially for `FAULT` states. I assume recursive structures are a of no use anyway.
