### ISSUE TITLE
Implement System.Callback.* interops

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#1197]
Now we can create various callbacks, pass them around and invoke them. Some syscalls can be used as callbacks also. See neo-project/neo#1629

**Comment by roman-khimov** [comment]
See also neo-project/neo#1723.

**Comment by roman-khimov** [comment]
Depends on #1208.

**Comment by fyrchik** [comment]
Syscall callbacks implementation depends on neo-project/neo#1655 changes done in #1191 .
