### ISSUE TITLE
Blockchain: Full verification of blocks

### ISSUE THREAD

**Issue by anthdm** [nspcc-dev/neo-go#12]
Currently `verify` only validates if the first TX is a `minerTX` and that all others can't be a `minerTX`.

**Comment by hal0x2328** [comment]
Looks like this still needs done - in fact, it looks like the v2dev branch does even less verification than master.

**Comment by roman-khimov** [comment]
Valid for `master` branch and `dev` also, `dev` really doesn't do any verification at all. But it needs to be expanded with more details on missing checks (I'll skip that for a moment).

**Comment by roman-khimov** [comment]
There are some TODOs in the code also around verification path:
```
pkg/core/block.go:      // TODO: When full is true, do a full verification.
pkg/core/block_base.go: // TODO: Need a persisted blockchain for this.
```
