### ISSUE TITLE
[0.76.0] Node killed during block synchronization due to OOM error

### ISSUE THREAD

**Issue by EdgeDLT** [nspcc-dev/neo-go#1214]
Hey team. I just got done catching up with the MainNet on my NeoGo node, which seems to be running smoothly now. Great work with it, the websocket service is really neat. I'm looking forward to putting it to work! 

Something I noticed while making up the block difference between NGD's latest bootstrap and the current chain height was that my node would be frequently killed due to an out of memory error. It restarts the syncing process gracefully when re-running the node so it's nothing a supervisor can't deal with, but it'd be worth looking into as it's not expected behavior.

My node is a dualcore with 4GB RAM running Ubuntu 20.04 LTS. I'm using the 0.76.0 binary with go version 1.13.8.

**Comment by roman-khimov** [comment]
We've not really optimized it for memory usage yet, but in general, neo-go is less memory hungry than the C# node during regular operation. At the same time IIUC you're saying that it happens during `db restore` and that can be quite resource-intensive as it crunches as many blocks as it can between disk-level persists that happen once a second normally. So we have sawtooth-like memory usage pattern, new blocks (and all their changes) get into memory-backed cache first and when persist timer ticks this cache gets flushed to disk, then the cycle repeats. But if it has problems fitting this changeset into memory available, OOM killer can make its visit to the node. I regularly do these resynchronizations myself, usually even with two parallel processes for testnet and mainnet and I've seen that happen like once or twice when the system was really overloaded with some additional things like VMs. 

We may try to optimize some things and/or may make persistence interval configurable.

**Comment by roman-khimov** [comment]
BTW, have you tried using a different DB backend? Of all our supported, Badger is the most memory-hungry, but we're more often using Bolt here rather than Level (it seems to be a bit more efficient and reliable) and maybe that has some influence too (though I've not directly compared them for this scenario).

**Comment by EdgeDLT** [comment]
Ah, to be clear it didn't happen during `db restore`, that worked fine. Each time it happened was while syncing the remainder of the chain from peers. I've not had any issues since catching up with the current latest block, running smoothly.

As you mentioned, I can see a considerable efficiency improvement in terms of resource consumption compared to my C# node :smile:

**Comment by roman-khimov** [comment]
This might be related to #2238, even if the node is not stuck processing blocks it can be slow and this can affect memory usage. I'm not sure we're fixing it for Legacy though, the change is quite invasive and this problem can only happen to the node catching up with the network using P2P, I'd guess most Legacy nodes should be using chain dumps if there is a need to process whole chain.

**Comment by roman-khimov** [comment]
Shouldn't happen on 0.98.0 and it's not that frequent problem for Legacy too (and Legacy is slowly fading away), so I'm closing it for now.
