### ISSUE TITLE
[neox-2.x] Loss StateRootSignature in CommitCompact

### ISSUE THREAD

**Issue by KickSeason** [nspcc-dev/neo-go#1270]
## Description

Recently c# consensus nodes in testnet threw exception and stopped consensus at `4641478` after received `RecoveryMessage ` from `index=6` which is a `neo-go` client.
As I look into it and reproduce in privatenet, I find that `neo-go` will send `RecoveryMessage` without  `StateRootSignature` field in `CommitCompact`.
### Version
https://github.com/nspcc-dev/neo-go/tree/v0.76.2
### Logs in Testnet
NGD2 
![image](https://user-images.githubusercontent.com/22324403/89398531-d08e7880-d743-11ea-81f0-248d5ca822d0.png)
Red4sec
![image](https://user-images.githubusercontent.com/22324403/89398624-ee5bdd80-d743-11ea-85c9-7f258ef9748f.png)
NGD
![image](https://user-images.githubusercontent.com/22324403/89398741-16e3d780-d744-11ea-8010-5787beb71848.png)

### Steps

* Set up a private net which contains 1 `neo-go` client and 5 c# client.(1 offline node)
* Use [P2PLossyConsensusPlugin](https://github.com/KickSeason/P2PLossyConsensusPlugin) to prevent 3 c# nodes from receiving `PrepareResponse`.
* `neo-go` client will commit and receive 2 other commit messages, and will send recovery when time out.

### Version

* [Neo CLI v2.10.3-neox-preview1](https://github.com/neo-project/neo-node/releases/tag/v2.10.3-neox-preview1)
* [neo-go v0.76.2](https://github.com/nspcc-dev/neo-go/tree/v0.76.2)

### Result

I add log in `func (s *service) broadcast(p payload.ConsensusPayload)` to print `RecoveryMessage` in `neo-go`
code:
```
        if p.Type() == payload.RecoveryMessageType {
		rmm, ok := p.GetRecoveryMessage().(*recoveryMessage)
		if ok {
			s.log.Debug(fmt.Sprintf("[test] commits: %d", len(rmm.commitPayloads)))
		}
		rp, ok := p.(*Payload)
		if !ok {
			s.log.Warn("cannt get recovery message")
		} else {
			rm := rp.message
			buff := io.NewBufBinWriter()
			rm.EncodeBinary(buff.BinWriter)
			s.log.Debug(fmt.Sprintf("[test] hex: %s", hex.EncodeToString(buff.Bytes())))
		}
	}
```
And get log:
![image](https://user-images.githubusercontent.com/22324403/89399919-bb1a4e00-d745-11ea-8426-922bb92c827b.png)
And analyse the hex:
```
41//MessageType
01//ViewNumber
00//ChangeViews
01//HasReq

//PrepareRequest
20//MessageType
01//ViewNumber
07742a5f//Timestamp=1596617735
a4e1b8b7cf4f33d2//Nonce
ac8f066c0ea0884aee2e2f85baf790394e81996d//NextConsensus
01//Tx Hashes
2c54c299522fe9a3f6548e134b4e05beced722b32705afc29ac5bc602ed72e05//hash
//Miner Tx
00//Tx Type Miner
00//Version
743b52cc//Nonce
00//Attributes
00//Inputs
00//Outputs
00//Witness[]
//StateRootBase
00//Version
4c020000//Index=588
7f7370307f9f93a66972beb1fedd3aa37b08387c8a57f146996fe7abfe155f30//PreHash
0000000000000000000000000000000000000000000000000000000000000000//RootHash

//PreparationMessages
06//count
0000//ValidatorIndex
//InvocationScript
41//Length
40487ea78562976ce43fc1645d0de95604ab40bce390804ef8125335ce58eedf7de7e3cba716888cd11592a1ca4ab63e21ad2b04e1a1e7cf5cd857bbf528f57150//Script
0100//ValidatorIndex
//InvocationScript
41//Length
40af96af1c3a82d594506c1476c280846941cc38276fd90668e0482b68256b03d1e01509d2859e60562e5d2f74fba95564ccee508d428d3ce6488f82fdc514ede8//Script
0200//ValidatorIndex
//InvocationScript
41//Length
40b02dcddeeaef6e766892f41a588bbd45568b3057bd20aef8f14f74f252c7ec29972d3dfdaa0c195205b71d8c1ec433213510d120aec42a9c31ea282e658b03c1//Script
0300//ValidatorIndex
//InvocationScript
41//Length
403a0ee34671518c56906b455f5703e4207abe04ce13526d003238c477d42926b1555835c72cceab3ba3c5f92e84d9be2875a9e79fd6d06f0ccb3b5024773016fb//Script
0400//ValidatorIndex
//InvocationScript
41//Length
40e529a2d23149dd7dc403e3ed91ae382de45d1e40fb282351ee9f3669ae32126e2ed4dd25e7582d1552bf06cf89644c91d930cb53b31141d7f3467110d507a81c//Script
0500//ValidatorIndex
//InvocationScript
41//Length
40b12b2b092a13375ac5220785dbd3fe2c9c351d05234968acad39f14a952a9b039e8d4ad1443a33b71daadb83bab23d0e382ce9dd7eadb8cb2fb2f26b754f9df7//Script

//CommitMessages No StateRootSignature Field ?
03//Count
01//ViewNumber
0000//ValidatorIndex
8bad55ae036582ee8a764ed2e97daaf2983a0688879dca94d8b103b07f35bcc44d2ef0d78dec81825b3e6e72e4396bf7a0495763e441ef2022dbd836babc574f//Signature
//InvocationScript
41//Length
4002631c0377fbd38aee82b335180cf79b3fd34a61f44d2b8f77f4dcabc6184296e287edbf1d01ffabaa27ed566ae34e38b9c934c4e1ae5ddadab6f56ca2b94474//Script
01//ViewNumber
0200//ValidatorIndex
867f84b13c6ebcf524e21a03fbcefaf0f827d6a16960fad5ed2cd57cb71fdcb5a1998c4d62d6aea6df22c5f59dd2b5e305cfa5d5b0ad33da95e795f5a26db8a0//Signature
41//Length
402209f831a710804f3d9e4becf0eb7bf3abd865d661fef5fc3702a4fa5b9a9b4323f0c9b4d06dd1f87c209b6f1b38bf168b23d8ad5d284b4034a5d874177f8d9a//Script
01//ViewNumber
0400//ValidatorIndex
118b6b985586b0a225197d356a3b6dbeed9d48c79703f8f75f31479ffdabaac84ccbb365d822cf8639ae1bf3f341bd57282559c6468ff1a72e4157e275766639//Signature
41//Length
4009275f35a93b743927fc58fe22dc6996f43686552d40e45208fce9168f5d5b3436b8a7c0a9c261058abd325c5ef595d4d18a6ebab222c6ae8ba2461245edb5cc//Script
```
You can see in the hex:
* There is no `StateRootSignature` field in `CommitCompact`. Maybe something wrong with `stateRootEnabled` field

## Conclusion

Invalid `RecoveryMessage` will cause unpredictable behavior in c# nodes, including ignore this message or throw exception.

**Comment by roman-khimov** [comment]
Might be because of
```
dbft.WithNewRecoveryMessage(func() payload.RecoveryMessage { return new(recoveryMessage) }),
```
It doesn't set `stateRootEnabled` although it should.

Thanks for the bug, we'll check if that's the case and fix it.
