### ISSUE TITLE
Generate proper debug data for `_initialize`

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#1276]
We have proper globals initialization and `init()` runs after #1261, but we're missing correct debug information for this code, this needs to be fixed.

**Comment by fyrchik** [comment]
We already use normal `convertFuncDecl`, so the only things that need to be addressed are:
1. Sequence point on returns. Possibly insert `NOP` opcode at the end of each `init` for this.
2. Sequence point on global initialization.

Also depends on #1245 .
