### ISSUE TITLE
rewrite RPC package

### ISSUE THREAD

**Issue by im-kulikov** [nspcc-dev/neo-go#128]
I plan to rewrite RPC-package almost from scratch in the near future. This will make it easier to use and give a small boost to the development of the project.

**Comment by dauTT** [comment]
@im-kulikov ,
I am working on implementing all the missing rpc calls with the current base code. I believe this will help you to refactor the RPC code later on. But let us discuss in case you disagree.

**Comment by im-kulikov** [comment]
I plan to start rewriting the client and highlight a package of common structures. This will allow us to more conveniently use golang client to work with neo rpc. Next, we need to clean up the documentation and sample code to work with the rpc client. After that, we can use the available experience to build an rpc server. I don't think this will prevent you from implementing the missing methods at this stage.

**Comment by im-kulikov** [comment]
In any case, this is not a quick process, because I plan to do it in my spare time.

**Comment by im-kulikov** [comment]
For server side I suggest to use http://www.gorillatoolkit.org/pkg/rpc

**Comment by roman-khimov** [comment]
It would be nice to make a summary of issues this rewrite is ought to solve.

**Comment by im-kulikov** [comment]
what i meant by the given issue:
 • bring the code in accordance with  json-rpc rfc 
 • get rid of switch-case-if
 • lead to a general view with go / http
 • make the possibility of convenient unit testing

**Comment by roman-khimov** [comment]
BTW, our RPC implementation has the following TODO items in its README:
```
### TODO

* Merge structs so can be used by both server and client.
* Add missing methods to client.
* Allow client to connect using client cert. 
```
Something to consider wrt this issue.

**Comment by roman-khimov** [comment]
I think that after #763, #753, #705 and #676 our rpc packages are good enough and no longer need to be rewritten. Of course there is always some room for improvements, but these can be done as separate issues.
