### ISSUE TITLE
Add tests for CLI libraries

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#1336]
CLI being at 0% coverage gives us quite low overall coverage number of 68% even though we're at 76%+ now for packages. I think we can start improving it with libraries included there (flags/options/similar things).

**Comment by fyrchik** [comment]
I can be written as a set of integration tests reusing our test dump in `pkg/rpc/server/testdata`

**Comment by roman-khimov** [comment]
That's more for the second part which is running real CLI commands, but this task is about the first step which is covering librarian parts of the CLI (which I think is way easier).
