### ISSUE TITLE
AddToCirculation method of token sale example has no witness checks or approves

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neo-go#1379]
There is a `AddToCirculation` method in [token sale example](https://github.com/nspcc-dev/neo-go/blob/master/examples/token-sale/token_sale.go). This method changes amount of circulated tokens. It has no references in contract and it is public method. But there are no witness checks or any approves, so anyone can invoke this method and mess with the amount of circulated tokes. Seems like a bug.

**Comment by roman-khimov** [comment]
It shouldn't be public, probably. Though it's not being used internally in any way too.
