### ISSUE TITLE
Invalid VM behaviour when creating big big integers

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#1437]
This test case passes, though it shouldn't.
```
func TestBigNegativeInt(t *testing.T) {
	prog := []opcode.Opcode{
		opcode.PUSHINT8, 0x01,
		opcode.PUSHINT16, 0xFF, 0x00,
                opcode.SHL,
	}
	v := load(makeProgram(prog...))
	runVM(t, v)
}
```

This is because we check `BitLen()` in `NewBigInteger` which returns size of the absolute value, while in C# encoding we append leading zero to distinguish positive numbers from negative ones.
Fix this and write tests. May be implementing `bigint.Size(*big.Int)` will be useful.

**Comment by roman-khimov** [comment]
That has some cost to it, obviously, though we don't have much choice here.
