### ISSUE TITLE
feat: support jsonrpc multi-requests

### ISSUE THREAD

**Issue by ixje** [nspcc-dev/neo-go#1509]
The JSON-RPC standard supports sending an array of request objects and receiving an array of response objects (hence the existence of the `id` field). I noticed `neo-go` (at least `https://rpc1.go.nspcc.ru:10331`) doesn't support this and throws an error instead

```
{"id":null,"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse Error","data":"Problem parsing JSON-RPC request body"}}
```

Supporting this feature can reduce the need to hit an endpoint multiple times e.g. when asking for token information. Right now that would require 4 `invokeFunction` calls (name, symbol, decimals, totalSupply)

**Comment by roman-khimov** [comment]
@AnnaShaleva: https://www.jsonrpc.org/specification#batch
