### ISSUE TITLE
Implement tail cutting

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#1560]
While `MaxTraceableBlocks` allows us to drop older blocks and transactions we don't actually do that in any way at the moment. So we need to implement an option (`KeepOldBlocks`, `KeepUntraceableBlocks`, maybe some better name) that will drop useless data from the chain. We have two way to implement it --- either in `storeBlock` directly, or (and I hope it's better) in a background reaper routine (that can be subscribed to `Blockchain` block events).

**Comment by fyrchik** [comment]
I think defaults should keep all state, so something like `RemoveUntraceableBlocks` is desirable.

Regarding transactions: should we allow to add transaction with hash equal to that of removed old transaction? Same question about blocks. I think hashes should still be present in database, so no client code is broken in some unexpected ways.

**Comment by roman-khimov** [comment]
> should we allow to add transaction with hash equal to that of removed old transaction?

It won't happen because of ValidUntilBlock.
