### ISSUE TITLE
Update `run` in VM cli

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#1585]
It still supports only `Main(string, []interface{})` form (at least in doc).
1. Ensure it can be executed with any signature, update tests if needed.
2. Think about loading contract manifest (can be done automatically in `loadgo`).
3. Support `setip`/`jmp` to a specified instruction pointer if (2) will be hard.
4. Implement `reset` instruction which is useful when trying multiple executions.

**Comment by roman-khimov** [comment]
I guess we need manifest now for any non-trivial contract, the thing just won't be really useful without it. (3) shouldn't be needed.
