### ISSUE TITLE
Fix CLI `wallet convert` command

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#1589]
In NEO3 some opcodes were changed, so verification scripts from NEO2 should be parsed by means other than `vm.ParseMultisigContract`. I think, simple ad-hoc function which can extract keys should suffice for conversion purposes.
`import-deployed` wasn't yet introduced in `master-2.x`, may be we can leave it out.

**Comment by roman-khimov** [comment]
We can add some specific function in the CLI, there is no other use for it but conversion. And yeah, support for multisignature contracts can be a nice feature. Deployed ones can be left out, contracts on 2.x have nothing in commong with contracts on 3.x, so there is nothing to transfer/convert.
