### ISSUE TITLE
Mark appropriate methods as `Safe` during compilation

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#1596]
We should mark some methods as safe when emitting contract manifest.
I see two possibilities:
1. If method doesn't call interops or other methods which modify state and doesn't call lambda functions `CALLA`, then mark it as safe. This will lead to false negatives in case when every lambda is private to our contract, but I don't think it is a big deal, as emitted manifest will still be valid.
2. Allow to specify safe methods in config explicitly.

I prefer the first one because it doesn't demand anything from user and minimizes the possibility of emitting invalid manifest.

Related #1594, #1373.

**Comment by fyrchik** [comment]
`System.Contract.Call` is another problem because we doesn't (and can't) have a snapshot to check what method do we call. Probably adding `contract.SafeCall()` compiler interop is the simplest solution.

**Comment by roman-khimov** [comment]
I don't think we can do it automatically in any reliable fashion, but configs will work. It of course makes developer responsible for correctness of these attributes, but that's unavoidable IMO. See neo-project/neo-devpack-dotnet#401 also.
