### ISSUE TITLE
Add CALLT opcode

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#1644]
Port changes from https://github.com/neo-project/neo-vm/pull/382.

**Comment by fyrchik** [comment]
It is not yet used in any way in neo.

**Comment by roman-khimov** [comment]
See neo-project/neo#2185 and neo-project/neo#2200 also.

**Comment by roman-khimov** [comment]
As well as neo-project/neo-vm#388 and neo-project/neo-devpack-dotnet#420.
