### ISSUE TITLE
Update `System.Contract.Call`

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#1646]
Port changes from https://github.com/neo-project/neo/pull/2166, https://github.com/neo-project/neo/pull/2167 .
Effectively, `CallEx` is removed and `Call` is altered.

**Comment by fyrchik** [comment]
neo-project/neo#2211 can be calso done here.

**Comment by roman-khimov** [comment]
Let'd do it step by step with #1647 first.
