### ISSUE TITLE
go get and binary

### ISSUE THREAD

**Issue by gsmachado** [nspcc-dev/neo-go#1650]
Great work, guys!

So... is there a way to modify the go packages a bit to simply be able to `go get -u github.com/nspcc-dev/neo-go/cli` and then it would already produce the `neo-go` bin to the `$GOBIN`?

Just asking, since this would make things slightly simpler to install. 😄

**Comment by gsmachado** [comment]
Just to clarify that this is more a question than a bug/feature/whatever.

**Comment by gsmachado** [comment]
Also, I just want to attach the stacktrace of what happens when I try to execute the `go get` command I mentioned above:

```
root@cc8605da2eab:~/workspace# go get -u github.com/nspcc-dev/neo-go/cli
# github.com/nspcc-dev/neo-go/cli/flags
/go/src/github.com/nspcc-dev/neo-go/cli/flags/address.go:28:2: cannot use AddressFlag literal (type AddressFlag) as type cli.Flag in assignment:
	AddressFlag does not implement cli.Flag (wrong type for Apply method)
		have Apply(*flag.FlagSet)
		want Apply(*flag.FlagSet) error
/go/src/github.com/nspcc-dev/neo-go/cli/flags/fixed8.go:25:2: cannot use Fixed8Flag literal (type Fixed8Flag) as type cli.Flag in assignment:
	Fixed8Flag does not implement cli.Flag (wrong type for Apply method)
		have Apply(*flag.FlagSet)
		want Apply(*flag.FlagSet) error
# github.com/nspcc-dev/neo-go/pkg/core/storage
/go/src/github.com/nspcc-dev/neo-go/pkg/core/storage/redis_store.go:28:21: not enough arguments in call to c.cmdable.Ping
	have ()
	want (context.Context)
/go/src/github.com/nspcc-dev/neo-go/pkg/core/storage/redis_store.go:41:26: not enough arguments in call to s.client.cmdable.Get
	have (string)
	want (context.Context, string)
/go/src/github.com/nspcc-dev/neo-go/pkg/core/storage/redis_store.go:53:21: cannot use string(k) (type string) as type context.Context in argument to s.client.cmdable.Del:
	string does not implement context.Context (missing Deadline method)
/go/src/github.com/nspcc-dev/neo-go/pkg/core/storage/redis_store.go:59:14: not enough arguments in call to s.client.cmdable.Set
	have (string, string, number)
	want (context.Context, string, interface {}, time.Duration)
/go/src/github.com/nspcc-dev/neo-go/pkg/core/storage/redis_store.go:67:11: not enough arguments in call to pipe.Set
	have (string, []byte, number)
	want (context.Context, string, interface {}, time.Duration)
/go/src/github.com/nspcc-dev/neo-go/pkg/core/storage/redis_store.go:70:11: cannot use k (type string) as type context.Context in argument to pipe.Del:
	string does not implement context.Context (missing Deadline method)
/go/src/github.com/nspcc-dev/neo-go/pkg/core/storage/redis_store.go:72:21: not enough arguments in call to pipe.Exec
	have ()
	want (context.Context)
/go/src/github.com/nspcc-dev/neo-go/pkg/core/storage/redis_store.go:78:23: not enough arguments in call to s.client.cmdable.Scan
	have (number, string, number)
	want (context.Context, uint64, string, int64)
/go/src/github.com/nspcc-dev/neo-go/pkg/core/storage/redis_store.go:79:15: not enough arguments in call to iter.Next
	have ()
	want (context.Context)
/go/src/github.com/nspcc-dev/neo-go/pkg/core/storage/redis_store.go:81:25: not enough arguments in call to s.client.cmdable.Get
	have (string)
	want (context.Context, string)
/go/src/github.com/nspcc-dev/neo-go/pkg/core/storage/redis_store.go:81:25: too many errors
root@cc8605da2eab:~/workspace
```

Is it because of the vendors ([this line](https://github.com/nspcc-dev/neo-go/blob/master/Makefile#L66) and `-mod=vendor`) that are missing?

**Comment by fyrchik** [comment]
Hello! Go toolchain does not allow to change binary names in `go get` or `go install`: build flag `-o` used for can't be used in `get` and `install`. So it seems the simplest way is just:
`go get .. && mv $GOBIN/cli $GOBIN/neo-go`.

Also you don't need `-u` flag for this. Does the problem remains when invoking `go get` without `-u`?

**Comment by gsmachado** [comment]
@fyrchik yes, it remains.

I tested on a Ubuntu Bionic docker image.

BTW: I know that `go get` or `go install` doesn't provide a way to specify the output file name. But, I think it would be a great thing if the `cli` binary could be generated just with `go get`, out of the box. Then, people/devs could decide if they want to rename the file or not by themselves.

**Comment by fyrchik** [comment]
@gsmachado what version of Go do you use?

**Comment by gsmachado** [comment]
@fyrchik check it out:

Create a `Dockerfile`:

```
FROM golang:1.15.6
USER root
RUN go get github.com/nspcc-dev/neo-go/cli
```

Then, execute:

`docker build -t test-neo-go ./`

Then, check how it miserably fails. 😄

**Comment by gsmachado** [comment]
aaaaand... the same happens with:

```
FROM golang:1.14
USER root
RUN go get github.com/nspcc-dev/neo-go/cli
```

😄

**Comment by fyrchik** [comment]
The problem occurs because incorrect module versions are fetched. Try to set `GO111MODULE=on`:
```
FROM golang:1.15.6
USER root
RUN export GO111MODULE=on && go get github.com/nspcc-dev/neo-go/cli
```
This works for me.

**Comment by gsmachado** [comment]
@fyrchik oh, sure! Yes, it works.

What about adding this to the documentation (or `README`) somewhere? 😄 

Closing this issue. Thanks!

**Comment by fyrchik** [comment]
@gsmachado Glad to hear!. This setting is already present in our `Dockerfile`, you may want to look at it. Also notice `-ldflags` argument to `go build` there, lack of this can be a problem for contract compilation.
