### ISSUE TITLE
Make core tests less verbose

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#1677]
Right now we have `invokeContractMethod`, `invokeContractMethodBy`, `prepareContractMethod` etc. each of which return errors.
I think, we can simplify this a bit:
1. Make tests look more like `cli` and `vmcli` with some struct carrying necessary context.
2. Provide parameter `t *testing.T` to `invoke*` etc. and don't check errors at call site.

In the end this will look like this:
```go
e := newExecutor(chain, contractHash, committeeSigner, defaultSysfee)
e.checkInvoke(t, "setPrice", true, 100)
e.withSigner(notCommittee).checkInvoke(t, "getPrice", 100)
e.checkInvoke(t, "setPrice", false, "invalid integer")
e.withSigner(walletSigner).checkInvoke(t, "setPrice", nil, 1)
```

This is easier to read, write and maintain.

**Comment by roman-khimov** [comment]
Obsoleted by #2355?

**Comment by fyrchik** [comment]
Yes, closing this in favour of #2355.
