### ISSUE TITLE
Add method overloading

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#1683]
neo-project/neo#2237, we now can have methods with identical names, but different number of parameters and we need to choose an appropriate one for the call.

**Comment by fyrchik** [comment]
I haven't come up with how we can support this in compiler and it's not Go-way, so may be only interop handling should be changed. Essentially, `...interface{}` varargs do the same work.

**Comment by roman-khimov** [comment]
The only thing we need from the compiler is to generate correct code for `deploy(1,2)` and `deploy(1,2,3)` calls, of course our contracts won't expose any overloaded methods.
