### ISSUE TITLE
neo-go cli incorrectly handles backspace for non-ascii characters

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neo-go#1688]
When creating a new wallet with `neo-go wallet init` command, neo go doesn't understand escape sequences and, even if it look correct on the screen, writes corrupted input in the resulting wallet file.

Steps to reproduce:
- Run `wallet init -a -w test.wallet`
- Enter account name with few non-ascii characters (проверка), delete them and continue with regular latin characters (of the label)
- See the `label` field of the resulting wallet file.

Example output:
```
...
 			"label": "провof the label",
...
```

**Comment by roman-khimov** [comment]
1) Normal editing must be supported (we do have readline already in `vm/cli`, so maybe reusing it here is not a bad idea).
2) The input must be checked for UTF-8 validity.
