### ISSUE TITLE
VM: Add Conversion Methods for stack types Byte Array and BigInteger

### ISSUE THREAD

**Issue by decentralisedkev** [nspcc-dev/neo-go#169]
If the type of the item cannot be determined by the opcode, we will store it on the stack as a ByteArrayItem until we need to use it.

This means that Byte Array, will need to override the default methods on abstractItem.

For example:

On the Stack there are two byte arrays b1 and b2. We see OpAdd. So we Pop both b1 and b2, then called b1.Integer() and b2.Integer() to convert them both to Integers, then we can add them.

We would do this for most of struct types, except for stack types like Map because for example there is an explicit NEWMAP opcode

**Comment by decentralisedkev** [comment]
This is completed, but will leave it open, until it is checked a couple times

**Comment by roman-khimov** [comment]
ByteArray to Int conversion is implemented in dev and I think this issue could be closed for now, any bugs should be filed as new issues.
