### ISSUE TITLE
VM : Add unifying Documentation

### ISSUE THREAD

**Issue by decentralisedkev** [nspcc-dev/neo-go#172]
To my knowledge implementing a VM in another language will require one to read other languages implementation.

Creating a readme with the specifications of the VM will make ti easier to implement in newer languages and it will also allow all languages to have one point of reference.

The documentation should ideally be split into two parts; the stack and it's types and then the neo-vm.

The section on the stack and it's types would include all possible types of stack items, what type of stack it is and the rules around integers such as when they can overflow, what is the max neg/positive integer allowed, what happens if the integer is "-0", how to convert from an integer to a byte slice (with endian)...

The section on the vm would include the opcodes available and a step by step instruction on how to implement them, this should also include the effect that the opcodes have on the stack. The type of structure that the vm is(eval stack/invocation stack...), the possible vm states...

The section on the stack and it's types should come first.

It would be best to split this into two tasks; the stack and it's types, which is the foundation.Then the VM.

The stack and it's types can also be broken down into separate PRs, starting with the types.

Please also include a Table of contents and be concise with your definitions.

**Comment by decentralisedkev** [comment]
Additionally, we can include a separate documentation for a go specific implementation, but it is not near completion so it will not be put as an issue yet.

**Comment by roman-khimov** [comment]
I think it's out of scope for neo-go project. There is an project to create an implementation-agnostic specification for NEO:
https://github.com/neo-project/specification
and IMO all the effort should be funneled there.
