### ISSUE TITLE
OnNEP17Payment fails with storage context initialization in init()

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neo-go#1725]
neo-go version 0.92.0-159-g71494e6a

If smart contract has storage context initialization in `init()` function, then asset transfer to contract address fails with error:

`can't add system fee to transaction: bad vm state: FAULT due to an error: error encountered at instruction 2 (SYSCALL): error during call from native: error encountered at instruction 5 (SYSCALL): failed to invoke syscall: missing call flags: 01110 vs 00001`.

I tried it with this smart contract:
```go
package example

import (
	"github.com/nspcc-dev/neo-go/pkg/interop"
	"github.com/nspcc-dev/neo-go/pkg/interop/binary"
	"github.com/nspcc-dev/neo-go/pkg/interop/runtime"
	"github.com/nspcc-dev/neo-go/pkg/interop/storage"
)

var ctx storage.Context

func init() {
	ctx = storage.GetContext() // remove me and onNEP17Payment will work
}

func OnNEP17Payment(from interop.Hash160, amount int, data interface{}) {
	runtime.Log("Got NEP17 payment: " + binary.Itoa(amount, 10))
}
```

Is it expected behavior? Should I avoid storage context initialization in `init()`?

**Comment by alexvanin** [comment]
Seems it has nothing to do with `init()`. You just can't initialize context storage at `OnNEP17Payment` execution. This one fails the same way:

```go
var ctx storage.Context

func OnNEP17Payment(from interop.Hash160, amount int, data interface{}) {
	ctx = storage.GetContext() // remove me and onPayment will work
	runtime.Log("Got NEP17 payment: " + binary.Itoa(amount, 10))
}
```

**Comment by fyrchik** [comment]
1. Native contract methods are called with the required set of flags.
2. `ReadStates` is a flag needed for the `storage.GetContext` syscall.
3. `transfer` doesn't require `ReadStates` flag.
4. `onNEP17Payment` is called from `transfer`.

(3) seems to be wrong, because, obviously, to write new balance, we read the old one.
