### ISSUE TITLE
Test invocation always fails

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neo-go#1731]
neo-go version 0.93.0-pre-189-g2ee755e0

Pretty new issue, haven't seen it in 0.93.0-pre-158-g71494e6a
All test invocations from CLI or client fails with error: `json: cannot unmarshal number 0.0099891 into Go struct field invokeAux.gasconsumed of type int64`

**Comment by roman-khimov** [comment]
#1723, certainly.

**Comment by alexvanin** [comment]
Tried to use chain dump created with 0.93.0-pre-189-g2ee755e0 in old neo-go single node environment. That caused the issue.
