### ISSUE TITLE
VM CLI is not UTF-8 compatible

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#1743]
```
NEO-GO-VM > loadgo фыва/test.go
Error: Unknown rune: 1092
NEO-GO-VM > loadnef фыва/test.nef фыва/test.json
Error: Unknown rune: 1092
```

**Comment by fyrchik** [comment]
There is an issue in `ishell` repo https://github.com/abiosoft/ishell/issues/22
Current workaround is to enclose name in `"` (added a test, it works).

**Comment by fyrchik** [comment]
This originates from now archived dependency of ishell https://github.com/flynn-archive/go-shlex

**Comment by fyrchik** [comment]
Probably not a priority, but let it be here https://github.com/fyrchik/go-shlex/commit/cd7f49bfd959d7507868ec95b28ca4e86181d3a5 , will discuss it later.

**Comment by roman-khimov** [comment]
Is there any decent replacement for `ishell`? I don't see it being actively maintained. We should of course wait for some reaction on abiosoft/ishell#22, but it's almost a four year old bug now.

**Comment by fyrchik** [comment]
I have found only https://github.com/mkouhei/gosh which is also unmaintained. https://github.com/spf13/cobra and https://github.com/urfave/cli are maintained but have no interactive interface.
