### ISSUE TITLE
Add onNEP*Payment compliancy checks

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#1767]
As we can't infer whether contract wants to support proper onNEP*Payment interfaces or not from metadata (neo-project/neo#2355) we should imply for now that if it declares these functions it wants to (but of course it should be disabled with `--no-standards`) and thus check signatures of these methods against their standard definitions.

**Comment by fyrchik** [comment]
Don't we already do it here? https://github.com/nspcc-dev/neo-go/blob/master/pkg/compiler/compiler.go#L249
These checks are executed separately from standard checks.

**Comment by roman-khimov** [comment]
Yep, somehow overlooked this.
