### ISSUE TITLE
Some interops inside for loop break it

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neo-go#1784]
neo-go version 0.94.0-pre-68-gf264996f

I found out that some interops that called inside for loop, break it after first iteration with `error encountered at instruction 1220 (INC): runtime error: invalid memory address or nil pointer dereference` message. 

For example:

```go
func Test() {
	k1 := binary.Base58Decode([]byte("tmYZqjzuUd9r6jfXKyewHKNyeYtzq2sqrYcBJhYKVE1w"))
	k2 := binary.Base58Decode([]byte("t75T8uckRGVb1xUWXDGSnAoBfNT8T63vbohLA2qny3pz"))
	k3 := binary.Base58Decode([]byte("fdfrD7c8Md8BDPU5sC1FdQSgZyBvxnGMEDZ9aKX1Ru6u"))
	k4 := binary.Base58Decode([]byte("y2ZikmrvCbTmbuvNEZHKu9QLTwQ5K1hqK79k1AcEoSn8"))
	k5 := binary.Base58Decode([]byte("2AKA34u97VCj6qPWHaG4mbiRwWs5LUPkyef7ZUWJhWjur"))
	k6 := binary.Base58Decode([]byte("o7fX3sizfR2ztVK1ViSfJPM1CiPF1BtEwu8ocs895ZJW"))
	k7 := binary.Base58Decode([]byte("284mdZikGXka3izdykdtWmJnRBYGM2fgpZNx7fYer3udY"))

	ir := []interop.PublicKey{k1, k2, k3, k4, k5, k6, k7}

	for _, node := range ir {
		contract.CreateStandardAccount(node)
	}
}
```

I got such errors with `contract.CreateStandardAccount`, `binary.Serialize`, `binary.Itoa`, `binary.Base58Encode` interops. However it works fine with `runtime.Log`.

**Comment by fyrchik** [comment]
The problem is that some control-flow statements can drop stack items (for algorithms implemented using stack variable such as `range` loop). For inline calls only part of stack (used in inlined body) needs to be dropped.
