### ISSUE TITLE
cli: allow to sign dumped transaction by several non-multisig signers

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#1798]
After #1797 we fully support transaction's cosigners in `invoke*` CLI commands. At the current moment, we only have the `wallet multisig sign` command to sign dumped transactions, but we don't have an analogue for standard signature/contract signers.

We need something like `wallet sig sign` command which allows signing dumped transactions by several non-multisig signers.

**Comment by roman-khimov** [comment]
This needs to be unified for different usecases in CLI interface (`multisig sign` vs `sig sign` is somewhat misleading). The essence of the operation is the same, we have incomplete tx and we add some signature to it. We at the same time explicitly pass the address we want to add our signature to, so it's easy to see what the user wants (add something to multisig or add signature for some signer). `wallet sign`?
