### ISSUE TITLE
compiler: util.Equals bug (?)

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#1821]
Consider the following contract with `Verify` method:
```
package testdata

import (
	"github.com/nspcc-dev/neo-go/pkg/interop/runtime"
	"github.com/nspcc-dev/neo-go/pkg/interop/util"
)

func Verify() bool {
	res := util.Equals(true, true)
	if res == true {
		runtime.Log("true")
	} else {
		runtime.Log("false")
	}
	return true
}
```

When I call `verify`, it logs `false`.

However, the following example returns `true`:
```
package testdata

import (
	"github.com/nspcc-dev/neo-go/pkg/interop/util"
)

func Verify() bool {
	return util.Equals(true, true)
}
```

**Comment by AnnaShaleva** [comment]
It may be connected with the recent inlining changes.

To reproduce the bug with the more complicated smart-contract, re-generate our test chain from `helper_test.go`, update `verifyContractHash` (the hash of `pkg/rpc/server/testdata/verification_sontract.go`) and run `TestInvokeVerify` RPC-client test. It will fail with `false` on stack.

**Comment by roman-khimov** [comment]
> thus == in if actually compares true and 1

But it should be comparing 1 and 1, isn't it?
