### ISSUE TITLE
Use numeric comparison for booleans?

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#1823]
Related to #1821. We can technically use `NUMEQUAL` instead of `EQUAL` for boolean values comparison. That of course won't solve `util.Equals` problem, but least produce more sensible result for `(a == true) == true`. Thoughts, opinions? My fear is that we can face the same issue with some value returned from calls/contracts (that can be of any real type). Also related to neo-project/neo#2372.

**Comment by fyrchik** [comment]
What do you mean by "more sensible result"? Less cost in GAS (`NUMEQUAL` is cheaper than `EQUAL`)?

**Comment by roman-khimov** [comment]
It's not often that we do `== true` comparisons, and it's not entirely clear how this will affect existing code, thus we can leave it as is for now.
