### ISSUE TITLE
Move fee calculations to DEV

### ISSUE THREAD

**Issue by dauTT** [nspcc-dev/neo-go#186]
Move fee methods to DEV:
```
FeePerByte
NetworkFee
SystemFee
IsLowPriority
```
reference: 
https://github.com/CityOfZion/neo-go/blob/master/pkg/core/blockchain.go#L632

**Comment by dauTT** [comment]
@decentralisedkev ,

I believe that the above methods should en up in newly created 
```
package chain
```
Correct?

**Comment by roman-khimov** [comment]
Obsolete, closing this (see #283).
