### ISSUE TITLE
Let node announce address other than the one it's bound to

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neo-go#1868]
If the node is bound to an IP address behind NAT, but it's available via port-forwarding on the router, there is no way for it now to properly announce itself.

The proposed solution is to add one more option, like `AnnounceAddress/Port` additionally to `Address` and `Port` and use them to identify node in p2p communication.

**Comment by roman-khimov** [comment]
Actually the node only announces its port number, address is derived from the connection on the other side (and it only sees public address). So we can add `AnnouncedPort` configuration, but I think usually you can make node use the same port on the internal address as the one you're providing on public IP.

**Comment by realloc** [comment]
Having `AnnouncedPort` option is still better than nothing. I'd appreciate if you add this feature.
