### ISSUE TITLE
VM: Refactor StepInto, StepOver, StepOut

### ISSUE THREAD

**Issue by decentralisedkev** [nspcc-dev/neo-go#187]
There seems to be two implementations for the StepInto() method.

neo-python uses it to process a single op-code and leaves the vm in a running state, if no error was found : NONE

https://github.com/CityOfZion/neo-python/blob/e806b355d98d3ac2bab2b7d71776829a3dadc3e4/neo/VM/ExecutionEngine.py#L988

While neo-vm uses it to process single op-code and if no error was found, the vm is left in a suspended state: BREAK. 

https://github.com/neo-project/neo-vm/blob/2e5981cf3ea6ec1e110ece72407ba92293a6027f/src/neo-vm/ExecutionEngine.cs#L1681

In general the nomenclature for stepInto suggests that we are in debug mode, so this should be changed in the vm implementation to match

**Comment by volekerb** [comment]
I believe we have to figure out one behavior so all VM implementation behave the same way. 
Take a look at NEO sharp VM which will be used soon:
https://github.com/CityOfZion/neo-sharp/blob/development/src/NeoSharp.VM.NeoVM/ApplicationEngine.cs#L479

**Comment by roman-khimov** [comment]
To be fair, the distinction between BREAK and NONE seems artificial to me, but still we need to match original VM's behavior, because tests from #196 do specify states and do use steps.
