### ISSUE TITLE
VM: Implement Stack Maths Opcodes

### ISSUE THREAD

**Issue by decentralisedkev** [nspcc-dev/neo-go#188]

**Comment by dauTT** [comment]
**TODO:**

| Opcode | issue | status| PR|
| ------------- | ------------- |------------- |------------- |
|        INC       | #220 | open| |
|	DEC         | #220 | open| |
|	SIGN       |#221  | open| |
|	NEGATE      | #221 | open| |
|	ABS         | #222 | open| |
|	NOT         | #222 | open| |
|	NZ         | #223 | open| |
|	ADD        |  | closed| |
|	SUB         |  | closed| |
|	MUL         | #223 | open| |
|	DIV        | #224 | open| |
|	MOD        |  #224| open| |
|	SHL        |  | open| |
|	SHR         |  | open| |
|	BOOLAND   | #226 | open| |
|	BOOLOR     | #226 | open| |
|	NUMEQUAL    | #227| open| |
|	NUMNOTEQUAL | #227 | open| |
|	LT          | #228 | open| |
|	GT         | #228 | open| |
|	LTE         | #229 | open| |
|	GTE        | #229 | open| |
|	MIN        | #230 | open| |
|	MAX       | #230 | open| |
|	WITHIN     | #230 | open| |

**Comment by decentralisedkev** [comment]
Thanks for the checklist

**Comment by volekerb** [comment]
Last one #261 closed. So closing this one
