### ISSUE TITLE
VM : Implement Stack Flow Opcodes

### ISSUE THREAD

**Issue by decentralisedkev** [nspcc-dev/neo-go#189]

**Comment by dauTT** [comment]
TODO:

| Opcode | status| PR|
| -------------|------------- |------------- |
|          NOP      | open| |
|	 JMP         |  open|  |
|	JMPIF       | open| |
|	JMPIFNOT       | open| |
|	CALL       | open| |
|	RET       | open| |
|	APPCALL       | open| |
|	SYSCALL       | open| |
|	TAILCALL       | open| |

**Comment by volekerb** [comment]
CALL, APPCALL, SYSCALL, TAILCALL left

**Comment by roman-khimov** [comment]
Not an issue for master (see #283), obsolete, closing.
