### ISSUE TITLE
VM: Implement Stack Manipulation Opcodes

### ISSUE THREAD

**Issue by decentralisedkev** [nspcc-dev/neo-go#190]

**Comment by dauTT** [comment]
TODO

| Opcode | status| PR|
| -------------|------------- |------------- |
|      DUPFROMALTSTACK          | open| |
|TOALTSTACK	          |  open|  |
|	FROMALTSTACK       | open| |
|	XDROP       | open| |
|	XSWAP       | open| |
|	XTUCK       | open| |
|	DEPTH       | open| |
|	DROP       | open| |
|	DUP       | open| |
|	NIP       | open| |
|	OVER             | open| |
|	PICK             | open| |
|	ROLL             | open| |
|	ROT             | open| |
|	SWAP             | open| |
|	TUCK             | open| |

**Comment by volekerb** [comment]
All PRs are merged, so closing this one
