### ISSUE TITLE
VM: Implement Stack Isolation Opcodes

### ISSUE THREAD

**Issue by decentralisedkev** [nspcc-dev/neo-go#192]

**Comment by dauTT** [comment]
TODO

| Opcode | status| PR|
| -------------|------------- |------------- |
|      DUPFROMALTSTACK          | open| |
|TOALTSTACK	          |  open|  |
|	FROMALTSTACK       | open| |
|	XDROP       | open| |
|	XSWAP       | open| |
|	XTUCK       | open| |
|	DEPTH       | open| |
|	DROP       | open| |
|	DUP       | open| |
|	NIP       | open| |
|	OVER             | open| |
|	PICK             | open| |
|	ROLL             | open| |
|	ROT             | open| |
|	SWAP             | open| |
|	TUCK             | open| |

**Comment by decentralisedkev** [comment]
These would be stack manipulation, stack isolation would be CALL_I, CALL_E, CALL_ED,CALL_EDT, CALL_ET

**Comment by roman-khimov** [comment]
Notice that these were deleted in NEO 3.0, so we may end up not implementing them at all (see #362 also).

**Comment by roman-khimov** [comment]
Contracts in NEO 2.0 are using them, so they're needed for real compatibility.
