### ISSUE TITLE
VM: Implement Stack Crypto Opcodes

### ISSUE THREAD

**Issue by decentralisedkev** [nspcc-dev/neo-go#194]

**Comment by dauTT** [comment]
TODO

| Opcode | status| PR|
| -------------|------------- |------------- |
|     SHA1           | open| |
|	SHA256          |  open|  |
|	HASH160          |  open|  |
|	HASH256          |  open|  |
|	CHECKSIG          |  open|  |
|	CHECKMULTISIG          |  open|  |

**Comment by volekerb** [comment]
Left only checksig and multisig
https://github.com/nspcc-dev/neo-go/issues/269
so closing this one
