### ISSUE TITLE
VM: Implement Array Opcodes

### ISSUE THREAD

**Issue by decentralisedkev** [nspcc-dev/neo-go#195]
This issue cannot be completed without first completing this: https://github.com/CityOfZion/neo-go/issues/167

**Comment by dauTT** [comment]
TODO

| Opcode | status| PR|
| -------------|------------- |------------- |
|       ARRAYSIZE         | open| |
|PACK	          |  open|  |
|PACK	          |  open|  |
|PACK	          |  open|  |
|PACK	          |  open|  |
|PACK	          |  open|  |
|PACK	          |  open|  |
|PACK	          |  open|  |

	PACK      
	UNPACK    
	PICKITEM 
	SETITEM   
	NEWARRAY  
	NEWSTRUCT
	APPEND   
	REVERSE  
	REMOVE

**Comment by roman-khimov** [comment]
UNPACK, REVERSE and REMOVE are not implemented currently.
