### ISSUE TITLE
cli: add support of manifest.Extra and manifest.Permissions to `yaml` smartcontract config

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#1964]
We need to be able to specify smartcontract's author/email/etc. for `manifest.Extra` and permissions for `manifest.Permissions` via `yaml` configuration file during a contract compilation.

After this the following fields should be added to the non-native NameService contract manifest (via `yaml` config file):
-  [ManifestExtra("Author", "Erik Zhang")]
-  [ManifestExtra("Email", "erik@neo.org")]
-  [ManifestExtra("Description", "Neo Name Service")]
-  [ContractPermission("*", "onNEP11Payment")]

(ref https://github.com/neo-project/non-native-contracts/commit/7c73c9a44ce36eb4e088cceed80a40a37189bd1f).

**Comment by roman-khimov** [comment]
Extra fields are extra (they were mandatory in Legacy), I don't think we care about them. But permissions do need to be represented with all capabilities they provide.
