### ISSUE TITLE
list address method for neo-go legacy

### ISSUE THREAD

**Issue by gitloverr** [nspcc-dev/neo-go#2005]
hi everyone,

can I use the listaddress method for wallet via rpc req.? 

this method seems unsupported. how do I list the addresses on neo-go?

thank you

**Comment by roman-khimov** [comment]
We have a different wallet model, you only give keys to the node if it's a consensus node (and thus it needs to sign things) or SV/Oracle node in N3. As a regular user you have your NEP-6 wallet and you use it with CLI like this:
```
neo-go wallet dump -p path-to-wallet.file
```
Which will output wallet in JSON and you'll have addresses there. Transfers/invocations are done similarly, transaction is created and signed locally and then pushed via RPC endpoint you provide in parameters.

**Comment by gitloverr** [comment]
hi,

thank you for your response @roman-khimov. can I use the wallet dump method over rpc? I couldn't find it, in rpc document. but I tried this way:

`curl -X POST --data '{"jsonrpc": "2.0","method":"wallet","params":["dump":{"my-wallet.path"}],"id": 1}' -H 'content-type:application/json;' 127.0.0.1:10332`


but I didn't get a successful result... How can I use it over rpc as correctly? Can you share with me? 

thank you

**Comment by roman-khimov** [comment]
I'm not sure what you're trying to do. NeoGo RPC node won't go over file system to open/dump wallets, there is no API for that (everything it supports is documented). But you can do it locally with CLI, your wallet is standard NEP-6.
