### ISSUE TITLE
about the wallet create command parameters... 

### ISSUE THREAD

**Issue by gitloverr** [nspcc-dev/neo-go#2009]
hi everyone,

can I pass the name, passphare values of "wallet create" command as directly like that

`./bin/neo-go wallet create -p ./wallet-data/my-wallet.path **--name BLABLA --passphrase BLABLAPASS** `

because I would like create the address from remotely access.After send create wallet the node is waiting for answers like this:

```
Enter the name of the account >...
Enter passphrase >...
Confirm passphrase >...

```

I would like to send these parameters  as directly...

do you have any solution suggestions??

thank you

**Comment by roman-khimov** [comment]
Not currently possible directly, but you can always use some `expect`.
