### ISSUE TITLE
Method 'getnep17balances' not supported

### ISSUE THREAD

**Issue by gitloverr** [nspcc-dev/neo-go#2013]
hi everyone,

getnep17balances method seems as supported but I'm getting this response:

Request: 
`curl -X POST --data '{"jsonrpc": "2.0","method": "getnep17balances","params": ["AKTzaZRAyx3eeDW1UkEQ9K2ftcgPMxocuz"],"id": 1}' -H 'content-type:application/json;' 127.0.0.1:10332`

Response:
`{"id":1,"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found","data":"Method 'getnep17balances' not supported"}}`

Why? How do I get the wallet balance?

thank you

**Comment by roman-khimov** [comment]
Which NeoGo version are you using? `getnep17balances` is for NEP17 tracking which is Neo N3 standard (since preview4 or NeoGo 0.92.0) while Neo Legacy has NEP5 and `getnep5balances`.

**Comment by gitloverr** [comment]
that works! thank you
nep5 standarts is valid for neolegacy is it? Did I get right? nep17 only for neo N3? @roman-khimov

**Comment by roman-khimov** [comment]
> nep5 standarts is valid for neolegacy is it?

Yes.

> nep17 only for neo N3?

Yes.

**Comment by gitloverr** [comment]
the getnep5balances method does it show neo balance of wallet? @roman-khimov

**Comment by roman-khimov** [comment]
It's about NEP-5 tokens and NEO is not a NEP-5 token in Legacy (see getunspents and other UTXO-related methods). It is NEP-17 in N3 though.
