### ISSUE TITLE
Can't find matching token prompt

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neo-go#2014]
If you create new wallet file with neo-go and then send assets from this wallet, you'll see missing matching token prompt. 

```
neo-go wallet nep17 transfer -w wallet.json -r [endpoint] --from [address] --to [address] --token GAS --amount 50
Password > 
Can't find matching token in the wallet. Querying RPC-node for balances.
db54ea02b92b9cccaa9c1b547645637c395fdea8d638e2bc3fc7809d5f76eccc
```

`Can't find matching token in the wallet. Querying RPC-node for balances.` looks like error message. Several people asked me what went wrong at deposit in neofs-dev-env because they misinterpreted this line as an error.

Do we really need to prompt this if querying RPC-node for balances finished successfully?

**Comment by roman-khimov** [comment]
It's annoying, true, we can drop it.
