### ISSUE TITLE
Check permissions of native contract calls at compile time

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neo-go#2022]
neo-go v0.95.2+ expects `permissions` section in the manifest in case of state changing RPCs to other contracts. Unfortunately there are no compile time warnings about that. If you create contract with migration support, then you *have to* add `update` method in permissions list in manifest.

It is not possible to track all invocations inside the contract. However I suppose it is possible to track native contract invocations. We have beautiful wrappers such as `gas.Transfer` or `management.Update` in the library and we know whether they change state or not. I think compiler can throw a warning if you use one of such methods and do not include it in manifest.

**Comment by roman-khimov** [comment]
> neo-go v0.95.2+ expects permissions section in the manifest

True, 4467e2cbfdcd9539b5a85287ab64cc43654f1f36 changed the default behavior, previously it was more like
```
permissions:
- methods: '*'
```
We can auto-add native contracts, btw, or generate relevant YAML section at request (probably better option).
