### ISSUE TITLE
management.Destroy does not require manifest permission

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neo-go#2024]
At https://github.com/nspcc-dev/neo-go/pull/2023 I noticed that `management.Destroy` method can be successfully invoked without any mention in `permissions` section of manifest. Is it expected? I thought it should behave the same as `management.Update`.

**Comment by roman-khimov** [comment]
Not really. Does it happen in timer contract?

**Comment by alexvanin** [comment]
I noticed it in timer contract and confirmed in `nft-nd` (it has explicit `Destroy` method).

**Comment by alexvanin** [comment]
The issue is not realated to `management.Destroy` method. 

It seems that such wildcard in contract address ignore list of methods. With 
```json
[{"contract":"*","methods":["foobar"]}]
``` 
in manifest I successfully invoked both `management.Update` and `gas.Transfer` methods. If you specify the contract address, then it works as intended.
