### ISSUE TITLE
run testnet node with dump data

### ISSUE THREAD

**Issue by bettybao1209** [nspcc-dev/neo-go#2027]
![image](https://user-images.githubusercontent.com/12050350/123760632-a1509f00-d8f3-11eb-9013-1fd318ebf2e7.png)

it seems the process is not successful. Could you tell me where I am wrong?

**Comment by roman-khimov** [comment]
Most likely it's #1991. You can strip the first 4 bytes of the dump and then it'll be accepted.

**Comment by roman-khimov** [comment]
And it should be solved now after #2061.
