### ISSUE TITLE
Unable to transfer non-native NEP-17 tokens

### ISSUE THREAD

**Issue by hal0x2328** [nspcc-dev/neo-go#2040]
neo-go is unable to transfer non-native NEP-17 tokens due to an unmarshalling error while processing the JSON retrieved from the RPC method `getcontractstate`

Specifically, an `UnmarshallTypeError` occurs when neo-go tries to unmarshal `nef.tokens.callflags`. It appears that a custom `MarshalJSON`/`UnmarshalJSON` is needed but missing in `pkg/smartcontract/callflag/call_flags.go`. This causes neo-go to exit with the error message `can't fetch matching token from RPC-node: NEP-17 token was not found`.

The native NEP-17 tokens have an empty `nef.tokens` array which is why they can be transferred without error.

This was tested using the NEP-17 token contract 0x0a8b0c0b1981738f468dc630220df18fbb85ff87 (I can provide test tokens if needed for replicating this issue).

**Comment by roman-khimov** [comment]
C#:
```
         "tokens" : [
            {
               "hash" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
               "hasreturnvalue" : true,
               "callflags" : "All",
               "method" : "getContract",
               "paramcount" : 1
            },
            {
               "hash" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
               "callflags" : "All",
               "method" : "update",
               "hasreturnvalue" : false,
               "paramcount" : 3
            }
         ],
```
Go:
```
         "tokens" : [
            {
               "callflags" : 15,
               "paramcount" : 1,
               "hash" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
               "method" : "getContract",
               "hasreturnvalue" : true
            },
            {
               "hasreturnvalue" : false,
               "paramcount" : 3,
               "callflags" : 15,
               "hash" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
               "method" : "update"
            }
         ],

```

**Comment by roman-khimov** [comment]
> neo-go is unable to transfer non-native NEP-17 tokens

BTW, this should only be a problem if using neo-go with C# RPC server, is that the case?

**Comment by hal0x2328** [comment]
> > neo-go is unable to transfer non-native NEP-17 tokens
> 
> BTW, this should only be a problem if using neo-go with C# RPC server, is that the case?

Probably; is there an authoritative source for a list of public N3 TestNet neo-go RPC nodes, and can I add those to the Dora monitor?

**Comment by roman-khimov** [comment]
I don't think they're published anywhere, but https://rpc1t.n3.nspcc.ru:20331 is a good one for testnet.
