### ISSUE TITLE
MPT data cleanup for RemoveUntraceableBlocks

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#2095]
We have `KeepOnlyLatestState` to remove old MPT data, but it strips everything up to the latest state. We at the same time have `RemoveUntraceableBlocks` which makes node remove old blocks/transactions, but it doesn't do anything else. So if we're to have `KeepOnlyLatestState` set to `false` and `RemoveUntraceableBlocks` set to `true` the node will drop old blocks, but keep all MPTs at the same time which doesn't make a lot of sense. I think it'd be appropriate to drop old MPTs along with corresponding blocks in this configuration.

**Comment by roman-khimov** [comment]
It has some intersections with the `KeepOnlyLatestState` problem for P2P state exchange (#1992). Nodes need to keep not just the latest state, but also P1 and P2.
![2095-trees](https://user-images.githubusercontent.com/22092804/129541660-fee2cfaa-6827-4abd-9b8b-bdabaf3b37fd.png)

**Comment by roman-khimov** [comment]
So we need to keep some set of MPT states, either `[Rn-traceable...Rlatest]` as here or `[Rp₂, Rp₁, Rlatest]` as with `KeepOnlyLatestState` and state synchronization enabled (deleting `Rp₂` every `StateSyncInterval`).

**Comment by roman-khimov** [comment]
After some testing (luckily, mainnet is >900K blocks now) I can agree with https://github.com/nspcc-dev/neo-go/pull/2137#issuecomment-925878341, GC-based solutions spend like 95-99% of their time iterating over MPT and updating generations, the seek-delete part is then very fast. The biggest problem is that MPT grows fast over time and with 904906 dump and 10K generations my latest GC runs took more than 7 minutes (even with 100K generations it can be more than 9m per cycle). So while this generation update can be done asynchronously to the other node activities (unlike seek-delete) it still costs too much.

I had an idea of moving the generation data into the key, but probably it's not a good idea either, both because it makes reads cost more (up to three accesses to the DB instead of one) and especially since it doesn't solve the MPT traverse problem. Seek-delete can be made faster with this, but it's not a problem anyway.

So we need some scheme that will allow to make some judgement over node's validity just by looking at it (while seeking), without going through MPT. And I think I have one.

We can use `hash, height` keys with `value, active, (refcount | height)` values. The operation is as follows:
 * we have refcounting enabled with our regular meaning (the number of references corresponds to the latest root)
 * the height in the key is the height of node addition
 * `active` flag is `true` if the node is active in the latest root, in this case we have refcount stored afterwards
 * if `active` flag is `false`, then the node is not active and it has the block number where it was deleted stored afterwards
 * when we're updating an already existing node we just manage the refcounter as usual
 * when a new node appears we check for the presence of some older one by doing a seek with hash prefix:
   - if there is no node, we add one appending current height to the key
   - if there is an old node, but it's inactive, we do the same
   - if there is an old one and it's active we update the refcounter as usual
 * when the refcounter goes to zero and the node needs to be deleted we mark it as inactive with height of the block where the deletion happened

Notice that the main logic only creates/updates KV pairs in the DB, it never deletes them. And when updates are done one type of the update is final, that is the deactivation, after it the KV pair is never changed again (a new key will be used if the node is to reappear). Now the GC thread can come in and do its job:
 * seek over the whole MPTData prefix, look at values:
   - active ones are not touched
   - block number is extracted from inactive ones and compared to the current latest block number we need to keep, if it's too old, the key is dropped, if not it's kept

This thread can be asynchronous, if it doesn't see any new keys added that's fine, if it doesn't get some updates it's not a problem either (all of this will be handled in subsequent GC runs); when it deletes something nothing breaks in the MPT handling logic (those won't be used again anyway).

The overhead is rather minimal compared to our regular refcounter, it's just that we never delete things and to get something we need to do a Seek instead of Get. Most of the time this Seek will yield exactly one result for us, so it shouldn't be a problem. GC can be run at any intervals with this scheme.

@fyrchik, @AnnaShaleva, what do you think? I'll probably try implementing that.

**Comment by fyrchik** [comment]
@roman-khimov First, some questions:
1. When operating with `RemoveUntraceableBlocks` setting, GC just deletes blocks with `deleted height < current - MaxTraceableBlocks`, right?
2. When operating without any history removal, is it possible to store the same MPT node multiple times? Or does GC also work in this case?

> Most of the time this Seek will yield exactly one result for us, so it shouldn't be a problem. 
But can we just iterate backwards and take the first result? (given that key-height is stored as big-endian). This way `Seek` will always yield one item.

I see only 2 points of slow-down:
1.  While `Seek` has the same cost as `Get` for `bbolt` or `leveldb` it can incur non-zero overhead for our `MemCached` wrapper, where `Seek` requires iterating over the map (making n `Put`s quadratic in time). But nothing stops us from implementing memory caching a bit differently for this use-case.
2. Because inner nodes change on every leaf change, and refcount=1 for nodes close to the root, we will put them in DB instead of deleting (because we need to set deletion height). This will increase allocations, (if less leaves are touched, the relative overhead should (?) be _greater_). I wonder how we will behave in this case (many blocks, small number tx per block) when restoring from dump. May be nodes which are born and die between flush cycle could be deleted immediately, in some circumstances.

Otherwise, a good solution, I think storing height in key is a powerful idea we have missed in our earlier discussions.

**Comment by roman-khimov** [comment]
> When operating with RemoveUntraceableBlocks setting, GC just deletes blocks with deleted height < current - MaxTraceableBlocks, right?

At the moment it's done right in the `storeBlock`, but yes, it can be moved to the GC phase too.

> When operating without any history removal, is it possible to store the same MPT node multiple times? 

In this case the keys are just hashes, it makes little sense mangling them.

> But can we just iterate backwards and take the first result?

Yeah, that's what I have implemented already.

> Because inner nodes change on every leaf change, and refcount=1 for nodes close to the root, we will put them in DB instead of deleting (because we need to set deletion height).

That's the main source of garbage, but we actually will just overwrite them (with the same length, so it's not a huge problem).

> May be nodes which are born and die between flush cycle could be deleted immediately, in some circumstances.

I think these are handled already, we're refcounting internal changes before the `Flush` and their refcount is zero.

**Comment by roman-khimov** [comment]
> While Seek has the same cost as Get for bbolt or leveldb it can incur non-zero overhead for our MemCached wrapper

<img width="829" alt="Screenshot_20220131_095019" src="https://user-images.githubusercontent.com/22092804/151750626-c6441d33-fff5-466b-91a8-dd0cc23297e8.png">
