### ISSUE TITLE
RemoveUntraceableBlocks and NEP-17 tracking

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#2096]
We never ever touch NEP-17 transfers, so they'll keep adding up even with `RemoveUntraceableBlocks` set to `true`. I'd expect this data to be deleted at the same time with blocks, but it's not trivial to do that with current DB scheme.

**Comment by AnnaShaleva** [comment]
We also need to remove outdated NEP-17 transfers during state exchange process after state sync is completed when state jump is performing. The only outdated NEP-17 transfers we have by this moment is genesis-related transfers (for height 0). Ref. #2019.

**Comment by roman-khimov** [comment]
If we're to have #2263 implemented it'll be possible to drop old entries by iterating over batch keys, but they start with account hash, so while we can skip some records based on the time data we can't avoid going through all accounts (and we'll have many of them). Reversing the key into "date + account" from "account + date" is problematic wrt batching scheme and RPC.

Maybe we can store all accounts touched by a block in the block data itself? We remove transactions in a similar way, so if we're to store accounts we might also drop stale transfer data by iterating over just the accounts we need?

**Comment by roman-khimov** [comment]
Current storage scheme seems to be sufficient, we can handle stale entries in GC routine of #2095.
