### ISSUE TITLE
Chain: Add Verification logic to chain package

### ISSUE THREAD

**Issue by decentralisedkev** [nspcc-dev/neo-go#211]
Currently the chain is missing two components:

- The verification logic for a block and tx

- A suitable place to insert the genesis block

More information has been added in the package with XXX

**Comment by dauTT** [comment]
As the verification of Tx is a huge undertaken in itself, I have created a separate issue for this.
https://github.com/CityOfZion/neo-go/issues/214

**Comment by volekerb** [comment]
Looks like this issue is related to [12](https://github.com/nspcc-dev/neo-go/issues/12) and [214](https://github.com/nspcc-dev/neo-go/issues/214) but here it has description which covers both of them. Am I missing smth?

**Comment by roman-khimov** [comment]
I think now it duplicates #12, so this one can be closed.
