### ISSUE TITLE
Add public key to script hash & address in conversion utility

### ISSUE THREAD

**Issue by EdgeDLT** [nspcc-dev/neo-go#2121]
I have a small feature request!

It would be nice to be able to use `./neo-go util convert <publicKey>` and get both the Big Endian script hash and public address formats of the input, assuming it is a valid public key. This conversion is something I find myself doing semi-frequently, and I notice it's the only one that I have to go to https://neo.org/converter/ to perform rather than using NeoGo.

**Comment by roman-khimov** [comment]
Yeah, I had this thought also recently, there are cases where you see the key and want to know what the address is.
