### ISSUE TITLE
I use the code to generate a address and privatekey the privKey is start with N, how can I geneerate the address start with A . here is my code 

### ISSUE THREAD

**Issue by malingzhao** [nspcc-dev/neo-go#2129]

**Comment by malingzhao** [comment]
key, err := keys.NewSecp256k1PrivateKey()
	if err != nil {
		fmt.Println(err)
	}
	address := key.Address()
	fmt.Println("address---->", address)
	privKey := key.WIF()
	fmt.Println("privKey---->", privKey)

**Comment by roman-khimov** [comment]
If you need Neo Legacy address, just use master-2.x branch.

**Comment by malingzhao** [comment]
Thank you very much

**Comment by roman-khimov** [comment]
Oh, BTW, you're using `NewSecp256k1PrivateKey`, which is a Koblitz curve key that may be useful in some cases, but normally you need 256r1 that Neo uses.

**Comment by malingzhao** [comment]
I try

**Comment by malingzhao** [comment]
what is the tag of master-2.x

**Comment by roman-khimov** [comment]
https://github.com/nspcc-dev/neo-go/tree/master-2.x
https://github.com/nspcc-dev/neo-go/releases/tag/v0.78.4

**Comment by roman-khimov** [comment]
I think the issue is solved.
