### ISSUE TITLE
what is the testnet facuet of the neo , I can not get the test coin . https://neowish.ngd.network/neo3/#/ I use this net but in the testnet explorer can not get the test coin

### ISSUE THREAD

**Issue by malingzhao** [nspcc-dev/neo-go#2131]

**Comment by roman-khimov** [comment]
1) We're not responsible for faucet.
2) Please use shorter and more informative headers.
3) [Neo Discord](https://discord.gg/rvZFQ5382k) channels usually can handle these questions faster.
4) It'll probably be fixed soon.
