### ISSUE TITLE
Export neo-cli data to neo-go

### ISSUE THREAD

**Issue by versionCollector** [nspcc-dev/neo-go#2138]
Hi, i want to try out your project for neo network. Can i somehow import databse from neo.org project to yours? I have tried giving neo-cli database path, but faced this problem
`could not initialize blockchain: storage version mismatch betweeen 0.0.9 and 2.12.2.0`
I'm using release  v0.78.2 and neo-cli v 2.12.2.0

**Comment by roman-khimov** [comment]
DBs are not compatible, you need to resynchronize (and it'd be better to do it from chain dump). Also, please use the latest 0.78.4, it has important fixes and updates (especially wrt expected GAS generation cut off).

**Comment by versionCollector** [comment]
Thank you for the fast response. I've started importing db dump with height 7200000 long time ago but it's still processing it. 
![image](https://user-images.githubusercontent.com/85240173/130244975-208c9147-3632-4fd3-b239-c9a9bcec9937.png)
![image](https://user-images.githubusercontent.com/85240173/130244569-5a5ace96-22dd-4c76-b351-f9f91bf07dcb.png)
What could be the problem, can I speed it up?

**Comment by roman-khimov** [comment]
It really takes time especially in 6M+ range where the chain is already quite big and there is quite substantial number of transactions coming with every block (this starts somewhere around Flamingo start and Flamingo transactions tend to be heavy by themselves). Better hardware always helps, the other thing we usually do when processing these dumps is turning block signature verification off (`VerifyBlocks` setting), but it may not fit your purpose (if you absolutely need to be sure that the chain is correct) and it won't help much at 7M+ (verification is a bottleneck mostly at the beginning of the chain).

**Comment by versionCollector** [comment]
Thanks a bunch!
