### ISSUE TITLE
Move verification of transaction to DEV

### ISSUE THREAD

**Issue by dauTT** [nspcc-dev/neo-go#214]
The verification of transaction is already implemented (90% complete) in the master branch. 
We need to move it to DEV and fill the gaps once the VM is mature enough .

TODO: 
1) migrate the code to DEV: https://github.com/CityOfZion/neo-go/blob/master/pkg/core/blockchain.go#L673
2) fill the gaps: 
(https://github.com/CityOfZion/neo-go/blob/master/pkg/core/blockchain.go#L886)

**Comment by decentralisedkev** [comment]
Unfortunately, some of the logic in the `dev` branch deviates from the one implemented in the master branch.

In particular;

- The chain does not know about the mempool, and so VerifyTx returns true if a transaction can be put into the nextBlock. The mempool will keep a list of it's own transactions; it will check for duplicates and then call the chains VerifyTx(). 

- VerifyInput is the same as it just checks whether we have any repeated inputs in the transaction.

- IsDoubleSpend will take the inputs prevHash and index, then search the utxo table for it, if found then we have a double spend. So this would be a table look-up.

- OutputsVerification, for this we need to go back into chaindb and store the state of the asset.

- verifyResults IMHO is doing too much and we should first find out what it's meant to be doing then re-implement it in a Golang optimised way.

- NetworkFee calculations and Transaction priority will be in the mempool and not the blockchain.

We can use the implementation on master to double check our results and as a reference though.

1) I think to start this off, we can first do a PR which checks for duplicate inputs.

2) Then in chaindb in a separate PR, we can save assetstate information

3) Then add verifyOutputs and double spend check.

By this point, we will be able to verify whether a transaction has been double spent and whether the asset being used is valid.

If I have time I will add the mempool functionality. The main thing, is that the chain only verifies and saves blocks. Sorry for not being clear about this.

**Comment by roman-khimov** [comment]
No longer relevant, see #283.
