### ISSUE TITLE
Add max connections per host option to the RPC client

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neo-go#2149]
When NeoFS Node processes large amount of requests that use Neo RPC node, HTTP transport of neo-go client creates multiple underlying connections. If they are not limited, then we may see `dial tcp 192.168.130.90:30333: connect: cannot assign requested address"` errors as in https://github.com/nspcc-dev/neofs-node/issues/676

It will be nice to have `MaxConnsPerHost` option in neo-go RPC client.
```go
	// pkg/rpc/client/client.go:85
	httpClient := &http.Client{
		Transport: &http.Transport{
			DialContext: (&net.Dialer{
				Timeout: opts.DialTimeout,
			}).DialContext,
			MaxConnsPerHost: opts.MaxConnsPerHost,
		},
		Timeout: opts.RequestTimeout,
	}
```

From the NeoFS side, we will cache some neo-go client response and can also provide some sort of rate limit.

**Comment by roman-khimov** [comment]
Actually, I've not expected it to ever exceed one connection just based on the fact that the API is synchronous. But as we're reusing http.Client and it works this way, we need to expose `MaxConnsPerHost` option.

**Comment by roman-khimov** [comment]
And default it to 1 or 2? I really can't imagine why we need more than that in our Client, it's not supposed to be used from multiple threads and it's synchronous, so we send one request at a time and receive one reply, then get to the next request.

**Comment by alexvanin** [comment]
> And default it to 1 or 2?

I wonder if it is going to be noticeable in benchmarks. Maybe the best way is to mimic http.Client and leave 0 by default?
