### ISSUE TITLE
network: allow to handle GetMPTData command if `KeepOnlyLatestState` enabled

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#2152]
Depends on #2095.

We need to adjust server's `handleGetMPTDataCmd` behaviour wrt `KeepOnlyLatestState` setting. We also need a test for state exchange between two nodes with `KeepOnlyLatestState` on.

**Comment by roman-khimov** [comment]
At the moment `KeepOnlyLatestState` is ignored when `RemoveUntraceable` is active which kinda solves the problem (we have all the appropriate data). And and it's a fair behaviour to return whatever MPT data we have (if we don't, this command will error out anyway). So we can remove the check, but there are some other things that can be improved here.
