### ISSUE TITLE
Open read-only wallet 

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neo-go#2182]
If I understand correctly, at the moment we cannot open the wallet for read-only ([`wallet.NewWalletFromFile`](https://github.com/nspcc-dev/neo-go/blob/master/pkg/wallet/wallet.go#L58) opens file in `RW` mode). It would be nice to have such opportunity.

**Comment by roman-khimov** [comment]
I think we can open it RO by default and then close the file (we don't really need this handle). If `Save()` is called afterwards, that's where we'll open it RW and do what needs to be done.
