### ISSUE TITLE
Interop to get contract hash from contract ID

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neo-go#2189]
With the adoption of NNS contract in NeoFS, we want to register container nice name in NNS contract directly from container contract. To do so, container contract can be provided with the NNS address at deploy stage. However side chain **always** stores NNS contract with ID 1. Can we determine contract hash by its ID in NeoVM runtime?

/cc @roman-khimov @fyrchik @AnnaShaleva

**Comment by roman-khimov** [comment]
Nope. ContractManagement can of course be extended to accept IDs, but that's not that easy for C# node to do (it doesn't track ID-hash mappings). And I think providing it during deployment is a viable solution, you're setting it up anyway and it's just another parameter there.

**Comment by alexvanin** [comment]
>  but that's not that easy for C# node to do (it doesn't track ID-hash mappings)

I guess it is the reason why neo-go RPC does support ID argument in `getcontractstate`. Thanks.
