### ISSUE TITLE
Transaction hash in notification event

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neo-go#2190]
Notification events are quite convenient to monitor contract's invocations and produce responding actions. 

https://github.com/nspcc-dev/neo-go/blob/b989504d746deef4fd72a92221e22f15e658374e/pkg/core/state/notification_event.go#L17-L21

These responding actions are mostly notary messages: e.g. changes in `NeoFSAlphabet` role from the main chain trigger new notary message with main tx signed by side chain committee. To create correct notary message, Alphabet nodes need to synchronize `nonce` and `VUB` values. 

While Alphabet nodes are triggered by the same event, they create the same notary message with the same `nonce` and `VUB`. However, if the notification appears twice, notary message will fail with `<hash> is already on chain` error.

To solve that issue we are doing two things:
- produce notification that includes transaction hash, therefore it has a unique set of `Items`
- use current block height with some rounding as the source for `VUB`.

Those are not optimal solutions, because some events are produced by the native contracts (update of the role management contract), and current block height rounding does not exclude a chance of `VUB` divergence between Alphabet nodes.

The optimal solution: to have an identifier for events, e.g. transaction hash. With transaction hash, all Alphabet nodes will be able to create the same but unique `nonce`. As for `VUB`, Alphabet nodes will get block height where transaction appeared and use it as a base for `VUB`.

**Comment by roman-khimov** [comment]
Reminds me of #1081, this actually was requested previously. We'll need to create a new structure for this, but it seems to be useful, so I think we can do this.
