### ISSUE TITLE
Make notary balance error more descriptive

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neo-go#2197]
`Block or transaction validation failed. (-504) - invalid transaction due to conflicts with the memory pool - %!s(<nil>)` error message appears [when](https://github.com/nspcc-dev/neo-go/blob/v0.97.3-pre/pkg/core/mempool/mem_pool.go#L25) "Sender doesn't have enough GAS to pay for all transactions in the pool". But it is not clear that the problem is related to balances when reading such error text. Also `%!s(<nil>)` wrapping is confusing.

**Comment by roman-khimov** [comment]
That's interesting, it dates back to Legacy code where conflict meant real UTXO conflict, so it was quite relevant. Now the only possible "conflict" is insufficient balance actually and "Conflicts" attribute uses `ErrConflictsAttribute` (where "conflict" again means something). Maybe we can just change this error message.
