### ISSUE TITLE
Generic contract testing infrastructure

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#2222]
We have a lot of tests in core package that initialize chain, do some deployments/invocations and check for result. This is used heavily for non-native contracts, but this also is what non-native ones need for automated testing. So we need to move some generic infrastructure code into specialized package and use it both internall and externally. Partially that's what is done already by `neofs-contracts/tests`, but this needs to be a part of NeoGo.

Refs. #1966.

**Comment by fyrchik** [comment]
We can take https://github.com/nspcc-dev/neofs-contract/tree/master/tests as a basis.
