### ISSUE TITLE
compiler: allow to compile functions with no return value and `defer` statement

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#2253]
**Problem**

Consider the following smart-contract:
```
package main

func Main() {
	i := 0
	defer func() {
		if r := recover(); r != nil {
			i++
		}
	}()
}
```
Compilation fails with the following error:
```
error while trying to compile smart contract file: invalid label target: -1 at 8
```

However, if `Main` has a return value, then the contract will be compiled:
```
package main

func Main() int {
	i := 0
	defer func() {
		if r := recover(); r != nil {
			i++
		}
	}()
	return i
}
```

**Question**
Is the first smart-contract supposed to be compiled? If so, then I suppose that the problem is somewhere around this line: https://github.com/nspcc-dev/neo-go/blob/0a7f8afcea5dd9ae4359cc505b122e1a44b06c44/pkg/compiler/codegen.go#L1337

**Comment by roman-khimov** [comment]
Well, there is nothing wrong in the code itself (the function might have side-effects without return value), so it should be compiled successfully.

**Comment by roman-khimov** [comment]
Can be simplified to
```
package main

func Main() {
	i := 0
	defer func() {
		i++
	}()
}
```

**Comment by roman-khimov** [comment]
But closures are not really supported, so you can't access `i` anyway.
