### ISSUE TITLE
Use tokens for known external contract calls

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#2257]
`CALLT` is a bit shorter than `Contract.Call` syscall and allows to omit some parameters, so if any function is called multiple times it should be easier to do that with `CALLT`. I'm not sure about single call case though, tokens still make NEF larger.

**Comment by fyrchik** [comment]
Token contains hash and method (also present in the byte-code) plus 4 bytes (2 for param count + call flags + has return).
Currently we use `contract.Call(interop.Hash160(constant hash) ...)` in many places which emits constant at every callsite.

`CALLT` has a 2 byte argument (2 bytes less than SYSCALL) and unpacked arguments on stack (2 bytes less than `PUSH*` + `PACK`).
Pushing hash and method also incurs 2-byte overhead (opcode + size vs. only size for `token.EncodeBinary`). So I think `CALLT` might be better even in single-call scenario (for constant hash + constant argument + constant flags where `CALLT` is applicable).

It is also interesting which version performs better in terms of speed.

**Comment by roman-khimov** [comment]
It looks like C# is only using CALLT for native contracts, because we need to specify `HasReturn` and we don't know it for random contracts (`ParamCount` can be deduced).

**Comment by roman-khimov** [comment]
Which reminds me of #2221.
