### ISSUE TITLE
Add a note about go module initialization for contract compilation

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neo-go#2274]
[Quick start](https://github.com/nspcc-dev/neo-go/blob/master/docs/compiler.md#quick-start) guide mentions Go requirement. However it does not mention `go mod init` and `go mod tidy` commands, which may be not quite obvious for people unfamiliar with Go.

**Comment by fyrchik** [comment]
I think we may change our `contract init` in #2086 , as it also becomes necessary in tests.
