### ISSUE TITLE
logo looks bad in dark mode

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neo-go#2289]
Steps to reproduce: set "Night theme" in https://github.com/settings/appearance

![image](https://user-images.githubusercontent.com/14617699/144407909-0ae96bf8-f230-4b04-9053-5b1276c2307c.png)
![image](https://user-images.githubusercontent.com/14617699/144408403-ce16d775-e7fd-4947-a338-30612ccdaf00.png)

Please don't close this issue until all repositories have been updated.

**Comment by roman-khimov** [comment]
@mike-petrov, can you take a look at this one? AFAIR it's fixed for NeoFS repositories now, but not here.

**Comment by mike-petrov** [comment]
Here is a description of possible solutions: https://github.com/nspcc-dev/neofs-node/issues/614

**Comment by roman-khimov** [comment]
I'm OK with two PNGs for this.

**Comment by mike-petrov** [comment]
What do you think of a 1 or 2 pixel border in white?

**Comment by roman-khimov** [comment]
Argh. That'd be bad. But maybe we can steal the "neo" part in proper color from SVG and then rasterize it properly?

**Comment by roman-khimov** [comment]
Fixed in #2850.
