### ISSUE TITLE
Public methods must have named parameters

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#2296]
```
func OnNEP17Payment(_ interop.Hash160, _ int, _ interface{})
```
will compile fine, but fail deployment with
```
contract invocation failed      {"tx": "ca3e11c3d297eae6ce50b4b50255616aca47d73cedc4546d1ef465f805d26cd2", "block": 36, "error": "at instruction 8 (SYSCALL): invalid manifest: duplicate parameter name"}
```
which is kinda expected and creating some fake names seems to be counterproductive. So maybe we can just check that exported functions always have named parameters?

**Comment by fyrchik** [comment]
As a user I would expect `arg0`, `arg1` etc. to be substituted for me. We can also validate manifest after emitting (funny enough we have lots of complicated checks but miss simple `IsValid`).

**Comment by roman-khimov** [comment]
Substitutes are dangerous, and it's a public-facing function with parameter name being a part of the manifest, so disallowing `_` still makes sense.
