### ISSUE TITLE
Improve test framework usability

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neo-go#2297]
It would be nice to add some public functionality into the test framework:
+ [NewSingle](https://github.com/nspcc-dev/neo-go/blob/v0.98.0/pkg/neotest/chain/chain.go#L114) and [NewMulti](https://github.com/nspcc-dev/neo-go/blob/v0.98.0/pkg/neotest/chain/chain.go#L135) returns committee multi-signer and it is impossible to invoke something that is signed by one of the members of the committee (not with its multi-signature). So now testing such functionality requires copy-pasting one of the [WIFs](https://github.com/nspcc-dev/neo-go/blob/v0.98.0/pkg/neotest/chain/chain.go#L20-L33) and constructing its signer.
+ `Signer` -> `PublicKey` conversion functionality. Now if a tester wants to get a public key, he has to use something like
```
node := contractInvoker.NewAccount(t)
nodePub, ok := vm.ParseSignatureContract(node.Script())
require.True(t, ok)
```

**Comment by roman-khimov** [comment]
> it is impossible to invoke something that is signed by one of the members of the committee (not with its multi-signature)

But what is the use case for this?

**Comment by carpawell** [comment]
> But what is the use case for this?

Test NeoFS alphabet contract. It (each of them) must be invoked by one of the alphabet nodes, not by alphabet multi-account.

**Comment by roman-khimov** [comment]
OK, that explains why you also need proper `Signer` for each of these accounts.
