### ISSUE TITLE
NEO Legacy: TX not being relayed (different sorting behavior hashes / witness from c# / py?)

### ISSUE THREAD

**Issue by fabwa** [nspcc-dev/neo-go#2301]
https://neoscan.io/transaction/F9C68613F41CA85DDB01EC757153C0D86018D2324F6FF85A4AFC708BB598B722 when sent to neo-go it says is an invalid transaction, but is ok for C# and Python

The issue seems that neo-go sorts both the hashes for a tx and the witnesses and tries to compare them  (https://github.com/nspcc-dev/neo-go/blob/master-2.x/pkg/core/blockchain.go#L2512)

C# and neo-python only sort the hashes, and then it is up to the transaction assembler to order the witnesses correctly.

**Comment by roman-khimov** [comment]
Whatever that is, I doubt it's because of sorting. We've got two lists, hashes and witnesses, witnesses _must_ have the same hashes as ones from hash list, so if we're to sort two lists they must have the same order.

**Comment by roman-khimov** [comment]
```
      "scripts" : [
         {
            "invocation" : "40331fe1822bad898105f3fdd52b0f5068d84c4c4ce0f459f8107574206c87f0265d4d24a8e6b33c167ebdf4122127d21193db2b198a390826677fab3107c9f690",
            "verification" : "2103f3be0455bd6ed7031c991305759b1e386b80229a1f3045f58ae9ae64958f92f9ac"
         },
         {
            "invocation" : "0000",
            "verification" : ""
         }
      ],
```
Zero-length verification?

**Comment by fabwa** [comment]
When this is the case it means you're 'sending from the smart contract' and the node takes the public key of the contract that is being invoked and places it there

**Comment by roman-khimov** [comment]
Yeah, we have this logic, but you're correct in that sorting might intervene with it (sorting will use the hash of this zero-length verification script and it's not the one really needed).
