### ISSUE TITLE
Way to ignore return result check of invoked method in contract test framework

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neo-go#2312]
I had a contract with the method, that updates contract storage and returns some kind of ID. In the test, I had to call this method multiple times. [ContractInvoker.Invoke](https://github.com/nspcc-dev/neo-go/blob/501ca0dedba41bb23de24987e16f1890b47fc914/pkg/neotest/client.go#L64) method requires specific result, but in my case `HALT` state was enough to proceed. If I understand correctly, the only way to invoke method without result checking is to define such function in test code:

```go
func invokeNoReturnValueCheck(t *testing.T, c *neotest.ContractInvoker, method string, args ...interface{}) util.Uint256 {
	tx := c.PrepareInvoke(t, method, args...)
	c.AddNewBlock(t, tx)
	c.CheckHalt(t, tx.Hash())

	return tx.Hash()
}
```

It would be nice to see an optional result check for contract method invocations in `neotest` library.

/cc @fyrchik

**Comment by fyrchik** [comment]
This is fixed in #2299 (https://github.com/nspcc-dev/neo-go/pull/2299/commits/e606d3c3bf2c0721da965ff6f79efd9fe58b80fb) .
