### ISSUE TITLE
Pretty print wallet JSON file on creation

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neo-go#2317]
It would be nice to have a pretty-printed JSON file with the newly created wallet for better human readability.

**Comment by roman-khimov** [comment]
You want to have it pretty-printed in a file? But what's the purpose? It's JSON and pretty-printing will just make it bigger. We also have `wallet dump` command for pretty-printed version.

**Comment by realloc** [comment]
Wallets created for various NeoFS components using `neo-go` tool are then used by humans, who read them, copy addresses, etc. Pretty-printed wallet file would improve their experience a little.

**Comment by AnnaShaleva** [comment]
I was thinking about adding a separate `--pretty` flag to all wallet commands where printing to a file is used. Then the user may decide whether he needs indentations or not.

**Comment by roman-khimov** [comment]
Flag doesn't seem to be appropriate, people shouldn't care about wallet internals much. Frankly, I'd rather not change anything at all, JSON is JSON and should be interacted with either via neo-go CLI or JSON tools. But, if there really is a demand, I can live with pretty-printed JSON as well.

Let's vote: :+1: for changing to pretty-printed JSON and :-1: for leaving it as is.

**Comment by anatoly-bogatyrev** [comment]
It also seems to me that an additional flag is not needed. But the presence of a pretty-printed JSON, if it does not affect anything else, is better than its absence.

**Comment by fyrchik** [comment]
We already have `wallet dump`. Also `jq <wallet.json` looks much prettier anyway, so I vote for the :-1: option.

**Comment by 532910** [comment]
I use jq for a nice json, as it colorizes output, so
I vote for the 🌈

**Comment by AnnaShaleva** [comment]
I also vote for the 👎 because it's better to use the existing CLI command for pretty printing.

**Comment by realloc** [comment]
@AnnaShaleva @532910 @fyrchik Not all of our users are so advanced to have `jq` and other tools at hand. Not all of them are developers, they don't use terminal at a daily basis and can't build complex command pipelines.

The typical scenario is to create a wallet and then open it to see the address and other stuff. That's quite difficult for the regular user to see the JSON that's formatted for machines, not for humans, and parse it with eyes. Machines don't care about few additional spaces, they would not suffer from this. Also, making humans to use additional `dump` action for already created file is not very friendly, and how would they would even know this additional step exists?

**Comment by AnnaShaleva** [comment]
> The typical scenario is to create a wallet

Then probably the user makes it with `neo-go wallet create` command (or with neo-cli), so at least he's able to run binary and, likely, he's able to see the help on `wallet` set of commands. All commands including `dump` are well-documented, moreover, `wallet dump` allows to decrypt encrypted keys.

Just a note: C# node also doesn't use indentations for `create wallet` command, so the resulting wallet is not prettyfied.

**Comment by realloc** [comment]
> All commands including dump are well-documented

Yes, but that's additional steps and information to understand. The wallet creation action is usually a small step, for example, in NeoFS node or other dApp setup, which is already quite complex. Making the user to learn the full functionality of `neo-go` cli at the very begging may be too much. Just making the newly created wallet pretty printed would greatly improve human acceptance of the process.

> Just a note: C# node also doesn't use indentations for create wallet command, so the resulting wallet is not prettyfied.

There is a huge room for improvement in other software, but that should not be an excuse not to improve our own project.

**Comment by fyrchik** [comment]
> Just making the newly created wallet pretty printed would greatly improve human acceptance of the process.

We already pretty-print wallet in `wallet init` (creates new wallet). I think we can do the same for `wallet create` (adds account to the existing wallet).

**Comment by roman-khimov** [comment]
> Not all of our users are so advanced
> Not all of them are developers

Well, for them wallet is just a wallet, completely opaque thing where monsters live (it might've been a binary for them with no practical difference). There are neo-go commands that deal with it and they're sufficient, people don't should look inside of it at all.

**Comment by realloc** [comment]
> Well, for them wallet is just a wallet, completely opaque thing where monsters live

Maybe, but they look there in reality and there is no reason why it should not be human-readable. This change is trivial and avoids possible user's confusion. Machines do not care if the file is formatted or not, but humans do. Let us make humans happy!

**Comment by 532910** [comment]
As it turned out in the conversation this is about the wallet file itself, not an output, as I thought before.
And I'm for the pretty printed file, it'd allow to cat it as is.

**Comment by roman-khimov** [comment]
3:3, looks to me it's better to change nothing here, at least for now.

**Comment by roman-khimov** [comment]
#2549 makes it pretty much irrelevant. Reopening criteria: 50% more votes in favor under https://github.com/nspcc-dev/neo-go/issues/2317#issuecomment-1009120915.
