### ISSUE TITLE
Seek precisely for voter GAS calculations

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#2322]
See https://github.com/nspcc-dev/neo-go/pull/2316#discussion_r782486890, I still believe it'll be beneficial, but the key is to get exactly one value, not iterate over the whole data set. It's rather simple to do, we don't need to use asynchronous interface, it's just that the function passed to `Seek` needs to return `continue` boolean value. So when needed we'll just pick one value and return `false`. Extended tests (with varying claim distance) will probably show something.

**Comment by AnnaShaleva** [comment]
A part of implementation was presented in the https://github.com/nspcc-dev/neo-go/pull/2316/commits/05b5fdc0f4e181777308b87f49433f3cab10be5d, but it needs some more care.
