### ISSUE TITLE
Allow to use big numbers in RPC queries

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#2350]
There are 2 issues which prevent us from using big integers when working via RPC:
1. Smartcontract `Integer` parameter expects `int64` as a value. https://github.com/nspcc-dev/neo-go/blob/master/pkg/smartcontract/parameter.go#L67 .
2. Request parameter is converted to `int` (not even `int64`) when building invocation script https://github.com/nspcc-dev/neo-go/blob/01d15ff473f9984023e9c1e04be107981acec80e/pkg/rpc/request/txBuilder.go#L65-66 .

**Comment by roman-khimov** [comment]
The second one is rather trivial, but https://github.com/nspcc-dev/neofs-node/issues/122#issuecomment-716565100
