### ISSUE TITLE
Allow `WSClient` RPC calling from multiple gorutines

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neo-go#2357]
Now it may [mix](https://github.com/nspcc-dev/neo-go/blob/master/pkg/rpc/client/wsclient.go#L224) responses from an RPC node and the client's caller needs to handle it (make calls consequentially). It would be nice to remove such a restriction.

Problems appeared when I tried to change `Client` for `WSClient` in the same code base. `WSClient` embeds `Client` and, therefore, it looks like it could completely replace it. But not in all cases. Also, there are no words about multi-thread usage in client's description but there is `It's supposed to be faster than Client` state that made me think that it is "same but cooler".

**Comment by roman-khimov** [comment]
Regular `Client` is not guaranteed to work correctly in multithreaded scenarios also, so it's time to fix both.
