### ISSUE TITLE
VM: Add Test coverage for opcodes with a limited results

### ISSUE THREAD

**Issue by decentralisedkev** [nspcc-dev/neo-go#236]
For example; We can test all results of the NOT opcode, since it is either true or false.

Another is NZ.

It would be better to have them included in one function. I think we will need some boiler plate test code, to allow us to do this cleanly

**Comment by volekerb** [comment]
I guess here's an issue related to tests in vm_ops_maths_test.go
I believe that suggested approach could be applied to other tests as well

**Comment by roman-khimov** [comment]
New tests are always welcome, but I think we have enough infrastructure for them. If not, I'd like to see more specific bugs. Closing this one (see #283 also).
