### ISSUE TITLE
VM: remove underscore in vm file names

### ISSUE THREAD

**Issue by decentralisedkev** [nspcc-dev/neo-go#238]
For example: `vm_ops_bitwise` should be `vmopsbitwise`

**Comment by roman-khimov** [comment]
I don't think it improves anything, quite contrary --- it makes names less readable. Sure, underscores have some special meanings in Go in certain cases, but it doesn't prevent their normal use in almost every other popular repository of Go source code:
https://github.com/kubernetes/kubernetes/tree/900d652a9ac11e53293950b3d191295c21430215/plugin/pkg/admission/gc
https://github.com/moby/moby/tree/f6226a2a56c38b790b59393ff4ce7f88f790c811/integration-cli
https://github.com/etcd-io/etcd/tree/34bd797e6754911ee540e8c87f708f88ffe89f37/functional/runner
https://github.com/golang/go/tree/fdceb2a11bb767ddaa334cb39315ae6982b676aa/src/compress/bzip2

WONTFIX for me.
