### ISSUE TITLE
Prevent redirecting to local hosts in Oracle

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#2381]
See neo-project/neo#2662 and neo-project/neo-modules#692. Turns out, [net/http Client](https://pkg.go.dev/net/http#Client) has `CheckRedirect` exactly for this purpose (but be careful to keep the limit on redirections number).

**Comment by roman-khimov** [comment]
Also neo-project/neo-modules#694.

**Comment by vang1ong7ang** [comment]
i suggest to customize `http.Transport`. i think it's the final solution kkkkkk

**Comment by roman-khimov** [comment]
> inside http.Client.Do, there is a dns lookup

It's not always the case due to connection caching, but I was thinking more about redirects (the original problem stated) and what can happen during the call processing.

> this lookup result may be different with the one in URIValidator

That's true, resolving something in `CheckRedirect` or `URIValidator` in general doesn't mean that `http.Client` will use the same IP, so we can just say that the check was implemented incorrectly right from the beginning.

The way `Client/RoundTripper/Transport/Dial` things are structured it should be trivial to fix this though, we're TCP-level at `Transport.DialContext()`, irrespective of when and how DNS was resolved, checking and dialing there is easy.
