### ISSUE TITLE
Accept wallet password from stdin

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neo-go#2387]
It may be useful to support entering wallet passwords in a non-interactive mode from `stdin` to simplify scripting.

Something like this **expect**ed:
```
$ echo 'Secret` | neo-go wallet nep17 transfer ...
```

**Comment by roman-khimov** [comment]
Our current behavior is a feature, something like `sshpass` should work for this purpose.

**Comment by realloc** [comment]
The general-purpose tools, like expect, indeed helps to work around the issue sacrificing the usability, but that's not the way to handle it. One more tool like `neo-gopass` will be redundant.

Having an option for a secret to be accepted from `stdin` is a common practice (ansible-vault, keepass, etc) expected by an operations person. Let's make `neo-go` more ops friendly.

**Comment by roman-khimov** [comment]
You'll be able to use standard `sshpass` after #2480.
