### ISSUE TITLE
Upgrade go version of CircleCI linter job runner

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#2395]
Need to update `lint`'s job executor for CircleCI workflow after https://github.com/golangci/golangci-lint/issues/2649 is resolved.

**Comment by AnnaShaleva** [comment]
Ref. #2369.

**Comment by roman-khimov** [comment]
No CircleCI (#2873), no problem? Do we need to update GH linters?

**Comment by AnnaShaleva** [comment]
GH jobs are OK, we may close this issue.
