### ISSUE TITLE
Add logging to WSClient

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#2421]
Currently our RPC websocket client breakes the connection every time something unexpected is occurred. The problem is that we don't have a clue on what was wrong and how to recognise\debug\fix the error. It's the third time I have to make a patch with `fmt.Printf`s to log WS errors, so we definitely need the ability to provide logger to WSClient constructor and to log all these disconnection errors (e.g. errors like [this one](https://github.com/nspcc-dev/neo-go/blob/20c0e2f2e2ff059b194c658e874f22ad488838da/pkg/rpc/client/wsclient.go#L175)).

The users will appreciate (@carpawell, @alexvanin).

**Comment by roman-khimov** [comment]
Logging is not a solution. `Error()` method is.
