### ISSUE TITLE
Make sure all XXX comments are addressed

### ISSUE THREAD

**Issue by decentralisedkev** [nspcc-dev/neo-go#244]

**Comment by volekerb** [comment]
I believe after merging branches we will go through the comments in the code and list them here

**Comment by roman-khimov** [comment]
Or better yet submit separate issues for every XXX.

And actually `master` doesn't have any XXX, though it has some TODOs.

**Comment by volekerb** [comment]
true, master doesn't have, but  thought XXX comments are relevant for master. Looks like not that much.
Vote for submitting each XXX as a separate issue

**Comment by roman-khimov** [comment]
Now we have all TODOs either fixed (#371) or having a specific opened issue (#363, #364, #365, #366, #367, #368, #369, #370, #371), except a pair of very minor ones that already have intersections with other tasks. Thus, this issue is no longer relevant and can be closed.
