### ISSUE TITLE
node stop sync block at 1528989

### ISSUE THREAD

**Issue by laizy** [nspcc-dev/neo-go#2483]
node version : `/NEO-GO:0.98.3-pre-162-g19eb9761/`
error log:
```
2022-05-12T21:44:21.952+0800    WARN    blockQueue: failed adding block into the blockchain{"error": "onPersist failed: VM has failed: at instruction 0 (SYSCALL): insufficient funds", "blockHeight": 1528989, "nextIndex": 1528990}
```

**Comment by laizy** [comment]
thanks.

**Comment by laizy** [comment]
I upgraded to this version, but find out the transaction created by my client code will always be rejected with error: `Block or transaction validation failed., detail: witness #0: signature check failed: invalid signature`. 😢 
It turns out the response format of `getversion` rpc has changed, and my code failed to get the network magic number. the previous version returns `initialgasdistribution` as number, but this version returns it as string.

**Comment by roman-khimov** [comment]
0.98.4 doesn't change `getversion`, you're probably using some different version.

**Comment by laizy** [comment]
ok, maybe my previous build use master branch and includes this commit: https://github.com/nspcc-dev/neo-go/pull/2435, but reverted soon by this pr: https://github.com/nspcc-dev/neo-go/pull/2448.
