### ISSUE TITLE
wallet init without password

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neo-go#2487]
please add support to generate wallets with empty password, without asking it
```
neo-go wallet init -a -w wallet.json
```

**Comment by roman-khimov** [comment]
Why do you want that?

**Comment by 532910** [comment]
to generate it from script for example

**Comment by roman-khimov** [comment]
How about supporting a wallet config from #2536? Any kind of password there without additional questions (rewriting any existing wallet), non-empty passwords.
