### ISSUE TITLE
Counting circular references can be a problem

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#2500]
Here's a test to reproduce the issue
```go
func TestCircularRefs(t *testing.T) {
	h := "560110c34a4acf4a10c36058cf5810c34ecf10c34ecf58cf0b604a11d2"
	prog, err := hex.DecodeString(h)
	require.NoError(t, err)
	vm := load(prog)
	vm.Run()
	assert.Equal(t, 3, vm.refs)
}
```

This script comes from here https://github.com/neo-project/neo-vm/blob/master/tests/neo-vm.Tests/UtReferenceCounter.cs#L14-L41. The format of the comments in that file is `{<evaluation stack contents>} | {<static field slot contents>}: <engine reference count>`. fwiw; the right side of the evaluation stack is the top
So this
```
//{A[],A[]}|{null}:3
```
means 2 array items in the evaluation stack, 1 null stack item in the staticfields slot, total ref count of 3.

----------

The last opcode is `REMOVE` which removes array `B` from this setup
```
{A[A,B[C[D[B]]]],A[A,B],1}|{null}:9
```
The problem is with B containing itself, therefore the `rc` of `B` will always remain > 0 and it won't decrease the count for the internal elements that are discarded.

----------

I don't think this scenario is very realistic on chain, but you might want to solve it regardless of that. The implication I see is that the max stack items limit might be reached sooner than the C# VM.

_Originally posted by @ixje in https://github.com/nspcc-dev/neo-go/issues/2498#issuecomment-1128469429_

**Comment by AnnaShaleva** [comment]
Currently, our reference counter scheme is cheating and does not perform truly reference counting. We take into account only the number of added/removed entries instead of going deeper inside each stackitem and comparing new object references with ones that were already presented and counted. Current refcounter implementation causes the described bug with circular references. We need to refactor our refcounter so that it's able to memorize refcounted entries and perform fair refcounting.

After that we need to port https://github.com/neo-project/neo-vm/pull/486, so that only compound types and Buffer are taken into account by refcounter.

**Comment by fyrchik** [comment]
@AnnaShaleva Why do you think it is cheating? Our primary usecase is executing VM scripts, so if an array is added on stack you can be sure that is either was a part of some other collection (already refcounted), or created from the items on stack (elements already refcounted).
The bug with circular references is inherent in all reference counter implementations, basically, you can't tell whether the object is reachable from "root" based on a single numeric value.

**Comment by roman-khimov** [comment]
Frankly, I don't want to open this can of worms. I'd rather make C# refcounter as simple (and as performant) as the one we have. Currently it's doing too much work at every instruction, using complex GC schemes invented for completely different scenarios (where the cost of GC is amortized for a hell lot of instructions executed in some period of time). The VM we have must ensure that there is some proper amount of items at every step, it can't run GC every N instructions, so the approach it uses must be performant enough to be done at every step and any scheme that can solve circular references just costs too much IMO. And it's not that we desperately need this feature, transaction runs are relatively short-lived and in 99,99% scenarios they never have circular references, so to me it's just a waste of time.
