### ISSUE TITLE
RPC invokefunction missing exception key

### ISSUE THREAD

**Issue by ixje** [nspcc-dev/neo-go#2503]
Calling `invokefunction` on the the C# nodes gives a response which includes an `exception` key, the go nodes don't seem to have this
```
curl --location --request POST 'http://seed2t4.neo.org:20332' \
--header 'Content-Type: text/plain' \
--data-raw '{ "jsonrpc":"2.0",
  "method":"invokefunction",
  "params":["0x07a49861d44c0f00495c30a2884f47f08e0f32ef", "symbol"],"id":1}'

....

{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "script": "wh8MBnN5bWJvbAwU7zIPjvBHT4iiMFxJAA9M1GGYpAdBYn1bUg==",
        "state": "HALT",
        "gasconsumed": "209538",
        "exception": null,
        "stack": [
            {
                "type": "ByteString",
                "value": "U0VDT05E"
            }
        ]
    }
}

```

```
curl --location --request POST 'https://rpc01.testnet.n3.nspcc.ru:21331/' \
--header 'Content-Type: text/plain' \
--data-raw '{ "jsonrpc":"2.0",
  "method":"invokefunction",
  "params":["0x07a49861d44c0f00495c30a2884f47f08e0f32ef", "symbol"],"id":1}'

...

{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "state": "HALT",
        "gasconsumed": "209538",
        "script": "wh8MBnN5bWJvbAwU7zIPjvBHT4iiMFxJAA9M1GGYpAdBYn1bUg==",
        "stack": [
            {
                "type": "ByteString",
                "value": "U0VDT05E"
            }
        ],
        "notifications": [
            {
              ...
            }
        ]
    }
}
```

**Comment by ixje** [comment]
Ok, but it is missing when the execution ends in `HALT` whereas in C# it is always there.

**Comment by roman-khimov** [comment]
Well, we can remove `omitempty` if that makes us more compatible in some ways.

**Comment by fyrchik** [comment]
@ixje talking about response JSON schema, could you give a link if it is public?

**Comment by ixje** [comment]
@fyrchik There is no official schema to my best knowledge and I have yet to commit the updates to our RpcClient with the schemas. Let me know if [this](https://github.com/CityOfZion/neo-mamba/blob/b60079d97f0485a61547f4e2e044592f4396c4f6/neo3/wallet/account.py#L93) is useful to you ([NEP-6 Account](https://github.com/neo-project/proposals/blob/master/nep-6.mediawiki#Account) schema) and I can ping you when I commit the Rpc response schemas.
