### ISSUE TITLE
Dependabot reports for potential security vulnerabilities

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neo-go#2521]
![image](https://user-images.githubusercontent.com/14617699/170656228-cd1b6017-f86c-4ce8-b5a2-8592e0786e29.png)

https://github.com/nspcc-dev/neo-go/security/dependabot

**Comment by roman-khimov** [comment]
I know about it, but I'm not sure we have an actual problem here, because originally it's for a different version of the package we use. But it needs to be checked.

**Comment by 532910** [comment]
I believe the main actual problem is in the banner itself, as github is the front page for our code.

**Comment by roman-khimov** [comment]
It's not visible to outsiders.

**Comment by roman-khimov** [comment]
I've just looked at the code, and it seems like it affects us. As well as go-yaml/yaml#665, so we need to move on with #2085.
