### ISSUE TITLE
support wallet password from config

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neo-go#2536]
As an automation engineer, I need to use `neo-go` cli in scripts and autotests. Wallets require to enter the password interactively. For this purpose I use `expect` of `pyexpect` python library. The issue is that interactive password entry needs to be adjusted for every environment and every OS -- at the moment it is Jenkins, bash and python script on Linux and MacOS.

If wallet password might be obtained from config non-interactively it will be a convenient feature for using `neo-go` in automation.

The proposal is to have the same way to configure defualt wallet, address and password for it, as we have in `neofs-cli` and corresponding tools

**Comment by roman-khimov** [comment]
Based on: https://github.com/nspcc-dev/neo-preodolenie/blob/19717aac3dcbe6100ec91ec2100fa63d2d65b8d0/neo-preodolenie/importer.py

```
#!/usr/bin/python3

import sys
import pexpect
import subprocess

neogo = "/home/rik/dev/neo-go/bin/neo-go"

def accept(c: pexpect.spawn, name: str, pwd: str):
    c.expect('account > ')
    c.sendline(f'{name}\r')

    for _ in range(2):
        c.expect('password > ')
        c.sendline(f'{pwd}')

    c.wait()


wallet_path = f"twa.json"

# create wallet file
subprocess.check_call(f"{neogo} wallet init -w {wallet_path}", shell=True)

# create acc
child = pexpect.spawn(f"{neogo} wallet create -w {wallet_path}", encoding='utf-8')
child.logfile=sys.stdout
accept(child, "personal", "qwerty")
```

Result:
```
$ ls -l twa.json
ls: невозможно получить доступ к 'twa.json': Нет такого файла или каталога
$ python3 some.py 

{
        "version": "3.0",
        "accounts": [],
        "scrypt": {
                "n": 16384,
                "r": 8,
                "p": 8
        },
        "extra": {
                "Tokens": null
        }
 }

wallet successfully created, file location is twa.json
Enter the name of the account > personal
personal
Enter new password > qwerty

Confirm password > qwerty
$ ./bin/neo-go wallet dump -w twa.json

{
        "version": "3.0",
        "accounts": [
                {
                        "address": "NirEEsFmj676RHs7dqTLM7jS1gWrzKmtYs",
                        "key": "6PYTN7FBnYVuZNsjwzBJ3gyjvBhVtjnDXGeeRxB6yvkCwjw6ZQz1xaRUKx",
                        "label": "personal",
                        "contract": {
                                "script": "DCEDsNQjflm1dnSft+rrYlreqUX+h/4NNMLymgHNRXaYpApBVuezJw==",
                                "parameters": [
                                        {
                                                "name": "parameter0",
                                                "type": "Signature"
                                        }
                                ],
                                "deployed": false
                        },
                        "lock": false,
                        "isDefault": false
                }
        ],
        "scrypt": {
                "n": 16384,
                "r": 8,
                "p": 8
        },
        "extra": {
                "Tokens": null
        }
 }
```
Does it work for you?

**Comment by roman-khimov** [comment]
And just FYI, from https://pexpect.readthedocs.io/en/stable/api/pexpect.html#spawn-class:

> This works even for commands that ask for passwords or other input outside of the normal stdio streams. For example, ssh reads input directly from the TTY device which bypasses stdin.

**Comment by alexvanin** [comment]
Unrelated, but `c.wait()` may not behave the same on macOS and Linux machines. The example above is hanging on `c.wait()` on macOS 12.4.

To solve this, `pytest`, for example, just use `flush` method and do not wait at all: [link](https://github.com/brianmaissy/pytest/blob/a9457345eef296dbc2b76152a3471c019f8ebde5/testing/test_pdb.py#L151-L155).

**Comment by roman-khimov** [comment]
BTW, configs don't solve the wallet creation case.

**Comment by realloc** [comment]
CLI config feature should cover cases when already existing wallets are used. Like in AWS cli, user initializes the config, fills it with auth data, network settings, etc, and uses without interactive input or account/network settings in cli arguments.

**Comment by roman-khimov** [comment]
1. We have a `config.Wallet` that can be reused for this ~bug~ feature with its path/password data set. All commands where it's relevant also have an `--address` parameter that can specify which address to use, so just two additional data strings from this configuration file is enough.
2. Everywhere we have `--wallet` parameter (`walletFlag` and `walletPathFlag`) we should also accept `--wallet-config` with a path to this YAML configuration file. It can replace `--wallet` path specification and it also has a password inside, so there is no need to ask for it.
3. And that's it. Wallet creation is a separate matter.
