### ISSUE TITLE
Windows Defender alert on v0.99.0

### ISSUE THREAD

**Issue by EdgeDLT** [nspcc-dev/neo-go#2547]
Windows Defender blocks NeoGo v0.99 download due to `Trojan:Win32/Wacatac.B!ml`

![image](https://user-images.githubusercontent.com/21316801/172404582-23fad6f2-ca9e-4215-81a2-a1c740f14dd3.png)

No false positive for v0.98.5, so maybe worth a look what may be triggering this.

**Comment by roman-khimov** [comment]
Just to make sure, your file has 0e0196308184602156a19e07d05434355547f84c32a5648e18c9f59460e02eaf sha256 hash?
Virustotal gives it 2/50: https://www.virustotal.com/gui/file/0e0196308184602156a19e07d05434355547f84c32a5648e18c9f59460e02eaf
But frankly I have no idea what might be triggering it.

**Comment by roman-khimov** [comment]
Well, I've submitted this as false positive to Microsoft, let's see how it goes.

**Comment by roman-khimov** [comment]
But seems like this happens to Go binaries from time to time: https://go.dev/doc/faq#virus

**Comment by roman-khimov** [comment]
And I've even got a reply:

> At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.
>
>     1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
>     2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
>     3. Run "MpCmdRun.exe -SignatureUpdate"

Please try it.

**Comment by EdgeDLT** [comment]
Got `No updates needed` on the signature update, probably happened on boot this morning. Removed the Defender exception and tested, no alert. Woo Microsoft I guess 😄
