### ISSUE TITLE
Node services may never be stared after SIGHUP

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#2564]
Consider the case of reloading RPC server on SIGHUP: https://github.com/nspcc-dev/neo-go/blob/ea69b72cd8dc33fe9e7e445fd1010154adb096ba/cli/server/server.go#L537-L539 Consider the following situation:
1. Node is in sync, all services are running well including RPC server. Node's server has already been called `tryStartServices` ones: https://github.com/nspcc-dev/neo-go/blob/ea69b72cd8dc33fe9e7e445fd1010154adb096ba/pkg/network/server.go#L419-L433
2. Accidently node loses more than 2/3 peers connection.
3. Node receives `SIGHUP` and reloads RPC server. `StartWhenSynchronized` option is set to `true`. Node is temporary out of sync (less than 2/3 of minpeers are connected, so `serv.IsInSync()` will return `false` and relladed RPC server won't be started immidiately.
4. Node restores all missing connections and fetches all recent blocks. But reloaded RPC server will never be started, because `tryStartServices()` can start services only once due to this block of code: https://github.com/nspcc-dev/neo-go/blob/ea69b72cd8dc33fe9e7e445fd1010154adb096ba/pkg/network/server.go#L419-L422

As a result, newly created RPC server will never be started even if node reaches sync state.

**Comment by roman-khimov** [comment]
> Node is temporary out of sync

The way it's used in the `cli` package this is never supposed to happen, externally-visible `IsInSync()` must check for `syncReached` flag.
