### ISSUE TITLE
Server: Add a processing queue

### ISSUE THREAD

**Issue by decentralisedkev** [nspcc-dev/neo-go#258]
For some requests, we do not need to wait for. We can add a queue with a channel like in peer.go, to process these asynchronously.

**Comment by volekerb** [comment]
Can you please bring some light here? Since I found using peers with channel for connections in dev branch.

**Comment by decentralisedkev** [comment]
Channels can be blocking or non-blocking. For the items that we do not need to wait for, non-blocking, you can use a queuing system to give back control to the caller.

**Comment by roman-khimov** [comment]
Closing as obsolete, see #283 and #307.
