### ISSUE TITLE
Unexpected compiler behaviour while inlining interop function

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#2587]
#### Problem

Consider the case when the following is added to `pkg/interop/types.go` file (`interop` package):
```
func BothNull(a interface{}, b interface{}) bool {
	if a == nil && b == nil {
		return true
	}
	return false
}
```

This function is being called from the compiler testing code:
```
t.Run("test", func(t *testing.T) {
src := `package foo
import (
	"github.com/nspcc-dev/neo-go/pkg/interop"
)

func Main() bool {
	var a interop.Hash160
	var b interop.Hash160
	return interop.BothNull(a, b)
}
`
	eval(t, src, true)
})
```
This test fails with the `stack contains unexpected items` assertion:
```
   Error:      	Not equal: 
        	       expected: 1
        	       actual  : 2
   Test:       	TestInteropTypesComparison/Hash160/test
   Messages:   	stack contains unexpected items
```
One extra boolean value is located at resulting stack. It happens because two boolean values were pushed on stack without any condition (`PUSH1` for `return true` at instruction 15 and `PUSH0` for `return false` at instruction 18), see the comments:
```
INDEX    OPCODE      PARAMETER
0        INITSLOT    2 local, 0 arg    <<
3        PUSHNULL    
4        STLOC0      
5        PUSHNULL    
6        STLOC1      
7        LDLOC0      
8        ISNULL      
9        JMPIFNOT    18 (9/09)    // It's null, thus no JMP occurs.
11       LDLOC1      
12       ISNULL      
13       JMPIFNOT    18 (5/05)   // It's also null, thus no JMP.
15       PUSH1       
16       CONVERT     Boolean (20)  // Should RET after this from inlined BothNull function
18       PUSH0       
19       CONVERT     Boolean (20)
21       RET         
```
Also, the result of the program is invalid because the upper stack element is taken.

#### Summary

Not sure, but it seems to me as a bug in the compiler connected with interop-related functions inlining. Investigation is in progress.

#### Additional content

The described behaviour was discovered during interop equality helpers testing, it's not expected and blocks  https://github.com/nspcc-dev/neo-go/issues/2249 solution.

**Comment by roman-khimov** [comment]
That's likely to be something with `return` handling wrt inline functions, they obviously don't emit RET in this case, but instead they should jump out of the inlined section.

**Comment by roman-khimov** [comment]
Yeah, I guess any multireturn case is broken. You can just `return a == nil && b == nil` in your case and any other multiret code can be restructured to have one `return`. That at least will allow to progress with #2249. But the real problem is somewhere around
```
        case *ast.ReturnStmt:
...
                if len(c.pkgInfoInline) == 0 {
                        emit.Opcodes(c.prog.BinWriter, opcode.RET)
                }
```
