### ISSUE TITLE
Wallet: functionality for creating a native neo-go wallet

### ISSUE THREAD

**Issue by anthdm** [nspcc-dev/neo-go#26]
## Problem
At the moment there is no support for wallets yet. This could be so handy when we are starting to deploy smart contracts written and compiled in Go.

## Solution
Implement full wallet functionality through CLI.

## Quick start references
- [official NEO project](https://github.com/neo-project/neo/tree/master/neo/Wallets)
- [neo-python](https://github.com/CityOfZion/neo-python/blob/master/neo/Wallets/Wallet.py)
- [neo-js](https://github.com/CityOfZion/neo-js/tree/develop/dist)

**Comment by anthdm** [comment]
I just noticed there is no wallet folder in `/pkg` yet. That would be a good start :)

**Comment by vladucu** [comment]
@anthdm I can give this a go, if that's cool

**Comment by anthdm** [comment]
Can you coordinate your efforts with @pawanrawal I think he's on this?

**Comment by pawanrawal** [comment]
Yeah, I am on this and should have something out soon.

**Comment by anthdm** [comment]
Just merge a huge PR into master containing lots of crypto + wallet code. This should give a huge boost to the wallet package.

Things that still need to be done. 
- Extend the wallet command in the neo-cli
- Add more API's to the Wallet struct (check original #c implementation for those API's)
- Some security improvements

I will start working on the smart contract part, so we can wire things together (compiler, wallet and smart contracts)

**Comment by hal0x2328** [comment]
@anthdm assuming the three tasks from your comment of March 2 last year are still outstanding, I'd like to create three new issues for those, tagged with an impact and added to the project board, in order to encourage progress. I need a few more details on the specifics (especially the security improvements) to make the specifics of the tasks clear (or if you'd like, you could create the issues and I'll do the rest).

**Comment by roman-khimov** [comment]
`dev` is currently completely missing the wallet functionality.

`master` is a bit different, on the CLI side it only exposes `open` and `create` commands, `open` has no implementation at all, but `create` really does create something that looks like a wallet. Internally in the `wallet` package there is a NEP-2 implementation, WIF, wallet creation/import, private/public key management, although I guess it's still far away from full wallet functionality.

**Comment by roman-khimov** [comment]
Two inspiring links:
https://docs.neo.org/docs/en-us/node/cli/cli.html
https://neo-python.readthedocs.io/en/latest/prompt.html#managing-wallets

What we need here is ability to:
 * import/export wifs
 * import/export nep2
 * generate new keys for existing wallets
 * import smart contract address
 * delete addresses
 * maybe sign arbitrary things (it's strongly related to multisig #670, though)

We don't have a concept of watch-only addresses, so we don't care about those, the same way as "indexing" that is being done by the chain for us. Our wallet is just a NEP-6 thing that contains keys, scripts and allows to manage those. GAS claims and asset transfers are separate tasks (#669 and #670).

**Comment by roman-khimov** [comment]
I think the only thing we're still missing is ability to import arbitrary contracts and sign transactions using them, like here:
https://docs.neo.org/docs/en-us/sc/sample/Lock2.html

**Comment by roman-khimov** [comment]
And maybe deleting addresses/contracts/keys.
