### ISSUE TITLE
VM CLI: set ip

### ISSUE THREAD

**Issue by ixje** [nspcc-dev/neo-go#2606]
I think it could be useful to have a command that allows for setting the instruction pointer. Right now you can load a nef, but `run` will always execute whatever function or code is at offset 0 (obviously). Having the ability to set the instruction pointer we could at least call some other functions (the offset can be grabbed from the manifest). Of course it's still limited to functions without arguments but that could be all you need sometimes.

**Comment by roman-khimov** [comment]
@AnnaShaleva, IIUC `run method` works now even with 0.99.4? Arbitrary jumps can be useful anyway though.

**Comment by AnnaShaleva** [comment]
> `run method` works now even with 0.99.4

Yes, it works.

> Of course it's still limited to functions without arguments

Also, `run method` is able to parse arguments, e.g. `run method arg1 arg2 ...`. After #2740 arguments parsing will work exactly as `contract testinvokefunction` works.

> Arbitrary jumps can be useful anyway though.

I'll add some `move` or `jmp` command for this.
