### ISSUE TITLE
Change version output format to match neofs-*

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neo-go#2611]
It would be very helpful to have `neo-go` version output be in the same format as other NeoFS components, like
```
$ ./neofs-node --version
NeoFS Storage node
Version: v0.30.0-1-g54fe7667 
GoVersion: go1.18.3
```

```
// BuildInfo returns human-readable information about this binary.
func BuildInfo(component string) string {
        return fmt.Sprintf("%s\nVersion: %s \nGoVersion: %s\n",
                component,
                Version,
                runtime.Version(),
        )
}
```

**Comment by roman-khimov** [comment]
"component" for NeoGo? `NeoGo`?

**Comment by realloc** [comment]
> "component" for NeoGo? `NeoGo`?

`neo-go`, as it is now, or `NeoGo`. Both are fine.

**Comment by roman-khimov** [comment]
We tend to use `NeoGo` in articles/presentations and we have `NeoFS Something` used for neofs components, so probably `NeoGo` would be a better choice.
