### ISSUE TITLE
VM: stackitem consistency in return values

### ISSUE THREAD

**Issue by decentralisedkev** [nspcc-dev/neo-go#262]
@Dautt pointed out that the comparison for Byte array returns the native bool type, while the Integer comparison returns a Boolean stack item.

The thought process for returning a Boolean stack item, instead of the native golang bool type, is because if we are comparing two stack items for a truth value, we are more than likely going to push that value to the stack. For example, checking if two integers are equal, then pushing the results onto the stack.

For this reason, it should be the rule that all comparisons on structs return a StackItem Boolean and not a native bool. With this almost every method on a stackItem, will return a StackItem.

This would not change the code too much since creating a new Boolean does not return an error

**Comment by dauTT** [comment]
We will fix it as a side effect of #167

**Comment by decentralisedkev** [comment]
@dauTT Let's have them as separate PRs to make reviewing them easier

**Comment by dauTT** [comment]
If we stick to the same line of thought, I believe any operation between stack Items should returns again a stack item. For instance this method

```go
// Lt returns a bool value from the comparison of two integers, a and b.
// value is true if a < b.
// value is false if a >= b.
func (i *Int) Lt(s *Int) bool {
	return i.Value().Cmp(s.Value()) == -1
}
```
should be amended as follow

```go
// Lt returns a boolean from the comparison of two integers, a and b.
// value is true if a < b.
// value is false if a >= b.
func (i *Int) Lt(s *Int) *Boolean {
	res := i.Value().Cmp(s.Value()) == -1
        return NewBoolean(res)
}
```

The same apply for following methods:
```
Gte, Lte, Lt, Gt, Within, 
```
and potentially other as well.

**Comment by volekerb** [comment]
wan't able to find this one implemented in any branch

**Comment by volekerb** [comment]
as of now we have `v.estack.PushVal()` which inside converts value to it's proper type.
In case of bool it will be Bool:
https://github.com/nspcc-dev/neo-go/blob/8441b31b4b364427a1971a4b28489c5765cf30c0/pkg/vm/stack_item.go#L38

which looks correct as for me and compare to C#:

```
    public static implicit operator StackItem(bool value)
    {
      return (StackItem) new Neo.VM.Types.Boolean(value);
    }
```
looks like the same at this point.

Wasn't able to find `Gte, Lte, Lt, Gt, Within, ` functions.
Probably I'm missing smth here. @roman-khimov @im-kulikov

**Comment by roman-khimov** [comment]
Most probably this was originally submitted against the `dev` branch, but for some reason was also thought of as relevant for the `master`. In fact, our current VM compares values in a different way and just doesn't have the problem, so I'm closing it.
