### ISSUE TITLE
[uint160] : Uint160DecodeStringBE does not produce the desired uint160 

### ISSUE THREAD

**Issue by mystrycrypto** [nspcc-dev/neo-go#2647]
```
hashstring := "0xd2a4cff31913016155e38e474a2c06d08be276cf"
tokenHash, _ := neoutil.Uint160DecodeStringBE(strings.TrimPrefix(hashString, "0x"))
decimals, err := client().NEP17Decimals(tokenHash)
```
Produce: ` invocation failed: Called Contract Does Not Exist: 0xcf76e28bd0062c4a478ee35561011319f3cfa4d2
`
Am I doing it wrong?

**Comment by roman-khimov** [comment]
Well, that's neo-project/neo#938 that is wrong here (but it can't be fixed now) and you've got a GAS contract hash that needs to be decoded with `Uint160DecodeStringLE`.

**Comment by roman-khimov** [comment]
Seems to be solved to me.
