### ISSUE TITLE
Move account/signers handing into cli library

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#2682]
Smart contract invokers and NEP transfers are very similar in their handling of wallets/accounts/signers. It all boils down to an `actor` instance that then does something for us. We can merge this code into some `options.GetActor`, but it requires some untangling of the current status quo since different commands have slightly different options and some have signers used for `invoker`.

**Comment by AnnaShaleva** [comment]
`canceltx` also use `actor`, ref. #3151.
