### ISSUE TITLE
Fail compilation for type assertion statement with two return values

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#2692]
Given the test:
```
func TestTypeAssertionWithOK(t *testing.T) {
	src := `package foo
	func Main() bool {
		a := 1
		var u interface{}
		u = a
		_, ok := u.(int)
		return ok
	}`
	eval(t, src, true)
}
```
the following opcodes will be generated:
```
INDEX    OPCODE      PARAMETER
0        INITSLOT    3 local, 0 arg    <<
3        PUSH1       
4        STLOC0      
5        PUSHNULL    
6        STLOC1      
7        LDLOC0      
8        STLOC1      
9        LDLOC1      
10       DUP         
11       ISTYPE      Integer (21)
13       JMPIF       17 (4/04)
15       CONVERT     Integer (21)
17       DROP        
18       STLOC2      
19       LDLOC2      
20       RET
```
which results in a runtime panic:
```
        	Error:      	Received unexpected error:
        	            	at instruction 18 (STLOC2): runtime error: index out of range [-1]
        	Test:       	TestTypeAssertionWithOK
```

The reason is somewhere around `13       JMPIF       17 (4/04)` instruction, we're not leaving on stack boolean result after that, thus, STLOC2 fails to pick it from stack (actually, the stack is empty by that moment thanks to `17       DROP`).

**Comment by roman-khimov** [comment]
Can we support this at all? We don't have any proper type information in runtime, so you either return `ok` based on `ISTYPE` (not doing `CONVERT` at all) or `CONVERT` will fail and abort whole execution. Yeah, you can do a more thorough type check before invoking `CONVERT`, but then you have a problem with structures, will you also perform a check for each of the structure elements?

**Comment by AnnaShaleva** [comment]
> return ok based on ISTYPE (not doing CONVERT at all)

I think we can implement that and support simple cases, why not?

**Comment by roman-khimov** [comment]
There are assumptions on how this thing is supposed to work based on Go specification. Every Go programmer intuitively has them and the question is how these assumptions match to our implementation and does this (non-standard) behavior add any value. Do we have any valid use cases for type checks in contracts? That'd be something where `!ok` case has some reasonable behavior. What problem can't be solved without it?

It's not the only place we diverge from the specification, it can be done, but we better do it if we know why exactly and in what fashion (because there are options) we need it. Without that I'd rather just fail the compilation for now.

**Comment by AnnaShaleva** [comment]
> Do we have any valid use cases for type checks in contracts?

I faced with one when I wrote a contract (NNS) migration code and thought the descrideb case may be useful on the contract storage scheme update. Consider the case when old contract uses a storage scheme where some integer value is stored by `prefixA`. The updated contract should store the array of ints by the same prefix (ref. https://github.com/neo-project/non-native-contracts/commit/8ac2b807343e2e88a3a6534ed15594216db7a72b, yeah). So migration code should know what's the type of the value stored by `prefixA` to be able to perform subsequent contract update.

This problem can easily be solved with contract versioning (which is currently done in neofs contracts). Another way to solve it is to use different new `prefixB` to store the array of integers and remove values stored by `prefixA` on the subsequent contract update. But I've added this extra type check and faced with the problem during tests.

> Without that I'd rather just fail the compilation for now.

So I agree that we may easily go without `ok` notation support, but then let's at least fail compilation for such cases with some meaningful error. Current compiler behaviour allow to compile given example, which results in a script runtime failure. Or we may add a note to our compiler documentation.

**Comment by roman-khimov** [comment]
> This problem can easily be solved with contract versioning

Yes, and that's kinda the expected way to handle migrations. It can be simplified if we know exactly the initial and the target versions, it can be handled with some prefix changes like you mentioned, but in general versions and clear version to version conversion code is the way to go, I'd not even try doing runtime data checks for this. If we know the old version it has some exact schema and this schema can be handled in predictable way.

> let's at least fail compilation for such cases with some meaningful error

Sure, that's at least the safe thing to do for now. And it can be changed later if we have reasonable use cases/behavior suggestions.

> we may add a note to our compiler documentation.

And we should do this too anyway, it's important to set proper assumptions in our documentation as well.
