### ISSUE TITLE
compiler: do not inline some of interop functions

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#2700]
See https://github.com/nspcc-dev/neo-go/pull/2698#discussion_r974317105, we need to generate code when we face the `address.ToHash160` function declaration (if it's used from main program with argument different from BasicLiteral), and after that be able to call it using `CALL` instruction instead of inlining it each time it's used.

**Comment by AnnaShaleva** [comment]
Maybe we have some other interop functions that need to be handled the same way.

**Comment by roman-khimov** [comment]
It can be handled by excluding `libgo` package from inlining completely, but I'm not yet sure we should do it.

**Comment by AnnaShaleva** [comment]
> It can be handled by excluding libgo package from inlining completely
It's not that trivial, we have a couple of places where assumption on inlining is based on `isInteropPath`. And after that to decide about `address.ToHash160` declaration emission we need to visit all usages of this method and check their arguments. If all usages are with BasicLiteral argument, then we don't need to emit function declaration code at all.

**Comment by AnnaShaleva** [comment]
Actually, I agree with https://github.com/nspcc-dev/neo-go/pull/2698#discussion_r974343225, it's not a big problem to inline this function and do not complicate interops handling code. Let's leave it as is.
