### ISSUE TITLE
allow preflight OPTIONS request

### ISSUE THREAD

**Issue by worlddeleteRin** [nspcc-dev/neo-go#2721]
Would be good to handle preflight request, currently it's hard to query rpc node with browser app, browser tries to do OPTIONS request before POST (it asks server, which request methods are allowed, allowed origins and etc.), but getting
 `{"id":null,"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid Params","data":"invalid method 'OPTIONS', please retry with 'POST'"}}`
It's this part of code responsible for that in `pkg/services/rpcsrv/server.go`, which retrict any methods that not POST
![image](https://user-images.githubusercontent.com/48155364/193323984-7021319e-2897-4854-9c35-056496491c4a.png)

Actually what can be done is - return successful response with allow methods (only POST in this case), like described in mdn docs [click](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS)
Doing that will let browser to successfully continue POST request :thinking:

**Comment by roman-khimov** [comment]
Well, that means an extension of `EnableCORSWorkaround` kludge we have. It's really a misuse of CORS and proper setups should have some reverse proxy that handles it, but looks like proper setups are not that popular.
