### ISSUE TITLE
Improve VM CLI

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#2729]
After #2723 we have several unfinished tasks:

1. Allow to properly provide transaction (script, signers&scopes) to CLI context and update `resetInteropContext`.
2. Reuse all arguments-related functionality from `invoke*` commands of our standard CLI (arguments parsing, signers parsing, etc.)
3. Improve and unify commands documentation (adjust Usage, UsageText, Description).
4. Add 'loaddeployed' command.
5. Verbose chain logging (maybe add a separate `--debug` option for this). It will automatically verbose `Runtime.Log()` messages.

Several issues will be added after #2723 merge.

**Comment by roman-khimov** [comment]
> Allow to properly provide transaction

We can have
```
loadtx <txid>
```
As well.

**Comment by AnnaShaleva** [comment]
6. We may need to squash `changes` and `storage --diff` functionality, need to discuss it.
