### ISSUE TITLE
Implement "header_of_added_block" RPC WS subscription

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#2751]
See https://github.com/nspcc-dev/neo-go/pull/2749#discussion_r998285328.

**Comment by roman-khimov** [comment]
The main thing is that headers are short and in many cases people don't need full block data (tx waiter loop, for example).

**Comment by AnnaShaleva** [comment]
@roman-khimov, we actually have two different meanings of `header_added` subscription. The first one is to notify the user about only header's content by the moment when *block* is stored (which happens *after* block's processing). The second one is to notify the user about the fact that *header* is stored (which happens *before* the block processing in `(bc *Blockchain) addHeaders`). The first option is needed for proper `Waiter` work. However, the second one is also may be useful for our users (but our code probably doesn't have usecases of this option).

This issue is about implementing the first one, but I'm wondering, is `header_added` the right name for this subscription? Because technically it doesn't match the real header addition event.

**Comment by roman-khimov** [comment]
It can be made a parameter to `block_added`, but for some reason I don't quite like it. Any better naming suggestions?

**Comment by AliceInHunterland** [comment]
@roman-khimov  @AnnaShaleva `header_content` for the first, and `header_added` for the second case?

**Comment by AnnaShaleva** [comment]
> It can be made a parameter to block_added,

I also don't like it, I love that clear `SubscribeFor*` interface we have now and with parameter we should provide channel of `*block.Block` instead of channel `*block.Header`, which isn't good.

> Any better naming suggestions

I thought about something like `header_persisted` (`SubscribeForHeadersPersist`, the first case) and `header_added` (SubscribeForHeaders, the second case), but it's also kludgy. I also thought about something like `blockheader_added` for the first case, like a basic `block_added`, but I also don't quite like it.

**Comment by roman-khimov** [comment]
`header_of_added_block`, maybe?

**Comment by AnnaShaleva** [comment]
Let’s then implement both cases while we’re here.

**Comment by AnnaShaleva** [comment]
@roman-khimov, do we ever need `header_added` to be implemented? (the second case)

**Comment by AnnaShaleva** [comment]
> Not a priority. A possibility, yes.

Let's then create a separate https://github.com/nspcc-dev/neo-go/issues/3259 for it. It has some caveats on the blockchain side (to properly distinguish subscriber channels).
