### ISSUE TITLE
error on add block : block is not newer than the previous one

### ISSUE THREAD

**Issue by ikovalev1** [nspcc-dev/neo-go#2753]
How to reproduce:
1) move the system time forward on 3 of 4 nodes like:
hwclock --set --date="01/01/24 00:00:00" && hwclock --hctosys
2) reboot the nodes
3) journalctl -fu neogo-morph-cn | rg "error"
```
Oct 19 13:39:46 az neo-go[284]: 2022-10-19T13:39:46.087Z        WARN        error on add block        {"error": "block is not newer than the previous one"}
```

**Comment by roman-khimov** [comment]
nspcc-dev/dbft#64 + #2752
