### ISSUE TITLE
subscribe filtering issue

### ISSUE THREAD

**Issue by vincentgeneste** [nspcc-dev/neo-go#2775]
Hi!

We're trying to use subscribe for both FAULT and HALT tx, it doesnt look like it is working as intended

```
{
        "jsonrpc": "2.0",
        "method": "subscribe",
        "params": ["transaction_executed", {"container": hash}],
        "id": 1
}
```

i would expect this to work, but throws params invalid, otherwise maybe there's another way if i want to subscribe both to FAULT and HALT tx?

just HALT or just FAULT works of course like this

```
{
        "jsonrpc": "2.0",
        "method": "subscribe",
        "params": ["transaction_executed", { "state": "HALT", "container": hash }],
        "id": 1
}
```

**Comment by roman-khimov** [comment]
Are you using 0.99.4? `container` filter is a very recent addition, IIRC not available in stable versions yet.

**Comment by vincentgeneste** [comment]
> Are you using 0.99.4? `container` filter is a very recent addition, IIRC not available in stable versions yet.

Yes using 0.99.4

**Comment by roman-khimov** [comment]
I think I see where your problem is with the first request. I'm not sure why we've not seen it previously though, RPC tx waiter code uses the same request. @AnnaShaleva, please take a look at it, should be easy to fix/test.
