### ISSUE TITLE
Allow to set log level in config

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#2794]
Currently, to change log level in complex setups (systemd) we need to change systemd unit file, perform `daemon-reload` and restart the service.
It would be nice to
1. Be able to change only a single field in the configuration.
2. Possibly, support log level change on SIGHUP.

**Comment by roman-khimov** [comment]
We only have `-d` flag at the moment, but the first point totally makes sense. I'm not sure about the second one, IIRC it's not easy to do with zap.
