### ISSUE TITLE
Excessive network traffic if there are less than `MinPeers` peers in the network

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#2796]
v0.99.5 with minimal non-network changes on top, 4-node cluster, 1 node is down, `MinPeers: 3`. I know `MinPeers: 2` will also work fine, the issue is not about that.

```
$ journalctl -u neogo-morph-cn --since '1 minute ago' >out

$ head -n2 out
-- Journal begins at Tue 2022-11-15 09:32:20 UTC, ends at Tue 2022-11-15 09:54:26 UTC. --
Nov 15 09:53:26 vedi neo-go[2195]: 2022-11-15T09:53:26.830Z        WARN        peer disconnected        {"addr": "172.26.161.115:40333", "error": "unexpected empty payload: CMDVersion", "peerCount": 6}

$ tail -n1 out                                         # double check it is really 1 minute
Nov 15 09:54:27 vedi neo-go[2195]: 2022-11-15T09:54:27.636Z        WARN        peer disconnected        {"addr": "172.26.162.172:40333", "error": "already connected", "peerCount": 7}

$ rg --count 'peer connected' out
421702
```

1. We already have some sleep which is done only on `dial` failures https://github.com/nspcc-dev/neo-go/blob/master/pkg/network/discovery.go , may be we add sleep in more cases? `already connected`, `identical node id` etc.
2. Seeing ` {"addr": "172.26.161.115:55484", "peerCount": 10}` in a 3-node cluster where all nodes have static IPs defined in `SeedList` is unexpected. Of course there are trade-offs everywhere, but at least this behaviour could be configurable.

**Comment by roman-khimov** [comment]
2. Still it can happen at some stage because nodes connect to each other and this event is registered before the handshake (we only know we have the same node after the handshake).
1. It has to keep trying, but I'll check if it works as intended (retrying after the timeout).

**Comment by fyrchik** [comment]
2. Yes, but if we know that we are connected to `a.b.c.d:port`, do we need to try to connect to it again? (not sure if this is the case currently).

**Comment by roman-khimov** [comment]
Unfortunately always having less than `MinPeers` breaks `peersNumber >= s.MinPeers` synchronization condition. And that won't be changed. So even if the nodes are to stop connecting to each other in your case they'll never start the consensus process.
