### ISSUE TITLE
Too expensive db compaction

### ISSUE THREAD

**Issue by laizy** [nspcc-dev/neo-go#2808]
```
2022-11-16T19:14:16.019+0800	INFO	persisted to disk	{"blocks": 35, "keys": 5761, "headerHeight": 1670727, "blockHeight": 1670726, "took": "21m58.6459253s"}
2022-11-16T19:50:15.280+0800	INFO	persisted to disk	{"blocks": 26, "keys": 5521, "headerHeight": 1838889, "blockHeight": 1838888, "took": "25m2.0089036s"}
```
I found the current storage schema use `hash` instead `height` as key. Since the hash act as random value, this will greatly increase the leveldb's compaction burden. Please try to use `height` as block key, `height`+ `txIndex` as transaction key.

**Comment by roman-khimov** [comment]
1. You can try BoltDB and see if it makes any difference in your scenario.
2. This was considered previously, but blocks are naturally identified by hashes and changing to height-based key will require storing additional data and lead to additional DB lookups in many cases.
3. 20m+ persist time seems to be a hardware problem to me. I regularly have to resynchronize the chain and my SSD has a lot wear, but even then it's rarely 10s+.

**Comment by laizy** [comment]
I think in most cases, only the recently generated blocks/transactions will be accessed, so cache the latest 1024 hash-> height map in memory will remove the additional DB lookup.  And it will require little additional storage, since the hash key is now replaced with short uint64 key.

**Comment by roman-khimov** [comment]
> And it will require little additional storage, since the hash key is now replaced with short uint64 key.

Plus the hash->index mapping which takes additional space.

It can be changed only if there is a clear performance benefit, but I doubt there is one even considering any caches, likely it's going to be about the same or slightly worse.

**Comment by roman-khimov** [comment]
`headerHashes` will be changed eventually to not store all of the hashes, absent that hash->index needs to be resolved somehow.
