### ISSUE TITLE
Change logging to use uber zap

### ISSUE THREAD

**Issue by volekerb** [nspcc-dev/neo-go#284]
As proposed in [#247](https://github.com/nspcc-dev/neo-go/issues/247) we have to change fmt.println logging to log but at the same time suggest to use [uber/zap](https://github.com/uber-go/zap) since it has better performance compare to logrus which is used in master

**Comment by fyrchik** [comment]
There are more important advantages imo:
- zap can be disabled/enabled per component
- zap can be hierarchical (one can create child loggers based on parent ones, all fields will be inherited)

**Comment by roman-khimov** [comment]
Now that the DBFT library is using it it's more important to fix this issue for logging consistency.
