### ISSUE TITLE
WSClient uses library which is in archive-mode

### ISSUE THREAD

**Issue by acid-ant** [nspcc-dev/neo-go#2843]
Gorilla toolkit is now in archive mode https://github.com/gorilla#gorilla-toolkit
Need to find replacement for library `github.com/gorilla/websocket v1.4.2`

**Comment by roman-khimov** [comment]
Thanks for pointing it out! Back when it was chosen it was already somewhat stale, but at the same time we were not able to find anything better (API/feature-wise). Now read-only is not the end of the world, it still can be used, but of course we better look for some maintained alternative/fork.

Any suggestions are welcome.

**Comment by roman-khimov** [comment]
No longer archived -> no problem!
See https://github.com/orgs/gorilla/discussions/9 and https://github.com/gorilla/websocket/commit/931041c5ee6de24fe9cba1aa16f1a0b910284d6d
