### ISSUE TITLE
Store initial voter reward data in the NEO balance

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#2844]
Implement and test the second option from https://github.com/neo-project/neo/issues/2815#issuecomment-1259916590. Unit tests can be omitted for the first iteration, but we need to:
 * perform correctness tests, make a `db restore` for testnet and mainnet with storage dumps saved on a regular node and on a patched one, then `scripts/compare-dumps` can be adjusted to only compare GAS balances; obviously we need to have exactly the same balances in the patched version as we have on a regular node
 * do performance tests, run `db restore` for testnet, mainnet and NeoFS T5 testnet sidechain (without storage dumps) on the same machine with LevelDB/BoltDB and `KeepOnlyLatestState` enabled/disabled, check for restoration time and the resulting DB size

The expectation is that we would have noticeably smaller DB and better time for NeoFS sidechain, probably better time and about the same size for testnet/mainnet. If that expectation is met, we can propose this change to neo-project/neo and then either complete it as an option (I really expect it to be useful for NeoFS chains) or a proper protocol change (3.7.0/3.8.0).

**Comment by roman-khimov** [comment]
NeoFS mainnet sidechain can also be tried (it's much longer than T5, so more interesting wrt this problem) after #2848.

**Comment by ZhangTao1596** [comment]
I'm working on https://github.com/ZhangTao1596/neo/tree/fix-vote-reward. Once it works, I will port to neo-go.

**Comment by roman-khimov** [comment]
It's OK, I just think that NeoGo is a bit easier to work with, there are more tests there and you can quickly synchronize the chain from dump. But the protocol is the same, we can start with C# implementation, some effects should be visible there as well.

**Comment by ZhangTao1596** [comment]
I have compared gas balances of https://github.com/neo-project/neo/pull/2841 on Testnet. Now I'm testing neo-go https://github.com/ZhangTao1596/neo-go/tree/optimize-vote-reward
