### ISSUE TITLE
How to invoke function on contract at specific height?

### ISSUE THREAD

**Issue by ixje** [nspcc-dev/neo-go#2857]
I'm looking to invoke functions on a contract at a specific height because the contract is destroyed later on so I can't use the standard RPC invoke methods. 

1. is there any out of the box support for this? if not, see 2.
2. how do I set up the VM with the data I fetch via `findstates`? 

    To elaborate; 
    I can obtain the NEF/manifest by getting the contract state via `findstates`, similarly I can fetch all contract storages  using `findstates`. I believe I should be able todo
    ```
	    v := vm.New()
	    v.Load(invocationScript)
    ```
    where `invocationScript` is something I manually build to do `System.Contract.Call`s. Given that the contract might read from storage I need to somehow set that up. In `neo-cli` I would provide a custom [snapshot](https://github.com/neo-project/neo/blob/ee93a8dd9a4b4fad4eb1a9a2e11ae6e06bffaf8e/src/Neo/SmartContract/ApplicationEngine.cs#L156)
 to the engine in which I store the contract state and contract storage. How do you do this with neo-go?

    This function looks interesting as well, but again I don't see how to setup the storage side
    https://github.com/nspcc-dev/neo-go/blob/4e6ce9c3e666dd3979f31287dfdffc7a773544c7/pkg/vm/vm.go#L326-L327

**Comment by AnnaShaleva** [comment]
Thank you for submitting the issue,

1. Yes, we have the historic invocation functionality implemented as an extension for both RPC server and RPC client, please, check the [RPC server doc](https://github.com/nspcc-dev/neo-go/blob/master/docs/rpc.md#invokecontractverifyhistoric-invokefunctionhistoric-and-invokescripthistoric-calls), [RPC client doc](https://github.com/nspcc-dev/neo-go/blob/v0.100.1/pkg/rpcclient/rpc.go#L629) and the [corresponding RPC Invoker](https://github.com/nspcc-dev/neo-go/blob/v0.100.1/pkg/rpcclient/invoker/invoker.go#L49). Please, note that historic functionality is not supported by the C# RPC server.
2. Our VM CLI supports test invocations on the top of a specific blockchain state with ‘-m’, ‘-t’, ‘p’ and ‘—config-path <path-to-the-node-comfig>’ flags provided to the ‘neo-go vm’ CLI command, please, check the output of the ‘neo-go vm —help’. Our VM CLI supports the historic test invocations on the top of the blockchain state of the specified height as far with the help of ‘—historic <height>’ flag. Please, check the output of the ‘loaddeployed’ VM CLI command for the described case.

**Comment by ixje** [comment]
Unfortunately I need this to also work with the C# node so option 1 seems to drop off then. 

As for option 2, if I'm not mistaken (my golang knowledge is pretty new) this requires to have a synced chain locally that it can 'rollback', right? For my use-case I need to do this all in-memory without running a node or having a local chain. Meaning;
- obtain contract state and storage over RPC for height `x` using the `findstates` RPC call
- setup VM in memory and execute a script to call a few methods on the contract to obtain the results
  - note: it's safe to assume that the contract will not call any other contracts internally
- keep results, discard the VM

With a bit of digging I think this is what I'm looking for

- create a `dao.Simple` (with [InMemory](https://github.com/nspcc-dev/neo-go/blob/1426b54fd7ddc69d28adc53f5bca0c64a6e0d42e/pkg/core/storage/dbconfig/store_type.go#L10) as storage, instead of leveldb/boltdb)
   - call `PutStorageitem` for all contract storages I retrieved from the stateservice
   - use `Put` to store the contract itself (yet to confirm and figure out the key and data format)
- create an [interop.Context](https://github.com/nspcc-dev/neo-go/blob/389bdfd1b620916587368b6b0aa51e48c433b34a/pkg/core/interop/context.go#L47) with the configured dao from the previous step
   - can I ignore the `Chain` field or will all hell break loose then?
- obtain `vm` instance via [context.SpawnVM](https://github.com/nspcc-dev/neo-go/blob/389bdfd1b620916587368b6b0aa51e48c433b34a/pkg/core/interops.go#L26), load my script and run()

Does that sound about right? Please let me know if I'm missing something/should be careful with some parts or if I'm completely looking in the wrong direction :pray: 

Thanks!

**Comment by ixje** [comment]
I've got something cooked up that seems to work, leaving it here in case somebody wants to do the same
```go
	client, err := rpcclient.New(context.TODO(), "http://127.0.0.1:20332", rpcclient.Options{})
	if err != nil {
		return err
	}

	// get contract state (& NEF)
	stateResponse, err := client.GetStateRootByHeight(height)
	if err != nil {
		return err
	}
	managementContract, err := util.Uint160DecodeBytesBE([]byte(management.Hash))
	if err != nil {
		return err
	}
	prefix := append([]byte{0x08}, hash.BytesBE()...)
	states, err := client.FindStates(stateResponse.Root, managementContract, prefix, nil, nil)
	if err != nil || len(states.Results) != 1 {
		return err
	}
	si, err := stackitem.Deserialize(states.Results[0].Value)
	if err != nil {
		return err
	}

	siArr, _ := si.(stackitem.Item)
	var contractState state.Contract
	err = contractState.FromStackItem(siArr)
	if err != nil {
		return err
	}

	var contractGetter = func(_ *dao.Simple, h util.Uint160) (*state.Contract, error) {
		if h.Equals(contractState.Hash) { 
			return &contractState, nil
		}
		return nil, errors.New("not found")
	}
	fc := NewFakeChain()
	d := dao.NewSimple(storage.NewMemoryStore(), false, false)
	// TODO: insert contract storage
	ic := interop.NewContext(trigger.Application, fc, d,
		interop.DefaultBaseExecFee, native.DefaultStoragePrice, contractGetter, nil, nil, nil, nil, nil)
	v := core.SpawnVM(ic)

	w := io.NewBufBinWriter()
	emit.Opcodes(w.BinWriter, opcode.NEWARRAY0) // need to push empty args or panics
	emit.AppCallNoArgs(w.BinWriter, contractState.Hash, "symbol", callflag.All)
	v.LoadScriptWithFlags(w.Bytes(), callflag.All)
	err = v.Run()
```
the one "but" here is [NewFakeChain()](https://github.com/nspcc-dev/neo-go/blob/master/internal/fakechain/fakechain.go#L54) which comes from an internal package. I just duplicated it, perhaps it can be made public?

**Comment by roman-khimov** [comment]
`FakeChain` is an internal package that is only used in tests, it was never intended to be public. You probably can take a proper `core.Blockchain`, let it init at block 0 and then push data into its `dao.Simple`. Still, I'm not sure you'll get exactly the state needed (like `Blockchain.Reset()` does), there won't be blocks/transactions which may affect contract.

**Comment by roman-khimov** [comment]
More like `bc, err := core.NewBlockchain(...)`, but yes, it'll init properly with the config given at block 0 and then you can use `bc.GetTestVM()` (block can omitted there, transaction should contain a script you want to run).

**Comment by ixje** [comment]
Thanks for the hints. I'll consider the main issue done
