### ISSUE TITLE
Use `Required` flag for CLI parameters where needed

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#2861]
See #2852, we can simplify some code by relying on `Required` flag (remove error checks), but a thorough review of whole CLI command set is needed.

**Comment by AnnaShaleva** [comment]
We've tried with #3278, and turns out that `Required` functionality of `urfave/cli` not completely suits our needs. See the [comment](https://github.com/nspcc-dev/neo-go/pull/3278#issuecomment-1869444068). Thus, we're closing this issue in favour of https://github.com/nspcc-dev/neo-go/issues/3097.

**Comment by AnnaShaleva** [comment]
There's a way to validate flags with the new version of `urfave/cli`, ref. https://github.com/nspcc-dev/neo-go/issues/3097#issuecomment-2191090318, we can combine `Recuired` functionality with validation to reach our goal.
