### ISSUE TITLE
`Password` in CLI's configuration files

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neo-go#2883]
Some `neo-go` CLI commands allow fetching run parameters via a config file (`--wallet-config` flag). [Password](https://github.com/nspcc-dev/neo-go/blob/0c43b1ddca2f18fb1914a5b52bd334820e8dbf2e/pkg/config/wallet_config.go#L6) is one of such params. However, `neo-go wallet import` command [ignores](https://github.com/nspcc-dev/neo-go/blob/0c43b1ddca2f18fb1914a5b52bd334820e8dbf2e/cli/wallet/wallet.go#L623) it. It could be used instead of the `"Enter new password > "` prompt for a new account creation OR instead of the `"Enter password > "` prompt for NEP-2 strings decryption.

Useful for automation. Other commands may be improved too, did not check.

**Comment by roman-khimov** [comment]
WIF passwords should be accepted without any additional questions. NEP-2 can be tried it it matches the configured password.
