### ISSUE TITLE
listen RPC with StartWhenSynchronized on the first start

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neo-go#2888]
if RPC StartWhenSynchronized is true, neogo should listen RPC port on the first start

**Comment by roman-khimov** [comment]
I'm not sure I get the idea. `StartWhenSynchronized` means "start when the node is synchronized as per conditions from https://pkg.go.dev/github.com/nspcc-dev/neo-go/pkg/network#Server.IsInSync". It may take some time for the node to get to starting RPC. If you want it to start unconditionally, set this option to `false`.

**Comment by 532910** [comment]
I don't want to start them unconditionally. It's impossible to deploy alphabet contracts if contracts are not deployed yet, with this option enabled.

**Comment by 532910** [comment]
it is not true, my fault
