### ISSUE TITLE
Error running peerEOF in dev branch

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#289]
Regression after several merges in #283, the node doesn't connect properly giving an error:
```
Server is starting up
Connection manager started
We have connected successfully to:  localhost:20334
Error running peerEOF
Server has stopped from the following error:  there are no available peers to interact with
```

**Comment by anthdm** [comment]
Is someone already on this issue? Otherwise, I can take a look at it today. @roman-khimov @volekerb

**Comment by volekerb** [comment]
> Is someone already on this issue? Otherwise, I can take a look at it today. @roman-khimov @volekerb

yeah, I'm working on this one
issue happens on this line:
https://github.com/nspcc-dev/neo-go/blob/dev/pkg/peermgr/peermgr.go#L175
Leeds to
" unreadable: protocol error E08 during memory read for packet $m1,8"

**Comment by anthdm** [comment]
@volekerb Ok great, thanks for the fast reply

**Comment by volekerb** [comment]
This looks not relevant anymore
