### ISSUE TITLE
RPC wrapper's method calling the one which returns `any` does not compile

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neo-go#2898]
I used this simple contract with single method for testing:
```yaml
name: "Example"
safemethods: ["greet"]
```
```go
// Greet just greets you.
func Greet(name string) interface{} {
	if len(name) == 0 {
		name = "Stranger"
	}

	return "Hello, " + name + "!"
}
```

As we can see it returs single value of type `interface{}` (later `any`).

I've compiled the contract via corresponding Neo Go CLI utility:
```shell
$ neo-go contract compile -i contract.go -c config.yml -o contract.nef -m manifest.json --bindings models.yml
```

After that `models.yml` file looks like this:
```yaml
package: example
hash: "0x0000000000000000000000000000000000000000"
overrides:
    greet: interface{}
    greet.name: string
```

Then I've generated RPC wrappers:
```shell
$ neo-go contract generate-rpcwrapper -c models.yml -m manifest.json -o models.go --hash 0x0000000000000000000000000000000000000000
```

Generated models.go file can not be compiled. Here is a problem function:
```go
// Greet invokes `greet` method of contract.
func (c *ContractReader) Greet(name string) (stackitem.Item, error) {
	return func (item stackitem.Item, err error) (stackitem.Item, error) {
		if err != nil {
			return nil, err
		}
		return item.Value(), nil // any doesn't implement stackitem.Item
	} (unwrap.Item(c.invoker.Call(Hash, "greet", name)))
}

```

Of course, in this simple case I could just return value of type `string`. Abstracting from the function body - how legitimate is it to return `any` value?

Could you guys please help me with this case? I'm also interested in backward compatibility of changing return type of the method to `string` in this example.

**Comment by roman-khimov** [comment]
> how legitimate is it to return any value?

It's OK, it'll be `Any` in the manifest. It's just that we should have `(interface{}, error)` returned from wrapper's `Greet()`.
