### ISSUE TITLE
stackitem.Deserialize with custom limits

### ISSUE THREAD

**Issue by ixje** [nspcc-dev/neo-go#2899]
I'm looking for a workaround for this issue https://github.com/neo-project/neo/issues/2845 and a simple doubling of the limit would already be sufficient for my use-case, except I can't manually set it. It can be as simple as making this public (I think that would work at least)

https://github.com/nspcc-dev/neo-go/blob/bd26b9db8307567e77154d7a2fe17203b90b655b/pkg/vm/stackitem/serialization.go#L40-L44

It that an option?

**Comment by roman-khimov** [comment]
We've workarounded this problem by ignoring contracts that can't be deserialized, but for some special cases like this maybe we can expose it. We have `SerializationContext` exported already (but it's not exactly symmetric to `deserContext`). @AnnaShaleva?

**Comment by ixje** [comment]
Any updates?

**Comment by AnnaShaleva** [comment]
Oh, sorry, I've missed the GitHub notification, let me check it.
