### ISSUE TITLE
Import compiler changes from neo-storm

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#290]
As discussed in CityOfZion/neo-storm#64, we need to move changes made there back into neo-go.

**Comment by anthdm** [comment]
@roman-khimov We only need the compiler package, however, some parts are closely correlated with the VM package. That will need some cherry-picking shenanigans though

**Comment by roman-khimov** [comment]
Yeah, I do see it now, things like Opcode/Instruction differences make it a little bit more involved than I expected initially, but not impossible.
