### ISSUE TITLE
NNS-contract `Resolve` return types 

### ISSUE THREAD

**Issue by masterSplinter01** [nspcc-dev/neo-go#2900]
Method of nns-contract `Resolve`  returns `[]string`
https://github.com/nspcc-dev/neofs-contract/blob/master/nns/nns_contract.go#L444
```
// Resolve resolves given name (not more then three redirects are allowed).
func Resolve(name string, typ RecordType) []string {
	ctx := storage.GetReadOnlyContext()
	return resolve(ctx, nil, name, typ, 2)
}
```
`Neo-go` wrapper `Resolve` requires one `string`
https://github.com/nspcc-dev/neo-go/blob/master/pkg/rpcclient/nns/contract.go#L59
```
// Resolve resolves the given record type for the given domain (with no more
// than three redirects).
func (c *ContractReader) Resolve(name string, typ RecordType) (string, error) {
	return unwrap.UTF8String(c.invoker.Call(c.hash, "resolve", name, int64(typ)))
}
```
Comment to `unwrap.UTF8String(...)
```
// UTF8String expects correct execution (HALT state) with a single stack item
// returned. A string is extracted from this item and checked for UTF-8
// correctness, valid strings are then returned.
```
Is it sure it is valid?

**Comment by roman-khimov** [comment]
It's made to be compatible with the mainnet NNS: https://github.com/neo-project/non-native-contracts/blob/8d72b92e5e5705d763232bcc24784ced0fb8fc87/src/NameService/NameService.cs#L400

I don't think we can have NeoFS version of NNS right in the NeoGo, it'll have wrappers in neofs-contracts.

**Comment by AnnaShaleva** [comment]
Actually, #2693, #2687 and https://github.com/nspcc-dev/neofs-contract/pull/266 are about to change this and unify the NNS implementation through the neofs-contract and neo-go.

**Comment by roman-khimov** [comment]
They solve a bit different problem. NeoGo _must_ be compatible with the mainnet NNS.
