### ISSUE TITLE
Is "about" correct?

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neo-go#2902]
What does it mean "Go Node"? "Гошная нода"? Выглядит как калька с русского.
Во вторых, что важнее, язык, на котором написана программа или что это такое?
Кажется, что во первых это узел Neo блокчейна и во-вторых он на го: "NEO blockchain Node and SDK in Go."

**Comment by roman-khimov** [comment]
5b9578db5d930701d0dcef104ccebe3355edf0dd
