### ISSUE TITLE
rpc.GetPeers() UnmarshalTypeError

### ISSUE THREAD

**Issue by ixje** [nspcc-dev/neo-go#2910]
calling this on `https://mainnet1.neo.coz.io:443`
```
	peers, err := c.GetPeers()
	if err != nil {
		return
	}
```
results in 
![image](https://user-images.githubusercontent.com/6625537/218072491-9673e186-de3b-44e0-be08-2ff1c455d298.png)

**Comment by roman-khimov** [comment]
int vs string for port. I don't know why this happens again and again.
