### ISSUE TITLE
Allow retrieving RPC client endpoint

### ISSUE THREAD

**Issue by ixje** [nspcc-dev/neo-go#2912]
I'm working with multiple clients (primary and a backup) which get passed down some functions and at some point I want to log some failure information. Right now I can't tell what data source the client is using unless I pass the information down through all calls just for logging.

Would it be possible to make this public or retrievable?
https://github.com/nspcc-dev/neo-go/blob/1d6e48ee78e5cf911065b561006c6235b31126bb/pkg/rpcclient/client.go#L34

**Comment by roman-khimov** [comment]
`Endpoint() string`, I think.

**Comment by ixje** [comment]
That will do :+1:
