### ISSUE TITLE
Clarify "not found" return of `StateRoot.FindStates`

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neo-go#2925]
I suggest to clarify in docs what exactly `StateRoot.FindStates` returns in "not found" case - empty result w/o an error or the particular error. I already fell for it once. In current implementation `mpt.ErrNotFound` (https://pkg.go.dev/github.com/nspcc-dev/neo-go@v0.101.0/pkg/core/mpt#pkg-variables) is returned, which is what it is intended for, but it's not obvious from the `FindStates` itself, so I can't confidently rely on it. 

* https://pkg.go.dev/github.com/nspcc-dev/neo-go@v0.101.0/pkg/core/stateroot#Module.FindStates
* https://pkg.go.dev/github.com/nspcc-dev/neo-go@v0.101.0/pkg/core#StateRoot (but it doesn't have docs at all)

**Comment by roman-khimov** [comment]
I guess you're confused about the difference between _internal_ `stateroot` module API and external RPC API. The difference comes from #2863, RPC API is just the way it is in C# node, but internally we have this error and I think it's useful.

**Comment by cthulhu-rider** [comment]
> but internally we have this error and I think it's useful

Yeah, I'm OK with the error, and realize possible discrepancies between different layers. Just suggest to document return on the spot for clarity.
