### ISSUE TITLE
Actualize docs of DB config in code

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neo-go#2931]
Following docs about supported types of DBs in https://pkg.go.dev/github.com/nspcc-dev/neo-go@v0.101.0/pkg/core/storage/dbconfig#DBConfiguration led me to error
```
unknown storage: boltDB
``` 

I guess https://pkg.go.dev/github.com/nspcc-dev/neo-go@v0.101.0/pkg/core/storage/dbconfig#pkg-constants are valid set. Pay attention to `inmemory`.

**Comment by roman-khimov** [comment]
Some reference is needed.
