### ISSUE TITLE
`core.Blockchain` is used apart from docs in `node` command

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neo-go#2944]
_Inspired by https://github.com/nspcc-dev/neofs-node/pull/2277#discussion_r1144641597_

[`SetNotary`](https://pkg.go.dev/github.com/nspcc-dev/neo-go@v0.101.1/pkg/core#Blockchain.SetNotary) (and several other) method is required to be called before [`Run`](https://pkg.go.dev/github.com/nspcc-dev/neo-go@v0.101.1/pkg/core#Blockchain.Run).

`node` command doesn't follow this requirement:
* [`here`](https://github.com/nspcc-dev/neo-go/blob/7306beca4ddc013157027ca0de35686c2dd0c538/cli/server/server.go#L455) blockchain is instantly run
* [`later`](https://github.com/nspcc-dev/neo-go/blob/7306beca4ddc013157027ca0de35686c2dd0c538/cli/server/server.go#L476) blockchain is modified

The code must be put in order according to the documentation in order to avoid potential breakdowns. While everything looks clear for a cold start, further [processing](https://github.com/nspcc-dev/neo-go/blob/7306beca4ddc013157027ca0de35686c2dd0c538/cli/server/server.go#L538) of runtime signals may require more in-depth logic.

### P.S.
In general, I think that it may not always be convenient to restrict the use of a type at the documentation level (as here, when nothing obviously breaks). A much better solution would be to change the type system. For example, accepting all necessary components in the constructor and not providing setters for them, or separating basic independent subtypes and reusing them between existing ones. This will reduce type cohesion at the instance lifetime level. But this is a refactoring.

**Comment by roman-khimov** [comment]
We have to support dynamic notary service change because there is a USR1 handler that should do that (and it's doing this incorrectly in fact now in that `SetNotary(new_service)` is completely missing.

**Comment by AnnaShaleva** [comment]
> Inspired by https://github.com/nspcc-dev/neofs-node/pull/2277#discussion_r1144641597

It's completely my bad, I thought that there are some consurrency issues, but after careful review of all our services it looks like there can't be any concurrency issues.

>  support dynamic notary service change

In fact, it is already supported. And you did everything right when designing our services reloading on SIGUSR1.

> SetNotary(new_service) is completely missing

It's not missing, it's just hidden under `mkP2PNotary(...)` call.

**Comment by roman-khimov** [comment]
> And you did everything right

Well, that happens too from time to time.
