### ISSUE TITLE
Add missing RPC wrappers for native contracts

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#2949]
These contracts are StdLib, CryptoLib, Ledger, Designation. They are quite simple, but currently we don't have RPC Client wrappers for them (Actor/Invoker). Probably someone will need it.

**Comment by roman-khimov** [comment]
They were omitted intentionally. StdLib and CryptoLib have no state, they're to be used by contracts and it's hard to imagine some backend calling them directly (unless it's some kind of debug). Ledger does have a state, but for all components of it we have some specific RPC methods. Role management contract in fact does have a wrapper (rolemgmt).

**Comment by AnnaShaleva** [comment]
OK, then we may close this.
