### ISSUE TITLE
Add `getrawnotaryrequestpool` RPC extension

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#2951]
A topic for discussion: I'd suggest to introduce one more extension - `getrawnotaryrequestpool` RPC API. We have notary pool subscriptions, but it's not enough for debugging some unexpected things that may happen while submitting notary requests. Related to #2950.

@roman-khimov, what do you think?

**Comment by roman-khimov** [comment]
`getrawnotarypool`? Makes sense.

**Comment by AnnaShaleva** [comment]
The same `result.RawMempool` structure can be used as a response to the `getrawnotarypool`. `Verified` field should contain all current content of network server's notary request pool which is effectively the set of hashes of currently added fallback transactions. `Unverified` field should contain nothing. One principal difference from the `getrawmempool` here is that with `getrawmempool` we can request some transaction that we're interested in via `getrawtransaction`. Thus, I'm suggesting adding one more `getrawnotaryrequest` RPC handler so that notary requests can be retrieved by the RPC client. @roman-khimov?

These APIs should be dependent on `P2PSigExtensionsEnabled` config setting. These APIs should be supported by the NeoGo RPC client. `getrawnotaryrequest` should accept the same parameters as `getrawtransaction` and should respond either with raw (serialized) notary request or JSON-serialized (verbose) representation of notary request.

One potential problem I see here is that the users of `getrawnotarypool` are probably interested in main transactions and don't aware of the fallbacks (consider the case of reloaded NeoFS alphabet node). And the unique notary request identifier is a hash of fallback transaction. Thus, responding with the set of currently added fallback hashes may be not very convenient for the user, as the next step he'd probably desire to perform is to retrieve each notary request to take a look at the main transaction. Thus, we may probably have to think about adding the set of main transaction hashes to the `getrawnotarypool` as far. @roman-khimov, what do you think?

**Comment by roman-khimov** [comment]
The main use case for these is:
 * `getrawnotarypool` to get a list of current notary transactions
 * iterate over the list, retrieve main transactions, check their contents and act accordingly

Fallbacks are more interesting in case of debugging. Valuable, but less critical.

Maybe we can respond with
```
{
    "main_hash_1": ["fallback_hash_1", "fallback_hash_2",..],
    "main_hash_2": ["fallback_hash_1", "fallback_hash_2",..]
}
```
Direct `getrawmempool` compatibility is not a goal for us, it doesn't fit well (verified/unverified split is a C# node implementation detail, while main-fallback relation is important for the notary pool).

Then the question about `getrawnotaryrequest` is also relevant, but it's more like `getrawnotarytransaction` which can be done both for main and fallback. But that'd be transactions, not a complete notary request (which differs only in additional witness, do we care about it?).

**Comment by AnnaShaleva** [comment]
> Maybe we can respond with
>{
>    "main_hash_1": ["fallback_hash_1", "fallback_hash_2",..],
>     "main_hash_2": ["fallback_hash_1", "fallback_hash_2",..]
>}
Yes, I like it, let's do this, it will be helpful for those who search for both follbacks and mains.

> `getrawnotarytransaction` which can be done both for main and fallback

Let's do this as far, I don't really think that anyone needs NotaryRequest witnesses.
