### ISSUE TITLE
Fix errcheck warnings from emit* functions

### ISSUE THREAD

**Issue by volekerb** [nspcc-dev/neo-go#297]
During the merge of cherrypicks from neo-storm #292 there were found several "Error return value of X not checked" which is hard to fix in one shot.
https://golangci.com/r/github.com/nspcc-dev/neo-go/pulls/292
Here is the full list of them:
- [ ] Error return value of compiler.CompileAndInspect is not checked (from errcheck) | smart_contract.go | compiler.CompileAndInspect(src)
- [ ] Error return value of emitOpcode is not checked (from errcheck) | codegen.go | emitOpcode(c.prog, vm.DUPFROMALTSTACK)
- [ ] Error return value of emitOpcode is not checked (from errcheck) | codegen.go | emitOpcode(c.prog, vm.PICKITEM)
- [ ] Error return value of emitOpcode is not checked (from errcheck) | codegen.go | emitOpcode(c.prog, vm.DUPFROMALTSTACK)
- [ ] Error return value of emitJmp is not checked (from errcheck) | codegen.go | emitJmp(c.prog, vm.JMPIFNOT, int16(lElse))
- [ ] Error return value of emitJmp is not checked (from errcheck) | codegen.go | emitJmp(c.prog, vm.JMP, int16(lElseEnd))
- [ ] Error return value of emitJmp is not checked (from errcheck) | codegen.go | 
emitJmp(c.prog, vm.JMPIFNOT, int16(len(c.l)-1))
- [ ] Error return value of emitInt is not checked (from errcheck) | codegen.go | 
emitInt(c.prog, int64(i))
- [ ] Error return value of emitCall is not checked (from errcheck) | codegen.go | 
emitCall(c.prog, vm.CALL, int16(f.label))
- [ ] Error return value of EmitCall is not checked (from errcheck) | emit_test.go | 
EmitCall(buf, JMP, 100)
- [ ] Error return value of EmitOpcode is not checked (from errcheck) | vm_test.go | 
EmitOpcode(buf, RET)

**Comment by roman-khimov** [comment]
I think it should be fixed in a more generic way, all of `emit*` invocations (and there are lots of them) should be fixed, not just ten of them.

**Comment by volekerb** [comment]
Yup, I do agree with that. But at least mentioned should be fixed.

**Comment by volekerb** [comment]
@roman-khimov the only thing I'm not quite sure about is whether we should handle error in codegen#visit with logging or just gather all the possible error to some []err and after visit called throw it up.

**Comment by roman-khimov** [comment]
You can save an error in `codegen` state, check for it in `Visit` to return `nil` immediately (to not continue walking) and then check for it in `convertFuncDecl` and act accordingly (probably return an error, because you can change signature of this function, which is easily propagated then in an error return from `CodeGen`).
