### ISSUE TITLE
feature request: --config-file option to start node

### ISSUE THREAD

**Issue by ixje** [nspcc-dev/neo-go#2978]
The "feature" was discussed here https://github.com/nspcc-dev/neo-go/issues/2874#issuecomment-1381558863 and the time has come that I'm actually missing this (I'm planning to wrap `neo-go` so I can drop the need for `neo-express` to run examples with `neo-mamba`).

**Comment by AnnaShaleva** [comment]
It's a nice feature. Francly speaking, I've faced with the same problem while debugging several custom private networks with different configs, so it would be nice just to specify a custom config file on start.

**Comment by ixje** [comment]
🎉
