### ISSUE TITLE
notary: Example deposit code is currently unworkable

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neo-go#2987]
I try to make notary deposit using https://pkg.go.dev/github.com/nspcc-dev/neo-go@v0.101.1/pkg/rpcclient/nep17#TokenWriter.Transfer.

I used https://pkg.go.dev/github.com/nspcc-dev/neo-go@v0.101.1/pkg/rpcclient/notary#OnNEP17PaymentData as extra GAS transfer data which conveniently groups parameters. This is also used in https://pkg.go.dev/github.com/nspcc-dev/neo-go@v0.101.1/pkg/rpcclient/notary#pkg-examples.

Sad thing that `Transfer` method doesn't support `OnNEP17PaymentData` type. I realize that example skip error conditions but I'd expect code to be usable in good conditions.

**Comment by roman-khimov** [comment]
`emit.Array` needs to support some interface that can be implemented by structures like this one (`stackitem.Convertible`?). Related to #2891.
