### ISSUE TITLE
Attach binaries to releases for release builds

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#3001]
I'm not entirely sure, but I think it should be possible. Currently @sami-nspcc is able to push complete releases to projects like neofs-node or gateways, with comments and assets. We create release tags manually, but maybe we can make release build (that is triggered already) push binaries to the release itself automatically (like it pushes Docker images).

**Comment by AnnaShaleva** [comment]
It's possible, there's an uploading action https://github.com/actions/upload-release-asset, let's try it out with 0.102.0.

**Comment by AnnaShaleva** [comment]
Would you like to keep the current manual way of release creation?

**Comment by roman-khimov** [comment]
Yes, manual tagging and pushing tags from CLI doesn't look right to me, we're OK here, it's just that manually waiting/downloading/attaching binaries is boring.
