### ISSUE TITLE
Document supported/unsupported by compiler go 1.18/1.19/1.20 features

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#3023]
Our compiler is able to handle `any` alias, but isn't able to handle generics (hi, https://github.com/nspcc-dev/neo-go/issues/2376). We need to document this behaviour (probably, there's something else that should be mentioned in this section) and keep the documentation up-to-date.

**Comment by roman-khimov** [comment]
`any` is likely to be treated the same way as any other alias, so we may mention some status wrt type alias support in general.

**Comment by AnnaShaleva** [comment]
We need to write a couple of lines about unsupported generics in the `Language compatibility` section.

**Comment by roman-khimov** [comment]
We've got Go 1.21 now, so the list can be extended. At the same time we've got #3090, #3091 and #3092, so some of these things will be fixed.
