### ISSUE TITLE
Restrict maximum size of ObjectHead Oracle NeoFS response

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#3025]
The problem is described at https://github.com/nspcc-dev/neofs-api/issues/171#issuecomment-1566908300 and similar to https://github.com/neo-project/neo-modules/pull/803. Currently the size of received object header isn't restricted in any way, `getHeader` and `getHash` Oracle NeoFS protocol methods are affected. See the usages of `getObjHeader`:
https://github.com/nspcc-dev/neo-go/blob/871ee1898128377936a935165be0892297a8b1b0/pkg/services/oracle/neofs/neofs.go#L162-L176

**Comment by roman-khimov** [comment]
To be fixed by https://github.com/nspcc-dev/neofs-api/issues/262, nothing to do on NeoGo side.
