### ISSUE TITLE
Define new Project and Close Q1 Project

### ISSUE THREAD

**Issue by volekerb** [nspcc-dev/neo-go#304]
New to decide whether we will use milestones or projects. In case of project we have to create new one and define timeline/tag name/version.
At the same time there are several open issues still open in Q1 Project. They could be moved to our next project.

**Comment by roman-khimov** [comment]
Throwing some links in there:
https://stackoverflow.com/questions/39591795/what-is-the-difference-relationship-between-github-projects-and-milestones
https://help.github.com/en/articles/about-milestones
https://help.github.com/en/articles/about-project-boards

IMO all of these Q1/2/3 projects don't make much sense for a project like this one (that can potentially make several releases per month). What makes sense is versioned release schedule and some longer-term roadmap. Now how to use Github's milestones/projects for that is another problem that I don't have any strong opinion on at the moment.

**Comment by roman-khimov** [comment]
One idea that I have is to use milestones as a substitute for epics (like "implement all VM opcodes") and then use project as a higher level tool tracking releases (one release --- one "project"). Anything longer term just gets written into the roadmap. But that's just an idea at the moment and I'm not yet sure that it's the best way to manage things in Github.

**Comment by roman-khimov** [comment]
At the same time it looks like milestones are more frequently used to track releases, not features. And `neo-python` does something completely opposite to my suggestion --- use milestones for releases and projects for epics.

We can also just use milestones and not use projects at all. Or the other way around for more fun. I don't see any reasonable best current practice really and the options are so similar that it's hard to choose.

**Comment by roman-khimov** [comment]
Take go itself as an example, huge project, no "projects" at all, just plain versioned milestones:
https://github.com/golang/go/issues

**Comment by volekerb** [comment]
> Take go itself as an example, huge project, no "projects" at all, just plain versioned milestones:
> https://github.com/golang/go/issues

True, it could be because Projects in Github appeared in 2016 but Go development started before that. Anyway there are several ways to manage issues.
For Project I see advantage with having Kanban board. With milestone  -- overall progress bar.

For me any of these approaches working well. Just want to choose one and go with it / set up current tasks with selected approach.

**Comment by roman-khimov** [comment]
I guess the lowest common denominator is plain and simple milestones for versions, no "projects" at all and making some task lists (like https://github.blog/2014-05-14-nested-task-lists/) where appropriate (epics like VM opcodes). As this is a community project, we're better stick with things everybody understands as @realloc pointed out.

Not having any real project management tools --- isn't it fun, huh? Let's wait a day or two for other comments before making changes.

**Comment by volekerb** [comment]
Waiting for one more day for comments.
As a solution I believe we will have .md file added to code style guidelines with finalized decision.

**Comment by roman-khimov** [comment]
BTW, looking at releases here and CircleCI configs/makefiles it looks like there was an automated release process which I think we won't support (releases should mean something for a package like this, not just be an automated code push). Also, we've got a lot of tags that don't follow the `vX.Y.Z` convention, that will stay as is, but newer releases should tagged with this in mind.

**Comment by roman-khimov** [comment]
Linking #312 here as it changes versioning which is tightly coupled with milestones and tags. I think we can now:
 * remove "projects" support from project's settings
 * settle on semver adoption for a project
 * settle on using milestones to track future versions development
 * set the next version to be 0.5.0 (to signify project changes, the last one was 0.44.10)
 * create `v0.5.0-pre` tag for `git describe --tags` to give us proper versions as per semver
 * fix the script in #312 to properly handle such tags
 * add `v0.5.0` milestone

Releasing would mean just tagging with `v0.5.0` and rebuilding the thing. Then adding `v0.5.1-pre` (or whatever else) to the next commit in the repo.

**Comment by volekerb** [comment]
remove "projects" support from project's settings Done

**Comment by volekerb** [comment]
> * fix the script in #312 to properly handle such tags
Am I right that it will fix issue with not displayed tag on the main github page?

**Comment by roman-khimov** [comment]
I think that will be properly displayed only after the 0.5.0 release (and `v0.5.0` tag), but who knows.

**Comment by roman-khimov** [comment]
I've created `v0.5.0` milestone and `v0.5.0-pre` tag.

**Comment by roman-khimov** [comment]
Closing this one, I think we're done here.
