### ISSUE TITLE
Can't use --config-file with release binary?

### ISSUE THREAD

**Issue by ixje** [nspcc-dev/neo-go#3050]
So I just tried to update from `0.100.2-pre-12-g584675ec` to `0.101.2` and was hoping to use https://github.com/nspcc-dev/neo-go/pull/3014

despite seeing the code in the source 
https://github.com/nspcc-dev/neo-go/blob/abb58fb7de6053dc9734b5acfa334870481b6110/cli/server/server.go#L88

the binary I downloaded from the latest release doesn't give me the option
```
erik@erik-linux:~/code/neo-go-node$ ./neo-go --version
NeoGo
Version: 0.101.2
GoVersion: go1.19.10
erik@erik-linux:~/code/neo-go-node$ ./neo-go node -h
NAME:
   neo-go node - start a NeoGo node

USAGE:
   neo-go node [--config-path path] [-d] [-p/-m/-t]

OPTIONS:
   --config-path value  path to directory with configuration files
   --privnet, -p        use private network configuration
   --mainnet, -m        use mainnet network configuration
   --testnet, -t        use testnet network configuration
   --debug, -d          enable debug logging (LOTS of output, overrides configuration)
```

If I build it from source then it does exist
```
erik@erik-linux:~/code/neo-go$ ./bin/neo-go node -h
NAME:
   neo-go node - start a NeoGo node

USAGE:
   neo-go node [--config-path path] [-d] [-p/-m/-t] [--config-file file]
```

**Comment by roman-khimov** [comment]
It's not included in this release, see change log for details. 0.101.2 was a bit of emergency one, so it doesn't have many of the things from master. This particular feature will be a part of 0.102.0.

**Comment by ixje** [comment]
ah thanks for explaining. I'll just run from source then
