### ISSUE TITLE
RPC server responds with plain/text content-type instead of application/json on error

### ISSUE THREAD

**Issue by ixje** [nspcc-dev/neo-go#3075]
When requesting the applicationlog of a transaction that has not yet persisted it is expected to get an error response. Neo-go gives an error, but instead of the `content-type` being set to `application/json` it is set to `text/plain; charset=utf-8`. The C# implementation does return `application/json` as `content-type`. 

In my specific case I use a RPC library which will auto convert the JSON response to a native dictionary type, but throws an exception because the content-type is wrong. Undoubtedly there's other libraries that will do the same, hence it might be worth fixing?

**Comment by roman-khimov** [comment]
The response is JSON, therefore `application/json` is applicable.

**Comment by ixje** [comment]
I understand it can be parsed as json. But as said, if the library you're using does `content-type` checking then it fails.

**Comment by AnnaShaleva** [comment]
We set `application/json` after error response processing, it's definitely a bug:
https://github.com/nspcc-dev/neo-go/blob/3bbb21bf8f388dc291fd8c02a996231b6be9fa20/pkg/services/rpcsrv/server.go#L2864-L2870

**Comment by roman-khimov** [comment]
CORS is affected as well, btw.
