### ISSUE TITLE
Check and convert private fields of RPC binding structures to public

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#3083]
Resulting exported RPC binding structures must not contain private fields. This issue includes two tasks:
1. Check exported structures of the source contract code and convert all private names to exported ones.
2. If generating RPC binding not from the Go code, then ensure that all private fields declared in the contract manifest must successfully be converted to the public ones.

Ref. https://github.com/nspcc-dev/neofs-contract/blob/84ff5d244f6913987c2fb7dc3e2adfb5dfa81381/rpc/container/rpcbinding.go#L27.

**Comment by roman-khimov** [comment]
Maybe 2 is sufficient? Take any (garbage) input and make something out of it?
