### ISSUE TITLE
Get timeout for antlr dependency

### ISSUE THREAD

**Issue by steven1227** [nspcc-dev/neo-go#3094]
Some user try to use neo-go and  `make env_image`, it will occur get timeout for antlr dependency

![WechatIMG13](https://github.com/nspcc-dev/neo-go/assets/9437492/4ad269d6-e177-4a05-8408-16d7681727fa)

**Comment by roman-khimov** [comment]
Does it reproduce every time you try? Have you tried some VPN? Maybe also try disabling proxy support (there is some flag for it IIRC), because that's some kind of connectivity issue not directly related to neo-go.
