### ISSUE TITLE
Support multi-call in actors

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neo-go#3101]
## Context
sometimes you need to make a group of method calls of the contract(s). At the same time, in certain situations it makes sense to make such a group call within a single transaction

current solution is to build script by one of:
1. manually via `io.BufBinWriter` and `emit` package([example](https://github.com/nspcc-dev/neofs-node/blob/04ce9e3e8a46c6cf425e9cbb5ec193b1bcb6d679/cmd/neofs-adm/internal/modules/morph/initialize_register.go#L41-L47))
2. make several `Call` method calls and concatenate resulting scripts
3. ??? mb some other one

and then call `MakeRun`.

while both approaches are working, i see 1st as too low-level and requiring deep VM knowledge while 2nd as suboptimal

## Proposal
i can suggest two APIs
1.
```go
type CallPrm struct {
  Contract util.Uint160
  Method string
  Args []any
}

func (*Actor) MultiCallScript(ps []CallPrm) ([]byte, error)
func (*Actor) MakeMultiCall(ps []CallPrm) (*transaction.Transaction, error)
func (*Actor) SendMultiCall(ps []CallPrm) (util.Uint256, uint32, error)

```
2.
```go
type ScriptBuilder struct { ... }
func (*ScriptBuilder) AddCall(contract util.Uint160, method string, args ...any)
func (*ScriptBuilder) Close() []byte 

func (*Actor)  InitScriptBuilder() *ScriptBuilder
```
P.S. mb such `ScriptBuilder` is more generic than actors and then should be placed in other package

**Comment by AnnaShaleva** [comment]
You're right, currently only 1-st way can be safely used, but I think we can consider implementing some API that is similar to `MultiTransfer` with several `call` targets. So I like the first example from your description.

**Comment by AnnaShaleva** [comment]
We've just discussed this issue, I think we may close it as unplanned.

**Comment by cthulhu-rider** [comment]
`smartcontract` package API is exactly what i was looking for, thx

**Comment by AnnaShaleva** [comment]
> `smartcontract` package API is exactly what i was looking for, thx

Take a look at the Roman's link, it suits better than `smartcontract` API. You can concat multiple calls to Builder's `InvokeMethod` or `InvokeWithAssert`.
