### ISSUE TITLE
Fix docker image

### ISSUE THREAD

**Issue by volekerb** [nspcc-dev/neo-go#311]
- Current docker config doesn't work
standard_init_linux.go:211: exec user process caused "exec format error"

- There is no documentation: https://hub.docker.com/r/cityofzion/neo-go

**Comment by volekerb** [comment]
@roman-khimov can we close this one, right? Or we closing them after release?

**Comment by roman-khimov** [comment]
If #312 fixed it then certainly we should close it, we just don't have any difference between closed and fixed states or smth like that. And it's not hard to reopen if there's a need to.

**Comment by volekerb** [comment]
Closing since even with last changes #325 was able to run it
