### ISSUE TITLE
[neotest] panic when trying to deploy contract that requests storage context in init()

### ISSUE THREAD

**Issue by ixje** [nspcc-dev/neo-go#3120]
## Current Behavior
I was trying out neotest and figured I'd try to create tests for the [nep-17 token](https://github.com/nspcc-dev/neo-go/tree/master/examples/token) in the examples folder. 

**token_test.go**
```go
package tokencontract

import (
	"testing"

	"github.com/nspcc-dev/neo-go/pkg/neotest"
	"github.com/nspcc-dev/neo-go/pkg/neotest/chain"
)

func newTokenClient(t *testing.T) *neotest.ContractInvoker {
	bc, acc := chain.NewSingle(t)
	e := neotest.NewExecutor(t, bc, acc, acc)
	c := neotest.CompileFile(t, e.CommitteeHash, ".", "token.yml")
	e.DeployContract(t, c, nil)
	return e.CommitteeInvoker(c.Hash)
}

func TestToken_Basics(t *testing.T) {
	c := newTokenClient(t)
	c.Signers = []neotest.Signer{c.NewAccount(t)}
	c.Invoke(t, "ANT", "symbol")
	c.Invoke(t, decimals, "decimals")
	c.Invoke(t, 11000000*multiplier, "totalSupply")
}
```
Trying to execute the test fail in the `DeployContract` call with the below error
```
panic: interface conversion: interface {} is nil, not storage.Context

goroutine 1 [running]:
github.com/nspcc-dev/neo-go/pkg/interop/storage.GetContext()
	/home/erik/go/pkg/mod/github.com/nspcc-dev/neo-go/pkg/interop@v0.0.0-20221202075445-cb5c18dc73eb/storage/storage.go:52 +0x5d
github.com/nspcc-dev/neo-go/examples/token.init.0()
	/home/erik/code/neo-go/examples/token/token.go:32 +0xd4
```
which is here
https://github.com/nspcc-dev/neo-go/blob/2f54f176fb54b40da1d636d8391cf694ea688d9a/examples/token/token.go#L32

## Expected Behavior
I expect no errors on deploy

## Steps to Reproduce
1. Place the above code in this folder https://github.com/nspcc-dev/neo-go/blob/master/examples/token/ in a file called `token_test.go`
2. run `TestToken_Basics`

## Your Environment

* Version used: 80fdb1c90c2693c6cf7b410c35fd3160e30283d6

**Comment by roman-khimov** [comment]
> `package tokencontract`
> 
> Place the above code in this folder https://github.com/nspcc-dev/neo-go/blob/master/examples/token/ in a file called token_test.go

Well, that's the issue and it can't be fixed. You're creating a test file in the same Go module as the contract itself and this contract has an `init()`. So when the test module is compiled it gets the same `init()` inside which can't work in non-SC context.

You can try `package tokencontract_test` though. Since you don't (and shouldn't) import the smart contract package this should work by creating a different package that doesn't have any `init()`.

**Comment by ixje** [comment]
> Well, that's the issue and it can't be fixed. You're creating a test file in the same Go module as the contract itself and this contract has an `init()`. So when the test module is compiled it gets the same `init()` inside which can't work in non-SC context.

Oh I didn't know `init()` is some special function that always gets called.

> You can try `package tokencontract_test` though. Since you don't (and shouldn't) import the smart contract package this should work by creating a different package that doesn't have any `init()`.

I tried `package tokencontract_test` but the result is the same :thinking:

**Comment by roman-khimov** [comment]
Apparently it gets compiled into the `package_test` anyway, even though it's not imported directly. Which is somewhat surprising to me, but golang/go#58823.
