### ISSUE TITLE
bad intrinsic argument during SC compilation

### ISSUE THREAD

**Issue by ixje** [nspcc-dev/neo-go#3123]
## Current Behavior
Can't compile contract

## Expected Behavior
Can compile contract

## Steps to Reproduce
1. checkout https://github.com/nspcc-dev/neo-go/commit/a6daf6a37eff8eae0b4761d5674462e36f6a17d5
2. run one of the tests in `/examples/token/tests/token_test.go`

Arguably I only changed this line because it showed as deprecated https://github.com/nspcc-dev/neo-go/commit/a6daf6a37eff8eae0b4761d5674462e36f6a17d5#diff-a74574083207be1e1e69d72b6677b424ed12b73fe530004daa4ab38195bd2fbcR17 (the `mod` update is something my IDE seemed to want)

The addition and/or removal of the `_deploy` function has no effect on the compilation error

**Comment by ixje** [comment]
This seems to be related to the `mod` updates. If I revert that it's running. Leaving it open for the moment because I don't know if that is expected behaviour or not.

**Comment by roman-khimov** [comment]
It seems to be related to the fact that you're using `v0.0.0-20230906052832-a703e545639f` interops with v0.101.4 compiler. There are some new things in the `master` that can't be compiled with 0.101.4. Try upgrading NeoGo with `go get github.com/nspcc-dev/neo-go@master` and it should work again (reverting interop should also work). Inconsistent interop/compiler versions can't really work.

Unfortunately the inner interop Go module can't use git tags appropriately, it'd be more convenient to have some vx.y.z for both, but it's not possible at the moment (and we need this module to be separated for other reasons).

**Comment by ixje** [comment]
Ok so this looks as expected behaviour.
