### ISSUE TITLE
Is it possible to force codegen for the contract type if it does not appear explicitly in the API?

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neo-go#3132]
i'm working with the Neo smart contract written in Go and trying to generate Go types to integrate the contract into the Go project. I use `neo-go compile ... --bindings <file>` + `neo-go contract generate-rpcwrapper` commands for this

## Problem
lets assume there is some exported struct that doesn't appear in the contract API explicitly: all methods return list of its intances as [`iterator.Iterator`](https://pkg.go.dev/github.com/nspcc-dev/neo-go/pkg/interop@v0.0.0-20230913081353-eb571a13564e/iterator#pkg-types). Under such conditions, used codegen doesn't create type for this structure, so i need to define and decode it manually (e.g. `FromStackItem`)

i can suppose why this happens, but maybe there's some approach to get the generate type?

## Context
`RecordState` type from the [NeoFS Name Service](https://pkg.go.dev/github.com/nspcc-dev/neofs-contract/nns) contract

i also see this [comment](https://github.com/nspcc-dev/neofs-contract/blob/d2f3761adb21de84cb9e5be8cead5fda28a0d2de/nns/recordtype.go#L6-L7) related to the contants, so i guess this question has already risen

**Comment by roman-khimov** [comment]
In general, this doesn't make sense. A contract may have 100 of internal types that are not exposed to contract callers in any way. And we'll solve iterators with #2768.

**Comment by cthulhu-rider** [comment]
ok, sounds reasonable

so, will #2768 bring https://pkg.go.dev/github.com/nspcc-dev/neofs-contract/nns#RecordState to the RPC bindings?

**Comment by roman-khimov** [comment]
Yeah, if this type is used by any iterators, it will be there. See neo-project/proposals#160 also, it supports this as well since inception.
