### ISSUE TITLE
Format Go code generated from RPC bindings

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neo-go#3133]
_Originally posted in https://github.com/nspcc-dev/neofs-contract/pull/356_

## Is your feature request related to a problem? Please describe.
Go code generated via `neo-go contract generate-rpcwrapper` command may be unformatted in terms of std Go formatting. As a result, `go fmt ./...` execution modifies generated source files (like currently in the [repo](https://github.com/nspcc-dev/neofs-contract/commit/d2f3761adb21de84cb9e5be8cead5fda28a0d2de))

## Describe the solution you'd like
format resulting Go code by the generator (e.g. using https://pkg.go.dev/go/format package functionality). This will slow down codegen a bit but will most likely go unnoticed

## Describe alternatives you've considered
as presented in the mentioned pull request: do `go fmt` manually if formatting matters in the project

## Additional context
not really a problem cuz this relates to the code style only, but following the canonical Go way would be appreciated

also pay attention to the @roman-khimov [comment](https://github.com/nspcc-dev/neofs-contract/pull/356#issuecomment-1723264724)

**Comment by roman-khimov** [comment]
`go fmt ./...` is a pretty common use case, so we better have it formatted. Doesn't cost a lot either.
