### ISSUE TITLE
EOF on attempt to `wallet import`

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neo-go#3134]
```
% neogo wallet import --wif qweqweqweqwe -w wallet.json
open wallet.json: no such file or directory
% touch wallet.json
% neogo wallet import --wif qweqweqweqwe -w wallet.json
EOF
zsh: exit 1    neogo wallet import --wif qweqweqweqwe -w wallet.json
```

???

**Comment by EdgeDLT** [comment]
Is it really a bug? [Docs](https://github.com/nspcc-dev/neo-go/blob/master/docs/cli.md#create-wallet) say you should create a wallet with `neo-go wallet init` first.

**Comment by roman-khimov** [comment]
We can improve the error message here, I think. The first one is rather obvious, the second one not so much.
