### ISSUE TITLE
Add "automatically generated" warning to RPC bindings and contract bindings

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#3139]
To let the user know that the code was generated automatically and it's not recommended to edit it manually. Ref. https://github.com/nspcc-dev/neofs-contract/issues/348, it will be useful when combining auto-generated and manually-added files in a one directory.

**Comment by AnnaShaleva** [comment]
@carpawell, subscribe! Ref. https://github.com/golang/go/issues/13560#issuecomment-277804473

**Comment by carpawell** [comment]
See https://github.com/golang/go/issues/13560#issuecomment-277804473.

**Comment by carpawell** [comment]
Accourding to https://github.com/nspcc-dev/neofs-contract/pull/367 I would say that it was done not that strict:

> The text must appear as the first line of a properly formatted Go // comment, and that comment must appear before but not be attached to the package clause and before any /* */ comment. This is similar to the rules for build tags.

Lets disscuss it in find out what we think about it.

**Comment by roman-khimov** [comment]
Will godoc fetch proper package description with this scheme?

**Comment by roman-khimov** [comment]
It was added in 0.103.0, subsequent correction is #3254.
