### ISSUE TITLE
UnlockWallet relative to config instead of node execution dir

### ISSUE THREAD

**Issue by ixje** [nspcc-dev/neo-go#3179]
## Is your feature request related to a problem? Please describe.

The config file contains a section for `Consensus` configuration. The `UnlockWallet.Path` appears to be relative to the directory where the node is started from.  I'm currently facing a problem with specifying the wallet location in a setup where the node starting directory changes, but the configuration file + wallet could (and should) stay the same. 

The configuration file and wallet file have a tight relationship, but its implementation has the relationship between the node and the wallet file, not the configuration file. Take this folder that contains all the node needs to know
```
~/data/
├── consensus_wallet.json
├── notary_wallet.json
└── protocol.privnet.yml
```

With the great `--config-file` option introduced in https://github.com/nspcc-dev/neo-go/pull/3014 I would love to be able to run the node from any working directory by simply pointing it at the config e.g.
```shell
~/node/neo-go node --config-file ~/data/protocol.privnet.yml
```
or 
```shell
~/testnode/neo-go node --config-file ~/data/protocol.privnet.yml
```
should both work.

## Describe the solution you'd like

A way of  specifying the Consensus wallet path that is not relative to the node start directory. Can be a mutually exclusive `RelativePath` field, or a cli option like `--consensus-wallet-path` that is an absolute path

**Comment by roman-khimov** [comment]
Can be an option to add prefix to relative path.

**Comment by ixje** [comment]
Can you elaborate how would that work? Do you mean something like 
```
Path: "#/cn_wallet.json"
```
where `#` means "do a relative to config search"?

**Comment by ixje** [comment]
I've trialed a variation where I added a `Relative` key in the config
```yaml
    UnlockWallet:
      Path: "wallet1_solo.json"
      Password: "one"
      Relative: true
```
and extended [config.LoadFile](https://github.com/nspcc-dev/neo-go/blob/8ed6d97085d3229d4faf56a47bbd6cf73c132a76/pkg/config/config.go#L67) with
```go
	tmp := strings.Split(configPath, "/")
	s := strings.Join(tmp[:len(tmp)-1], "/")
	uw := &config.ApplicationConfiguration.Consensus.UnlockWallet
	if uw.Relative != nil && *uw.Relative {
		uw.Path = fmt.Sprintf("%s/%s", s, uw.Path)
	}
```

That seems to do the job. The forward slash splitting probably won't work on Windows, but the general idea is simple to implement.

**Comment by roman-khimov** [comment]
Sorry, sometimes I'm rushing to answer a bit, but what I mean is more of CLI option, like `--relative-path`. Having it in the configuration doesn't seem nice to me, because in configuration file you can use absolute path and not have this problem at all. If you're not using it, likely there is a reason for that. The default behavior is expectable here and to override it we can have a CLI option. At least that's my line of thinking.

**Comment by ixje** [comment]
Understood. That can also work for me. Consider this a feature request for `--relative-path` :)

fwiw; the background story of our situation is that the `neo-go` binary will be packaged and distributed with our Python test framework (it acts as the back-end). We don't know where that will be installed and thus can't hard code an absolute path, but we do want to provide a default runnable setup out of the box.
