### ISSUE TITLE
`neorpc.Error` can not be used easily as a target in `errors.As(err, target)`

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#3188]
## Current Behavior
`neorpc.Error` can not be used easily as a target in `errors.As(err, target)`. Linter tells that:
```
govet  errorsas: second argument to errors.As must be a non-nil pointer to either a type that implements error, or to any interface type
```

Technically, that's true, because we provide a pointer to `neorpc.Err` as a target, and the `neorpc.Err` itself doesn't implement `error`.

## Expected Behavior
No linter warnings.

## Possible Solution
Define `Error()` method not on `*neorpc.Error`, but on `neorpc.Error`. Although we need to check that this solution works.

## Your Environment

* Version of the product used: 0.103.0

**Comment by roman-khimov** [comment]
That's why `errors.Is` is much more convenient. But we can't have it till C# implements proper error codes.
