### ISSUE TITLE
Allow smart contracts without separate configuration files

### ISSUE THREAD

**Issue by lock9** [nspcc-dev/neo-go#3201]
## Is your feature request related to a problem? Please describe.
It's hard for people to manage two separate files when they are building a smart contract. I was today years old when I discovered that the .yml file in the examples folder was not generated. 

## Describe the solution you'd like
Instead of maintaining a separate configuration file, I would prefer to set this information inside .go file. On neo3-boa, we use an annotation to identify the method responsible for returning the 'configuration information'. https://github.com/CityOfZion/neo3-boa/blob/374916bbc087c8ca909c67ca20dfbcd6a58c64ae/boa3/builtin/compile_time/__init__.py#L166

I was wondering if Neo Go could support something similar. The main goal is to avoid having a separate config file.

## Don't forget to add labels!
- Smart Contract Compiler
- Enhancement

**Comment by roman-khimov** [comment]
Duplicates #1038, see https://github.com/nspcc-dev/neo-go/issues/1038#issuecomment-758531876, there are no annotations in Go.

**Comment by lock9** [comment]
Hello @roman-khimov,
There is a big difference between these two issues.

That issue is about automatically generating things. This one is about keeping it declarative but inside the same file.

We don't have to convert it to go or make it automatic. Something like this would do:

package main

```go
import (
	"github.com/nspcc-dev/neo-go/pkg/interop/runtime"
)

func Main() {
	runtime.Log("Hello, world!")
}

func HelloWorldContract() *ContractData {
       return 
            `name: 'HelloWorld contract'
            supportedstandards: []
            events: []`
}
```

**Comment by roman-khimov** [comment]
It's the same in that this YAML is considered to be a problem by some people. Some of its contents can't be guessed at all, so any change would mean exactly that --- transferring from YAML into Go code constructs.

BTW, we do have some automation since 0.102.0, event types can be guessed for you.

**Comment by lock9** [comment]
How far are you guys from automating all of it? I believe it will always need some configuration information. 'Groups,' 'Trusts,' and other info will need human input. 
This can be an additional (and optional) feature. Allow the user to generate the configuration file using a method.

The goal with this is to use a single file instead of two. Developers usually keep just one file open at a time. A basic ctrl+f doesn't work outside the current file. This aggravates the problem of using the wrong names on methods and events.

**Comment by roman-khimov** [comment]
It's not a priority for now, contracts can be compiled with config files and we've got too many other issues to solve. Patches are welcome!

> Developers usually keep just one file open at a time.

Yeah, but we're compiling packages usually and they tend to have a number of files (`_test.go` if nothing else), then things like `*.sln` or `NuGet.Config` are OK for people and this config doesn't differ much from them.
