### ISSUE TITLE
OSX AMD64 build

### ISSUE THREAD

**Issue by ixje** [nspcc-dev/neo-go#3238]
## Is your feature request related to a problem? Please describe.
CI only seems to build ARM binaries for OSX
https://github.com/nspcc-dev/neo-go/blob/e8e964e3da7d4aa0954a45149bedce48cfd15a57/.github/workflows/build.yml#L42-L46
 whereas I'm looking download the `amd64` build. It was explicitly disabled in #2727 for build time reasons.

## Describe the solution you'd like
Enable AMD64 builds for OSX.

**Comment by roman-khimov** [comment]
Huh. I thought it's deprecated and every day there are less and less users of it.

**Comment by ixje** [comment]
End of 2020 is the first release of Apples M1 (ARM). That's just about 3 years ago. I don't think everybody replaces their Intel based machines in < 3 years for a first off chip

**Comment by roman-khimov** [comment]
That's Apple, I have no idea how people use Macs.

But if there is a real need then it doesn't cost a lot for us, this combination is tested and supposed to be OK.
