### ISSUE TITLE
Audit RPC notification subsystem filters against target structure types

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#3241]
We need to ensure that all filters used to filter out RPC notifications have proper field types. E.g. [`BlockFilter`](https://pkg.go.dev/github.com/nspcc-dev/neo-go@v0.104.0/pkg/neorpc#BlockFilter) has `PrinaryIndex` of `int` type while `block.Block` structure itself has `PrimaryIndex` of `byte`, and in this case we need to change filter's field type and all associated subscriptions logic.

**Comment by roman-khimov** [comment]
Primary index can't exceed `ValidatorsCount` in fact.

**Comment by AnnaShaleva** [comment]
It's more like upper-level check, but it can also be implemented on the RPC server side. Maybe it's good idea to have some `(*Fileter).IsValid()` method to be implemented on every filter? We may include `MaxEventNameLen` restriction to contract notifications filter `IsValid` check then as far.
