### ISSUE TITLE
Extend `getversion` RPC response with RPC server settings

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#3276]
Ref. https://github.com/nspcc-dev/neo-go/pull/3274#issuecomment-1864716933. We need to add a set of specific RPC server settings to `getversion` RPC response: `SessionsEnabled`, `MaxIteratorResultItems`, etc. so that RPC client can benefit from it.

**Comment by roman-khimov** [comment]
Let's consider this without `etc`, just two options that are easy to probe from outside and that can be useful for clients to know without probing.

**Comment by roman-khimov** [comment]
See https://github.com/neo-project/neo-modules/pull/878. The only problem is `sessionenabled` vs `sessionsenabled`.
