### ISSUE TITLE
Autogenerated RPC wrapper method/event names don't follow Go naming convention

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#3296]
## Is your feature request related to a problem? Please describe.
Autogenerated RPC wrapper uses underscores to differentiate between methods/event overloads:
```
// Renew creates a transaction invoking `renew` method of the contract.
// This transaction is signed and immediately sent to the network.
// The values returned are its hash, ValidUntilBlock value and error if any.
func (c *Contract) Renew(name string) (util.Uint256, uint32, error) {
	return c.actor.SendCall(c.hash, "renew", name)
}

// Renew_2 creates a transaction invoking `renew` method of the contract.
// This transaction is signed and immediately sent to the network.
// The values returned are its hash, ValidUntilBlock value and error if any.
func (c *Contract) Renew_2(name string, years *big.Int) (util.Uint256, uint32, error) {
	return c.actor.SendCall(c.hash, "renew", name, years)
}
```
The problem is that `revive` linter is unhappy about it:
```
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go$ golangci-lint run pkg/rpcclient/nns
pkg/rpcclient/nns/contract.go:311:20  revive  var-naming: don't use underscores in Go names; method Renew_2 should be Renew2
```

## Describe the solution you'd like
Fix RPC wrapper generator or compiler to use some other overloads separator.

## Describe alternatives you've considered
Add `nolint` comment to autogenerator template where appropriate.

## Additional context
Ref. https://github.com/nspcc-dev/neo-go/pull/3291#discussion_r1454815362.

**Comment by roman-khimov** [comment]
We shouldn't be generating underscores, true. If they come from the manifest --- we can't do much about it, but our own code shouldn't be adding them.
