### ISSUE TITLE
`FuzzMessageDecode` fails sometimes

### ISSUE THREAD

**Issue by AliceInHunterland** [nspcc-dev/neo-go#3316]
[Run tests (ubuntu-20.04, 1.20)](https://github.com/nspcc-dev/neo-go/actions/runs/7887650071/job/21523383491#logs) and ubuntu 1.19
[5_Run tests.txt](https://github.com/nspcc-dev/neo-go/files/14267842/5_Run.tests.txt)
 maybe related to #3307 (or caused by). 
 Just rerunning the failed job helps - for example [Run tests (ubuntu-20.04, 1.20)](https://github.com/nspcc-dev/neo-go/actions/runs/7887650071/job/21524702516#logs) (just successful run).

**Comment by AnnaShaleva** [comment]
> Just rerunning the failed job helps

It doesn't help, it just tells that this problem is poorly reproduceable.

> maybe related to https://github.com/nspcc-dev/neo-go/pull/3307 (or caused by).

Hardly ever it can be related to the logger sync.

**Comment by AliceInHunterland** [comment]
as we had data races in pkg/network tests it seems to me that failing FuzzMessageDecode with `race detected during execution of test` is just another manifestation of the #3307 problem

**Comment by AnnaShaleva** [comment]
Discussed, and closing this issue as not relevant after #3307.

**Comment by roman-khimov** [comment]
I thought fuzzers are disabled in our regular runs.

**Comment by AnnaShaleva** [comment]
> I thought fuzzers are disabled in our regular runs.

> Fuzz tests are run much like a unit test by default. Each seed corpus entry will be tested against the fuzz target, reporting any failures before exiting.

It's just about the fact that seed corpus of this test is quite large. But we run our tests without `--fuzz` flag, so no fuzzing is performed.
