### ISSUE TITLE
Add integration tests(e2e)

### ISSUE THREAD

**Issue by volekerb** [nspcc-dev/neo-go#333]
For integration testing it's good to cover several points:
- Docker image
- RPC calls to node
- Contract deploy and invocation 
- Node connection to other node (p2p)

---
Thoughts:
- Integration tests should be run as a separate command https://stackoverflow.com/questions/25965584/separating-unit-tests-and-integration-tests-in-go 
I found approach with naming all integration tests like 'server_integration_test' and having them run with special tag 'integration'.
- For running other nodes and checking docker image [testcontainers library](https://github.com/testcontainers/testcontainers-go) could be used

**Comment by roman-khimov** [comment]
I think we have everything from this list now covered either by unit tests or neo-bench (which does a lot of things now).
