### ISSUE TITLE
Error running Neo-go on osx / arm64

### ISSUE THREAD

**Issue by lock9** [nspcc-dev/neo-go#3342]
Our tool downloads Neo-go automatically from GitHub. However, there is an error when we try to run the tool. Similar to what happens here: https://github.com/neo-project/neo/issues/3176

## Current Behavior
When I download and open Neo Go, it shows one error, then another:

<img width="256" alt="Screenshot 2024-03-07 at 13 14 21" src="https://github.com/nspcc-dev/neo-go/assets/38396062/a9f82dcb-7763-48d4-8645-5335d530f3d6">

<img width="254" alt="Screenshot 2024-03-07 at 13 13 58" src="https://github.com/nspcc-dev/neo-go/assets/38396062/5e9b43eb-4640-48b1-a013-646929017340">

It shows an error inside the terminal: `zsh: killed`. 

## Expected Behavior
I should be able to run neo-go.

## Possible Solution
This is caused by new security updates on macOS. This can be solved by signing the installer after it is built. This happens on other platforms, and maybe updating the go version used to compile it can fix the issue.

## Steps to Reproduce

1. Using a mac/arm, download the latest neo-go release
2. Double click it or try to run it from the terminal

## Context
It's not possible to use Neo Go without fixing this.

## Regression
No

## Your Environment

* Version of the product used: 'Enumeration'
* Operating System and version (`uname -a`): Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:43 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8112 arm64

**Comment by lock9** [comment]
This can't be fixed without an Apple account. It's easier to ask users to authorize it inside the security panel.

**Comment by roman-khimov** [comment]
Thanks for info, but yeah, I don't think we can fix it our side.
