### ISSUE TITLE
logs: hide timestamp by default

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neo-go#3358]
while prepending log lines with timestamp may be a good feature, it must be disabled by default, the same way as all other programs do

**Comment by AnnaShaleva** [comment]
An option should be added, but it's under discussion whether to enable this option by default. To me, it should be explicitly enabled by the node user if needed, otherwise the original behaviour should be preserved.

**Comment by 532910** [comment]
It's ok to print timestamp by default, if the program is intended for developers.
In case it's intended for users -- the default should be not to show timestamps.

**Comment by EESergey** [comment]
Advanced logging with application timestamps can be output in debug mode. By default, debugging mode should be disabled. As an option, enable debugging mode depending on the application version; it will be enabled on pre-release versions.

**Comment by 532910** [comment]
I would not like to receive additional timestamps when enabling debug logging.
It should be a separate control or presence of controlling terminal.

**Comment by roman-khimov** [comment]
Level is orthogonal to format. For now I tend to think that `tty` magic is the best way to handle the problem.
