### ISSUE TITLE
Add ability to pass storage type and type-specific configuration via the config file

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#336]
We do have support for different blockchain storages internally, but that's only partially and not correctly exposed to the user, because the only store exposed is LevelDB (one can't choose Redis or memory-based store) and the only setting is `DataDirectoryPath`, which is DB-specific. Redis, for example, has hardcoded parameters:
```go
        c := redis.NewClient(&redis.Options{
                Addr:     "localhost:6379",
                Password: "",
                DB:       0,
        })
```
We need some way to choose DB type (especially if we're to do #335) and pass DB-specific parameters for initialization.

**Comment by volekerb** [comment]
True. And this is one of the reasons why it's not that easy to use in-memory db for the #305 fix

**Comment by roman-khimov** [comment]
Well, maybe then it's time to just do it (tm)! I'm especially interested in memory-backed `Store` as it's so easy to use it in a throw-away fashion for all kinds of tests.

**Comment by volekerb** [comment]
whynot yup
