### ISSUE TITLE
can't request block 0 over RPC

### ISSUE THREAD

**Issue by ixje** [nspcc-dev/neo-go#3427]
I'm trying to request block 0 over RPC and neo-go can't provide it whereas neo-cli can.

## Current Behavior
```json
{
    "id": 1,
    "jsonrpc": "2.0",
    "error": {
        "code": -101,
        "message": "Unknown block",
        "data": "key not found"
    }
}
```

## Expected Behavior
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACI6hnvVQEAAB2sK3wAAAAAAAAAAABrEj3YvscYZIhSu8eFleNTagWPnwEAAREA"
}
```

## Steps to Reproduce
not working go node
```shell
curl --location 'https://rpc10.n3.nspcc.ru:10331' \
--header 'Content-Type: text/plain' \
--data '{
  "jsonrpc": "2.0",
  "method": "getblock",
  "params": [0],
  "id": 1
}'
```

working neo-cli node
```
curl --location 'https://mainnet1.neo.coz.io:443' \
--header 'Content-Type: text/plain' \
--data '{
  "jsonrpc": "2.0",
  "method": "getblock",
  "params": [0],
  "id": 1
}'
```

**Comment by roman-khimov** [comment]
Related to #3426.

**Comment by ixje** [comment]
That sounds logical. I didn’t even notice the applicationlog was for the genesis fundsOn 29 Apr 2024, at 17:50, Roman Khimov ***@***.***> wrote:﻿
Related to #3426.

**Comment by AnnaShaleva** [comment]
@ixje, thank you for submitting these bugs! This one and #3426 are important ones. Keep going and submit any issues if something doesn't work as expected.
