### ISSUE TITLE
Releases don't include the default configuration files

### ISSUE THREAD

**Issue by lock9** [nspcc-dev/neo-go#3459]
## Current Behavior
I've downloaded the latest version of Neo Go and tried to run it using the following command:
`.\neo-go-windows-amd64.exe node -m`. It didn't work: `config './config/protocol.mainnet.yml' doesn't exist.`

## Expected Behavior
Running `neo-go.exe -m` should work.

## Possible Solution
The `./config` should be shipped with the binaries, or the binary should create them if they don't exist (main net and test net).

## Steps to Reproduce

1. Download Neo Go
2. Run the binary using the `node -m` option.

## Context
It's not possible to run the node without the file. The configuration file is not small and can't be typed. Users must download it from the repository and store it in the config folder.

## Your Environment
* Version of the product used: Zephirantes
* Server setup and configuration files used: Windows Server

**Comment by roman-khimov** [comment]
`-m/-t/-p` have a bit different meaning, it can't be changed this easy, but we know about the problem. Still have not found any decent solution.

**Comment by lock9** [comment]
One alternative could be to add an init command that generates the files.
Another one would be to use the rpc endpoint and use RPC to get the network magic, standby validators and other config info. Some SDKs do that already, I'm not sure if Neo Go does (c# doesn't)

**Comment by roman-khimov** [comment]
We can bundle our default ones and extract them using CLI. RPC would be lacking seeds at least, but it's an interesting idea for extension anyway.

**Comment by AnnaShaleva** [comment]
Related to #3450.
