### ISSUE TITLE
Ensure NeoFS chains compatibility with hardfork-dependent Notary contract

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#3465]
Depends on the draft implementation of #3464. Ref. https://github.com/neo-project/neo/pull/3178#issuecomment-2132993804.

1. Find the most early usage of Notary contract in NeoFS mainnet and testnet. Let it be `X` and `Y` height.
2. Take the branch from https://github.com/nspcc-dev/neo-go/issues/3464, build the node.
3. Take the https://github.com/nspcc-dev/neo-go/blob/master/config/protocol.mainnet.neofs.yml and https://github.com/nspcc-dev/neo-go/blob/master/config/protocol.testnet.neofs.yml, enable `B`, `C`and `D` hardforks to `X-1` and `Y-1` correspondingly for mainnet and testnet.
4. Process both NeoFS mainnet and testnet with  https://github.com/nspcc-dev/neo-go/issues/3464 and updated configurations.
5. Compare containers and netmap with https://github.com/nspcc-dev/neofs-contract/pull/399.

Write in the comment what are X and Y heights, what is the result of step 5.

**Comment by AnnaShaleva** [comment]
For the record, data for NeoFS mainnet:
* The first appearance of transaction with Notary contract as a signer is 3519285.
* The first appearance of transaction with NotaryAssisted attribute is the same (which is expected) 3519285.
* The first appearance of transaction with funds transferred to Notary contract is a bit earlier (which is also expected): 3519100.

Aspidochelone starts from 3000000. Thus, I suggest to test the following settings for mainnet:
```
  Hardforks:
    Aspidochelone: 3000000
    Basilisk: 3500000
    Cockatrice: 3500000
    Domovoi: 3500000
```

Testnet is not affected by this problem since all hardforks are active from genesis.

@roman-khimov, ACK?

**Comment by roman-khimov** [comment]
Perfect, yes.

**Comment by AnnaShaleva** [comment]
We're free to move on with Notary!
```
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neofs-contract$ go run scripts/compare-fscontent/compare-fscontent.go http://localhost:40332 https://rpc1.morph.fs.neo.org:40341
RPC http://localhost:40332 height: 5815701
RPC https://rpc1.morph.fs.neo.org:40341 height: 5815701
number of containers checked: 179
number of netmap entries checked: 5
```
