### ISSUE TITLE
Add RPC method for extended information on connected peers

### ISSUE THREAD

**Issue by EdgeDLT** [nspcc-dev/neo-go#3480]
## Is your feature request related to a problem? Please describe.

I want to be able to quickly query my node for the network state (see last height of peers and their user agents). I've called it `getPeerHeights` because that's the main thing I want to check but maybe `getConnectedPeerInfo` or `getNetworkState` etc is better.

## Describe the solution you'd like

Example usage:

```json
{
  "jsonrpc": "2.0",
  "method": "getpeerheights",
  "params": [],
  "id": 1
}
```

Example response:

```json
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "peerHeights": [
      {
        "address": "34.16.114.243:20333",
        "userAgent": "/Neo:3.7.4+7f227a3026fadeb9723280e6f961b6f29b0f8a7a/",
        "height": 4104904
      },
      {
        "address": "159.203.28.78:21333",
        "userAgent": "/NEO-GO:0.106.1/",
        "height": 4104904
      }
    ]
  }
}
```

## Describe alternatives you've considered

RPC extension seemed sensible enough.

## Additional context

I have already implemented this method to meet my current needs. If consensus is that its useful, I am happy to send a PR for review.

**Comment by AnnaShaleva** [comment]
I think this extension is quite a useful one since getpeers doesn’t give us anything except addresses. Vote up from my side for PR.

**Comment by roman-khimov** [comment]
How do you get this data? To me it requires P2P `ping` to every neighbor and thus this RPC can't be safely exposed to everyone.

Refs. https://github.com/neo-project/neo/issues/1844.

**Comment by EdgeDLT** [comment]
@roman-khimov I use `LastBlockIndex()` and `Version().UserAgent` on `Peer`. Admittedly I don't know how often this is updated, but I was thinking it would be sufficient to detect stuck-but-live nodes.

**Comment by ixje** [comment]
This sounds like a more useful alternative to the `getpeers` RPC method. Perhaps including `useragent` and `height` for `connected` nodes is a worthy update to that method instead (then C# users can also benefit from it)

**Comment by roman-khimov** [comment]
I had this thought as well, but current `getpeers` is symmetric for all types of nodes. Maybe it's not a problem though.

Semantically this `height` is more like `lastknownheight` I should also add.

**Comment by ixje** [comment]
I agree if we only add the fields to `connected` it sacrifices the symmetry. We could use something like `useragent: "unknown"` and `height: -1` for `unconnected`/`bad`. I just feel that the current `getpeers` output is so limited that likely nobody is consuming it. But you might have some stats on that from your nodes
