### ISSUE TITLE
 C#-v3.7.4 and NEOGO-0.106.1 calling result mismatch

### ISSUE THREAD

**Issue by dusmart** [nspcc-dev/neo-go#3482]
Between testnet C# v3.7.4 and golang NEO-GO:0.106.1. The calling results of `AoAaBgABLAESwB8MBG1haW4MFFMo9Cc1/EJCiUOG1Ow0/ZfStZoXQWJ9W1I=` differ.

## Current Behavior

*FAULT*

## Expected Behavior

*HALT* as what C# did

## Possible Solution

I have no idea.

## Steps to Reproduce

curl -sd '{ "jsonrpc": "2.0", "id": 5, "method": "invokescript", "params": ["AoAaBgABLAESwB8MBG1haW4MFFMo9Cc1/EJCiUOG1Ow0/ZfStZoXQWJ9W1I="] }' https://rpc.t5.n3.nspcc.ru:20331/ > /tmp/result_neogo.json

## Context

https://github.com/neo-project/neo/issues/3296

## Your Environment

* C# v3.7.4
* golang NEO-GO:0.106.1

**Comment by dusmart** [comment]
As public accessible testnet C# nodes are not available for now. You may have to run you own local nodes. From the comparison of neogo's gas_consumed and c#'s, I guess that neogo is more strict than C#.

I'm not sure which one should be changed. As C# is now the mainstream on mainnet, I guess that we'd better adapt neogo to C#'s behavior.

**Comment by dusmart** [comment]
https://github.com/neo-project/neo/issues/3300

Maybe it should be fixed by C#.

**Comment by roman-khimov** [comment]
We'll check, but `at instruction 177 (SYSCALL): stack is too big / json error: too big: size` is somewhat inspiring in this case.
