### ISSUE TITLE
inconsistent cli help information for db dump

### ISSUE THREAD

**Issue by ixje** [nspcc-dev/neo-go#3498]
This is just a minor inconsistency in the help description

## Current Behavior
```shell
./bin/neo-go db
NAME:
   neo-go db - database manipulations

USAGE:
   neo-go db command [command options] [arguments...]

COMMANDS:
   dump     dump blocks (starting with block #1) to the file
```
Note how for the dump command it states `starting with block #1`

Showing the help for the `dump` command states that `start from` defaults to 0 instead of 1

```shell
./bin/neo-go db dump -h
NAME:
   neo-go db dump - dump blocks (starting with block #1) to the file

USAGE:
   neo-go db dump -o file [-s start] [-c count] [--config-path path] [-p/-m/-t] [--config-file file]

OPTIONS:
   ...
   --start value, -s value  block number to start from (default: 0) (default: 0)
```

## Expected Behavior
I believe these two should be the same, whichever is the right one.

## Your Environment

* Version of the product used: v0.106.2

**Comment by AnnaShaleva** [comment]
It starts from the genesis by default, thus, it's `dump`'s usage should be adjusted.
