### ISSUE TITLE
Use Go 1.13 error wrapping

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#350]
When we're to require Go 1.13 it makes sense to go through our error handling and make use of wrap/unwrap where appropriate:

> An error e can wrap another error w by providing an Unwrap method that returns w. Both e and w are available to programs, allowing e to provide additional context to w or to reinterpret it while still allowing programs to make decisions based on w. 

https://golang.org/doc/go1.13#error_wrapping
See #349 also.

**Comment by AnnaShaleva** [comment]
Possible use-case for this issue is to implement wrappers for the following errors into `core/blockchain.go`:
- `ErrAlreadyExists`
- `ErrOOM`
- `ErrPolicy`
- `ErrInvalidBlockIndex`

and add other missing RelayResult errors in order to distinguish these errors into RPC level.
