### ISSUE TITLE
Neo-go (master branch) not starting ("Hardforks configuration section contains unexpected hardfork: Domovoi")

### ISSUE THREAD

**Issue by lock9** [nspcc-dev/neo-go#3506]
## Current Behavior
I'm running neo-go using the latest master branch:
```
On branch master
Your branch is up to date with 'origin/master'.
```

I'm trying to start the node using the following command:
```./bin/neo-go node -m```

Which results in:
```Hardforks configuration section contains unexpected hardfork: Domovoi```

I deleted my chains folder, but it didn't solve the issue.

## Expected Behavior
I should be able to start the node.

## Steps to Reproduce
1. Sync your code with the master branch
2. From the root folder, use `./bin/neo-go node -m`

## Context
It's not possible to use the application.

## Your Environment
* Version of the product used: Master branch
* Server setup and configuration files used: Main net
* Operating System and version (`uname -a`): Darwin Kernel Version 23.5.0: Wed May  1 20:19:05 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8112 arm64

**Comment by AnnaShaleva** [comment]
Are you sure that `./bin/neo-go node -m` contains the *fresh* binary? Try to `make build` firstly and then `./bin/neo-go node -m` one more time, please.

**Comment by lock9** [comment]
Oops, I just remembered that I need to build it. Thanks a lot.
However, I'm still having issues. Specifically, 'invokescript' is not working for me. Other RPC endpoints are working fine.

I only get:
 ```  
Cause:
AggregateError:
```

Is it me forgetting something again? Other tests are working fine

**Comment by AnnaShaleva** [comment]
> Cause:
> AggregateError:

Could you please provide the whole response? Could you also provide the parameters of you `invokescript` request? Which RPC client do you use? Are you sure you sent this request to NeoGo RPC node?

I'm asking because this error seems not to be something Go-related, it's looks more like C# or even JS.

**Comment by lock9** [comment]
Hello,

That's all the output. I think it's a firewall issue.. not sure why this started happening. I think it may be related to some security update. I was able to access neo-go RPC API locally, now I can't. If the configuration didn't change, it is probably something on my OS.

I'll close this. Thanks.

**Comment by AnnaShaleva** [comment]
We haven't change neither configuration nor code related to RPC, so you're probably right, this error doesn't seem to be caused by NeoGo code.
