### ISSUE TITLE
Panic in WS client in subscription mechanism

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neo-go#3516]
Have 100ms block machines (4) and our SN nodes (https://github.com/nspcc-dev/neofs-node) are subscribed to some events. Once in a time we have panics and have it more than once, i would say even consistently.

## Current Behavior
Create a client, subscribe, use it, panic.

## Expected Behavior
Create a client, subscribe, use it, no panic.

## Possible Solution
Not sure, i guess some slices (receivers and subscriptions) are not in sync.

## Steps to Reproduce
Run SN, go 100ms block time, see panics.

## Context
```
июл 16 14:06:04 node04 neofs-node[642022]: panic: runtime error: invalid memory address or nil pointer dereference
июл 16 14:06:04 node04 neofs-node[642022]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xa2e02e]
июл 16 14:06:04 node04 neofs-node[642022]: goroutine 114 [running]:
июл 16 14:06:04 node04 neofs-node[642022]: github.com/nspcc-dev/neo-go/pkg/rpcclient.(*WSClient).notifySubscribers(0xc001402540, {0x1a?, {0x1063ca0?, 0xc0000fda40?}})
июл 16 14:06:04 node04 neofs-node[642022]:         github.com/nspcc-dev/neo-go@v0.106.3-0.20240711090334-434f94800ad6/pkg/rpcclient/wsclient.go:696 +0x26e
июл 16 14:06:04 node04 neofs-node[642022]: github.com/nspcc-dev/neo-go/pkg/rpcclient.(*WSClient).wsReader(0xc001402540)
июл 16 14:06:04 node04 neofs-node[642022]:         github.com/nspcc-dev/neo-go@v0.106.3-0.20240711090334-434f94800ad6/pkg/rpcclient/wsclient.go:592 +0x625
июл 16 14:06:04 node04 neofs-node[642022]: created by github.com/nspcc-dev/neo-go/pkg/rpcclient.NewWS in goroutine 1
июл 16 14:06:04 node04 neofs-node[642022]:         github.com/nspcc-dev/neo-go@v0.106.3-0.20240711090334-434f94800ad6/pkg/rpcclient/wsclient.go:493 +0x51b
```

## Regression
Not sure. Have never seen it but also have never tried the client on this short block time. 

## Your Environment
Neo-go was taken from this branch: https://github.com/nspcc-dev/neo-go/pull/3508. Not a release but looks like some recent master.

**Comment by roman-khimov** [comment]
Duplicates #3093.
