### ISSUE TITLE
Check state dump time for mainnet

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#3519]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when we don't know how long it takes to make a state dump for a real network. Maybe it's seconds, maybe minutes, maybe hours.

## Describe the solution you'd like
Traverse MPT for the current state in a special utility (see state sync code that does the same thing effectively) and dump key/value pairs into some file. We need to get an approximate real-life value, so this can be performed on a laptop.

## Describe alternatives you've considered
Not a lot. We need to know if it's feasible to create state snapshots on a regular basis.

## Additional context
#3493, https://github.com/nspcc-dev/neofs-node/issues/2878.

**Comment by AliceInHunterland** [comment]
It was checked for mainnet at 5777148. It took from 6 to 8 minutes on a laptop. The resulting file is 250 Mb.
