### ISSUE TITLE
"could not create levelDB chain" during testing

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#353]
Our CI failed for #352 with
```
--- FAIL: TestSize (0.00s)
	Error Trace:	blockchain_test.go:179
			blockchain_test.go:185
			blockchain_test.go:161
	Error:      	Received unexpected error:
	            	resource temporarily unavailable
	Test:       	TestSize
	Messages:   	could not create levelDB chain
```
The other one looks like this:
```
--- FAIL: TestHandler (0.00s)
        Error Trace:    server_test.go:249
        Error:          Received unexpected error:
                        resource temporarily unavailable
        Test:           TestHandler
        Messages:       could not create levelDB chain
FAIL
```
All of this has nothing to do with the changes made to the code, something is wrong with tests (races of some kind?).

**Comment by roman-khimov** [comment]
Seems like both blockchain and rpc tests use the same levelDB in `rpc/chains` which is utterly wrong and leads to problems when tests are executed concurrently. It's strange that we didn't see it before. The issue is strongly related to #305.

**Comment by volekerb** [comment]
BTW saw same thing but thought it's related to my changes in separate branch.

**Comment by roman-khimov** [comment]
Not yet.

**Comment by volekerb** [comment]
> Not yet.

server_test.go not yet fixed
