### ISSUE TITLE
Designation event extension

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#3549]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when we don't have protocol parity with C# node. https://github.com/neo-project/neo/pull/3397 has implemented an event extension.

## Describe the solution you'd like
Port it to NeoGo.

**Comment by AnnaShaleva** [comment]
We can implement it, but just a note: this change was not merged into neo-project master.

**Comment by roman-khimov** [comment]
I know, but it's a technical detail mostly now. Looks like we'll have some gigantic hf_echidna branch (like a dev branch) that will then be merged without any additional changes.

**Comment by AnnaShaleva** [comment]
Depends on https://github.com/nspcc-dev/neo-go/pull/3554.
