### ISSUE TITLE
RPC unwrapper doesn't handle NULL even if functions are returning pointer to a struct

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#3581]
## Current Behavior
Consider a method like in #3580. RPC binding generator will produce some code for it, but this code won't handle NULL even though it's a pointer returned from this method in the contract (and in the binding as well).

## Expected Behavior
Return `nil`.

## Possible Solution
Add support for it.

## Your Environment
* Version of the product used: 0.106.3

**Comment by AnnaShaleva** [comment]
Tightly related to https://github.com/nspcc-dev/neo-go/issues/2795.

**Comment by roman-khimov** [comment]
Yeah, but bindings are a bit different.
