### ISSUE TITLE
VM: implement maps and associated instructions

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#359]
`NEWMAP`, `HASKEY`, `KEYS`, `VALUES`.

**Comment by fyrchik** [comment]
In `neo-vm` `NEWMAP` is implemented as a `Dictionary<StackItem, StackItem>`.
https://github.com/neo-project/neo-vm/blob/3b9fc1390f5d69da8e179de6af08e93cd9fdd2e4/src/neo-vm/ExecutionEngine.cs#L957
I believe C# `Dictionary` use generic equality methods for checking on key equality.

In Go equality of map keys cannot be overriden which could lead to a strange behavior:
https://play.golang.org/p/S2eOIcwQn7r
