### ISSUE TITLE
divisible NFT example does not follow NEP11 standard for properties method

### ISSUE THREAD

**Issue by ixje** [nspcc-dev/neo-go#3590]
The NEP11 standard for the `poperties()` method says ([ref](https://github.com/neo-project/proposals/blob/master/nep-11.mediawiki#properties))
> Returns a serialized NVM object containing the properties for the given NFT. The NVM object **must** conform to the "NEO NFT Metadata JSON Schema". 

Which basically means a map with the following keys: `name`, `description`, `image`, `tokenURI`
of which `name` is mandatory and the rest optional.

## Current Behavior
Returns 2 invalid keys
https://github.com/nspcc-dev/neo-go/blob/e1d5ac8557d7e087158e6a766d059913a56df79f/examples/nft-d/nft.go#L240-L242

## Expected Behavior
a NEP11 compliant return value

## Possible Solution
move `containerID` and `objectId`  into the `description` of some form.

If the example gets updated it might also be nice if the `onNEP17Payment` gets updated such that it outputs the errors using `ABORTMSG` opcode instead of the plain abort it uses now
https://github.com/nspcc-dev/neo-go/blob/e1d5ac8557d7e087158e6a766d059913a56df79f/examples/nft-d/nft.go#L356-L358

**Comment by roman-khimov** [comment]
I think the standard was meant to be extensible in contract-specific properties, take NNS for example:
https://github.com/neo-project/non-native-contracts/blob/8d72b92e5e5705d763232bcc24784ced0fb8fc87/src/NameService/NameService.cs#L67

And if I read these correctly:
https://json-schema.org/draft/2020-12/json-schema-core#section-10.3.2.1
https://json-schema.org/draft/2020-12/json-schema-core#section-10.3.2.3
https://json-schema.org/draft/2020-12/json-schema-core#section-11.3

That's also the way provided JSON schema works in fact. We've got some `properties`, fine, then we don't have any `additionalProperties` or `unevaluatedProperties`, so validation for additional items follows an empty schema which always succeeds. NOBUG to me.

**Comment by ixje** [comment]
I agree with you this is no bug. I was under the impression that `properties` were the only allowed other keys, while in the back of my mind I seem to remember other keys used but I couldn't find examples.
