### ISSUE TITLE
packmap operation keeps duplicate entries

### ISSUE THREAD

**Issue by Slava0135** [nspcc-dev/neo-go#3613]
## Current Behavior

packmap keeps duplicate keys (and entries)
behavior might be considered undefined, though its probably better to copy C# implementation

![image](https://github.com/user-attachments/assets/d05e0a9d-3607-4982-9291-21174aded66e)

```json
[
  {
    "type": "Map",
    "value": [
      {
        "key": {
          "type": "Integer",
          "value": "1"
        },
        "value": {
          "type": "Integer",
          "value": "1"
        }
      },
      {
        "key": {
          "type": "Integer",
          "value": "1"
        },
        "value": {
          "type": "Integer",
          "value": "1"
        }
      }
    ]
  }
]
```

## Expected Behavior

C# results:
```json
[
  {
    "type": "Map",
    "value": [
      {
        "key": {
          "type": "Integer",
          "value": "1"
        },
        "value": {
          "type": "Integer",
          "value": "1"
        }
      }
    ]
  }
]
```

## Steps to Reproduce

1. `./bin/neo-go vm`
2. `loadbase64 ERERERK+`
3. `run`

## Your Environment

* Version of the product used: master (a9242535db757faba860e21c194033f30c679f48)

**Comment by roman-khimov** [comment]
And it's a map, it can't have duplicate keys, one key --- one value.
