### ISSUE TITLE
neofs.ObjectSearch returned fewer objects than expected

### ISSUE THREAD

**Issue by AliceInHunterland** [nspcc-dev/neo-go#3615]
## Current Behavior
When using `neofs.ObjectSearch` on the NeoFS Testnet, it returned fewer objects than expected https://github.com/nspcc-dev/neo-go/pull/3582#discussion_r1785873165. The expected number of objects was `128,000` (the `indexFileSize`), but the search result returned only `19,705` objects. There were no errors during the search execution.

```go
prm := client.PrmObjectSearch{}
filters := object.NewSearchFilters()
filters.AddFilter(attribute, fmt.Sprintf("%d", 0), object.MatchNumGE)
filters.AddFilter(attribute, fmt.Sprintf("%d", indexFileSize), object.MatchNumLE)
prm.SetFilters(filters)

objectIDs, err := neofs.ObjectSearch(ctx.Context, clientSDK, account.PrivateKey(), containerID.String(), prm)
fmt.Println("Number of objects found: ", len(objectIDs))
```

### Output:
```
Number of objects found: 19705
```

## Expected Behavior
The search should return all `128,000` objects in the container, as per the `indexFileSize` configuration.

## Possible Solution
- Check on different containers and mainnet, maybe it was problems with attributes
- Timeout of reading

## Steps to Reproduce
Example above.

## Context
This issue prevents retrieving all expected objects from the container in NeoFS Testnet. I am trying to upload and manage a large number of blocks in NeoFS, and incomplete search results disrupt the process.

**Comment by AnnaShaleva** [comment]
Depends on https://github.com/nspcc-dev/neofs-node/issues/2979.

**Comment by AnnaShaleva** [comment]
SEARCH results may be incomplete by NeoFS design, not a NeoGo issue, hence I'm closing this as not planned.
