### ISSUE TITLE
`generate-rpcwrapper` config file flag clarification

### ISSUE THREAD

**Issue by AliceInHunterland** [nspcc-dev/neo-go#3646]
## Is your feature request related to a problem? Please describe.

 I'm always frustrated when I use cli and do not know for sure from the `help` what argument should be passed.
```
NAME:
   neo-go contract generate-rpcwrapper - Generate RPC wrapper to use for data reads

USAGE:
   neo-go contract generate-rpcwrapper --manifest <file.json> --out <file.go> [--hash <hash>] [--config <config>]

OPTIONS:
   --config value, -c value    Configuration file to use
   --manifest value, -m value  Read contract manifest (*.manifest.json) file
   --out value, -o value       Output of the compiled wrapper
   --hash value                Smart-contract hash. If not passed, the wrapper will be designed for dynamic hash usage
   --help, -h                  show help

``` 
Why does passing --config <config> yield different results than not using the flag, although this isn't mentioned in the description. Also, I do not know if this config file is the same as it is in `neo-go contract compile` where at least an extension is mentioned (`Configuration input file (*.yml)`, but the flag is the same)
## Describe the solution you'd like

Example or more details about flags in the command description.
## Describe alternatives you've considered

do nothing with it. be more attentive and read docs and workshop repo.

**Comment by roman-khimov** [comment]
Long-term with NEP-25 implemented we will drop this configuration file. Short-term, if we can quickly make it fail because of unknown fields --- that'd be the best solution.
