### ISSUE TITLE
The OID of the put object can be saved into index file immediatly in `upload-bin`

### ISSUE THREAD

**Issue by AliceInHunterland** [nspcc-dev/neo-go#3655]
## Is your feature request related to a problem? Please describe.

 I'm always frustrated when it appears that OID can be calculated in the `uploadObj` function. So we do not need to perform lots of searches for OIDs after the main batch of blocks is done.
## Describe the solution you'd like

Return OID from `uploadObj`  and save it into the index file right away.  Ref. https://github.com/nspcc-dev/neo-go/commit/a0a0358cb11510911696f1d2ec505f8b6cb7f3c3
## Describe alternatives you've considered

Leave as is.

**Comment by AnnaShaleva** [comment]
Consider https://github.com/nspcc-dev/neo-go/pull/3650#issuecomment-2452910462 during implementation.

**Comment by AliceInHunterland** [comment]
> Consider [#3650 (comment)](https://github.com/nspcc-dev/neo-go/pull/3650#issuecomment-2452910462) during implementation.

> And uploadIndexFiles can't be removed anyway, we must consider cases when you don't have all OIDs in-place.

In https://github.com/nspcc-dev/neo-go/commit/a0a0358cb11510911696f1d2ec505f8b6cb7f3c3 uploadIndexFiles is not removed but moved to the first place. 
1. Check and upload index files using uploadIndexFiles, and return a partially filled buffer (if oldestMissingBlockIndex\ indexFileSize!=0).
2. Upload blocks from oldestMissingBlockIndex and when the buffer is full - upload the index file. 

What do you mean by  `cases when you don't have all OIDs in-place.`?

**Comment by AnnaShaleva** [comment]
> is not removed but moved to the first place.

OK. It needs some care.

> What do you mean by cases when you don't have all OIDs in-place.?

E.g. uploading index file without block object uploads. Or with partially uploaded blocks. I'm not saying that your commit doesn't contain this code, but such edge cases must be handled with care and we must ensure that script works properly for such edge cases.
