### ISSUE TITLE
Support loading precompiled `NEF` files in `neotest`

### ISSUE THREAD

**Issue by Chubru** [nspcc-dev/neo-go#3679]
## Is your feature request related to a problem? Please describe.

At the moment `neotest` allows contract compilation from source code. However, in some cases, it would be useful to load a contract from a `NEF` file. This can be especially helpful, for instance, when testing contract migration from a previous version.

## Describe the solution you'd like

Add a method to allow loading contracts from a `NEF` file.

**Comment by roman-khimov** [comment]
You can preload them in a way similar to how NeoFS contract updates are tested, see https://github.com/nspcc-dev/neofs-contract/blob/master/contracts/netmap/migration_test.go and https://github.com/nspcc-dev/neofs-contract/blob/69e9f737c91fc862dcf88496d8a8f9ebc1f4518a/tests/migration/storage.go#L78, but I agree it's not very elegant.
