### ISSUE TITLE
Notification subscription filter unit test checks nothing

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neo-go#3693]
https://github.com/nspcc-dev/neo-go/blob/57eec71101bad9d6d01bbaeecba0a2105f9dbd6b/pkg/services/rpcsrv/subscription_test.go#L244-L263

## Current Behavior
Subscription filters (execution notification) are called, none of the events are ever sent back, check funcs are also never called, test does nothing.

## Expected Behavior

Use some real notifications that are triggered and that can be tested. E.e. from the Rubl contract or from some native contract. 

## Possible Solution

Drop `my_pretty_notification`, this name is from nowhere. I don't know if it ever worked before but now it does not for sure. Use some real notifications from dumped blocks.

## Steps to Reproduce

Add some `print` in `check` func, see that it is never called
or
do `my_pretty_notification` search, see that it is never called, does not exist in any example contract, and is not passed in any predefined-blocks code, this event cannot happen from nowhere.

## Context
I tried to understand how to extend notification filter tests and could not understand why it works but it just does not work.

## Regression
Not sure, seems like not, the commit that adds it, does not change any example contract code.

## Your Environment
v0.106.3

**Comment by carpawell** [comment]
Also, I cannot understand why this code works but seems like it works: https://github.com/nspcc-dev/neo-go/blob/57eec71101bad9d6d01bbaeecba0a2105f9dbd6b/pkg/services/rpcsrv/subscription_test.go#L86

This is a buffer for server messages, but why is it 16-messages long? We have at least 23 blocks and every test subscribes for blocks first and then reads subscriptions. One routine, block by block. It cannot fit the buffer and I think it should lock somehow but tests work ok (or just pretend to work ok). I am afraid at some point this test can lock and it would take some time to understand what is happening. What am I missing? Is everything ok with this code? It has not changed since the notification release.

**Comment by AliceInHunterland** [comment]
> Also, I cannot understand why this code works but seems like it works:
> 
> [neo-go/pkg/services/rpcsrv/subscription_test.go](https://github.com/nspcc-dev/neo-go/blob/57eec71101bad9d6d01bbaeecba0a2105f9dbd6b/pkg/services/rpcsrv/subscription_test.go#L86)
> 
> Line 86 in [57eec71](https://github.com/nspcc-dev/neo-go/commit/57eec71101bad9d6d01bbaeecba0a2105f9dbd6b)
> 
>  respMsgs := make(chan []byte, 16) 
> This is a buffer for server messages, but why is it 16-messages long? We have at least 23 blocks and every test subscribes for blocks first and then reads subscriptions. One routine, block by block. It cannot fit the buffer and I think it should lock somehow but tests work ok (or just pretend to work ok). I am afraid at some point this test can lock and it would take some time to understand what is happening. What am I missing? Is everything ok with this code? It has not changed since the notification release.

The first idea: The buffer size of `respMsgs` (16) matches the number of blocks processed until the end of manipulation with `test_contract.go`.  But not sure about it.

The test will work even with a buffer size of `1` because the channel is read by a separate goroutine (`wsReader`), and messages are consumed synchronously in the test, so it should not be blocked. And even if it will happen we have `case <-time.After(10 * time.Second):` and `ws.SetReadDeadline(time.Now().Add(5 * time.Second))` which will interrupt the `readLoop`, ensuring it does not hang.
