### ISSUE TITLE
VM: implicit operand conversion

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#372]
In the reference NeoVM implementation arithmetic opcodes (`SIGN`, `ABS` ...) can also work with boolean values.
https://github.com/neo-project/neo-vm/blob/master/tests/neo-vm.Tests/Tests/OpCodes/Numeric/SIGN.json#L31
This is because `GetBigInteger` is defined for `Boolean` stack item.

Here is a list of implicit conversions than can be performed:
1. `Integer` from `Integer` and `Boolean` . (and default using `ByteArray`)
2. `ByteArray` from `Integer`, `ByteArray` and `Boolean`
3. `Boolean` from `ByteArray`, `Integer`, `Boolean`, `Array`, `Interop` and `Map`

Links:
Interface https://github.com/neo-project/neo-vm/blob/f9a5b2fa0f806b7f9db542efea4fcce9aae917b2/src/neo-vm/StackItem.cs
Implementations https://github.com/neo-project/neo-vm/tree/bf891cf07f7a2cd25212050cc6fe20588f77934d/src/neo-vm/Types

**Comment by roman-khimov** [comment]
Yeah, I saw some part of that and it looked scary. Are you sure this is the complete list of conversions for all cases? That's what I'm always concerned about when dealing with these kinds of things --- not missing some corner case where all of the magic works in a different manner for some reason.
