### ISSUE TITLE
How to catch an exception thrown by another contract?

### ISSUE THREAD

**Issue by lock9** [nspcc-dev/neo-go#3732]
## Problem
I'm calling a contract that _may_ throw an exception. I want to be able to 'catch' the exception.

## Context
I have a 'proxy' contract that redirects calls to other contracts. If the called contract throws an exception, I would like to abort the transaction. We are sponsoring this transaction and don't want it to be persisted if there's an error. 

If I recall correctly, transactions that fail with 'un-catched exceptions' can persisted, while those aborted aren't (please correct me if I'm wrong)

Edit 2: @EdgeDLT showed me these examples: https://github.com/nspcc-dev/neo-go/blob/master/pkg/compiler/defer_test.go but I'm still a bit confused.

1 - Is 'panic' going to use Opcode.Abort? 
2 - If I use panic, I get:`at instruction 900 (ENDFINALLY): unhandled exception: `. Does the 'unhandled exception' and 'abort' have the same error messages?  When it says 'unhandled', does it mean it can be handled('catched')?

**Comment by roman-khimov** [comment]
> I want to be able to 'catch' the exception.

Since exceptions are represented as `panic`, you need to `recover()` in a standard Go way. Like https://github.com/nspcc-dev/neofs-contract/blob/f5a31fd10a31988b019feaa6a04aeaf27f71afbf/contracts/container/contract.go#L469-L479

> I have a 'proxy' contract that redirects calls to other contracts. If the called contract throws an exception, I would like to abort the transaction.

If nothing above your contract is not dealing with exceptions you can just leave it, unhandled exception aborts the transaction anyway.

> Is 'panic' going to use Opcode.Abort?

No.

> Does the 'unhandled exception' and 'abort' have the same error messages?

No.

> When it says 'unhandled', does it mean it can be handled('catched')?

Yes.

**Comment by lock9** [comment]
In my case, I need to use abort to avoid someone wrapping the contract call in a try-catch block. 

I just found the abort inside the util package. Thanks.
