### ISSUE TITLE
How to make a tx, the third account pay the gas fee

### ISSUE THREAD

**Issue by godlovericea** [nspcc-dev/neo-go#3738]

**Comment by AnnaShaleva** [comment]
The first account in the list of transaction's Signers is the one who pays fees, it's a rule for Neo. So the third account can't pay the fees, you need to reorder the list of transaction's signers.

**Comment by roman-khimov** [comment]
<img width="522" alt="Screenshot_20241209_184509" src="https://github.com/user-attachments/assets/9d64cbf6-1539-4339-905a-30c54247b17f">

Signers are the key here. See https://neospcc.medium.com/thou-shalt-check-their-witnesses-485d2bf8375d which is somewhat related (you'll need proper scopes for your signers anyway).

**Comment by godlovericea** [comment]
@roman-khimov @AnnaShaleva 
Can you give me some code examples?

**Comment by AnnaShaleva** [comment]
Please, see dApps development workwhop to learn the basics of dApps development with NeoGo:
* The workshop itself: https://github.com/nspcc-dev/neo-go-sc-wrkshp/tree/master?tab=readme-ov-file#workshop-content
* The list of useful links: https://github.com/nspcc-dev/neo-go-sc-wrkshp/tree/master?tab=readme-ov-file#useful-links
* An example of dApp that demonstrates basic usage scenarios of NeoGo SDK: https://github.com/nspcc-dev/neo-go-sc-wrkshp/tree/master/dApp
