### ISSUE TITLE
How to get the network fee during a test invoke? (inside a smart contract)

### ISSUE THREAD

**Issue by lock9** [nspcc-dev/neo-go#3777]
## Problem
I'm validating the transaction fees to ensure they aren't above a specific threshold. I'm using test invoke to validate most of my contract features. It works, except when it comes to network fees. The values are always 0 (during test invoke). 

- Is this expected? Is there any way that I can get the proper value of the net fee inside a smart contract?
- There are some occasions where I have to attach an extra network fee. I remember this being fixed. Could anyone confirm? Do I need to use another endpoint to calculate this dynamic fee?
-  (Unrelated) When should I use int64 instead of int? I just realized I've been using int everywhere. Could this cause an overflow? Should I replace all int with int64? 

## Context
This is my contract code:

```go
func ValidateFeeRequirement(feeReq FeeRequirement, ctx ValidationContext) ValidationResult {
	transaction := runtime.GetScriptContainer()

	if transaction.NetFee > feeReq.MaxNetworkFee {
		return ValidationResult{Success: false, ErrorMessage: "Network fee exceeds the maximum allowed fee"}
	}

	if transaction.SysFee > feeReq.MaxSystemFee {
		return ValidationResult{Success: false, ErrorMessage: "System fee exceeds the maximum allowed fee"}
	}

	return ValidationResult{Success: true}
}
```

It seems that NetFee is always 0. The following test won't work unless I change the net fee requirement to '-1'. This is an indicator that the current netfee of the test invoke is 0:

```typescript
test("Validate fee requirement with network fee exceeding maximum", async () => {
    const feeRequirement = new FeeRequirement({
        maxNetworkFee: BigInt(0),  // Will work if replaced with -1. 
        maxSystemFee: BigInt(1000000)
    });
    const validationContext = createDummyValidationContext();
    
    const {result, exception} = await PermissionsManager.Test.validateFeeRequirement({
        feeReq: feeRequirement,
        ctx: validationContext
    });

    expect(exception).toBeNull();
    expect(result?.success).toBe(false);
    expect(result?.errorMessage).toBe('Network fee exceeds the maximum allowed fee');
});
```

Is it possible to 'emulate' the network fees during a test invoke?

**Comment by roman-khimov** [comment]
> Is this expected? 

Yes.

> Is there any way that I can get the proper value of the net fee inside a smart contract?

No. There is no "proper" value, especially when we're doing test invocations. There is no transaction to evaluate its size, it's not yet signed to evaluate GAS required for witness check. And users can legitimately add any amounts to the minimum allowed values.

> When should I use int64 instead of int? I just realized I've been using int everywhere. Could this cause an overflow? Should I replace all int with int64?

With the compiler we have now they're all the same 256-bit integers.

Related to https://github.com/neo-project/neo/issues/2568#issuecomment-899167753.

**Comment by lock9** [comment]
Thanks Roman.

About the dynamic fee calculation - should it work for all cases? Does it need any special config or endpoint?

>Related to https://github.com/neo-project/neo/issues/2568#issuecomment-899167753.

Not sure if I understood how they are related, but I suppose it's about differences between testinvoke and a real invoke? Is it related to the dynamic fee calculation?

**Comment by roman-khimov** [comment]
> About the dynamic fee calculation - should it work for all cases?

I'm not sure what problems you're referring to. RPC estimates work as specified. But

> it's about differences between testinvoke and a real invoke?

can still happen in some cases (https://github.com/neo-project/neo/issues/2806).

**Comment by lock9** [comment]
Ah ok. That solves the mystery. Thanks again.
