### ISSUE TITLE
VM: LEFT with big index should not fault

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#378]
If an operand of `LEFT` is more or equal than length of the array, entire array should be returned.

Implementation https://github.com/neo-project/neo-vm/blob/master/src/neo-vm/ExecutionEngine.cs#L465
Test https://github.com/neo-project/neo-vm/blob/master/tests/neo-vm.Tests/Tests/OpCodes/Splice/LEFT.json#L154

**Comment by roman-khimov** [comment]
Refs. #356.

**Comment by roman-khimov** [comment]
I actually thought that failing in this case is an obvious and desired behavior and didn't even check with C# code. But turns out NEO VM is way more fancy.
