### ISSUE TITLE
SUBSTR and LEFT tests failing with Go 1.11

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#384]
Notice, they work correctly with Go 1.12, but with Go 1.11:
```
--- FAIL: TestSUBSTRBadOffset (0.00s)
        Error Trace:    vm_test.go:649
        Error:          Not equal: 
                        expected: true
                        actual  : false
        Test:           TestSUBSTRBadOffset
--- FAIL: TestSUBSTRBadLen (0.00s)
        Error Trace:    vm_test.go:659
        Error:          Not equal: 
                        expected: true
                        actual  : false
        Test:           TestSUBSTRBadLen
--- FAIL: TestLEFTBadLen (0.00s)
        Error Trace:    vm_test.go:694
        Error:          Not equal: 
                        expected: true
                        actual  : false
        Test:           TestLEFTBadLen
```

**Comment by roman-khimov** [comment]
So I guess it's time for us to drop 1.11 support as it's not supported by upstream either after the release of 1.13.

**Comment by roman-khimov** [comment]
Refs. #383.

**Comment by volekerb** [comment]
Let's drop it! =)

**Comment by fyrchik** [comment]
It seems like `go1.11` take subslices based on capacity of underlying slice, not it's length. (run with `go1.11` and `go1.11.13`)
```golang
package main
import "fmt"
func main() {
        a := make([]byte, 3, 10)
        b := a[:5] // no panic here in go1.11
        fmt.Println(a)
        fmt.Println(b)
}
```

**Comment by roman-khimov** [comment]
@fyrchik: thanks for really digging into the problem. So it looks like according to [the spec](https://golang.org/ref/spec#Slice_expressions):

> For arrays or strings, the indices are in range if 0 <= low <= high <= len(a), otherwise they are out of range. For slices, the upper index bound is the slice capacity cap(a) rather than the length.

Which makes my code incorrect and working for Go 1.12 and 1.13 only by accident. Thus, this issue is not really solved.

**Comment by roman-khimov** [comment]
Closing in favor of #387.
