### ISSUE TITLE
VM: check for the slice bounds explicitly

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#387]
There is a case in #384 where previous version of Go failed some of the testcases.
Funnily enough, we can make the same tests fail on the current versions of Go just by changing
```golang
vm.estack.PushVal([]byte("abcdef"))
```
to
```golang
s := "abcdef"
vm.estack.PushVal([]byte(s))
```

This is something we should fix, by explicitly checking for slice bounds where possible.
This has an additional benefit of more explicit errors.

**Comment by volekerb** [comment]
pow wow, @fyrchik thanks for catching it!
