### ISSUE TITLE
Core: refactor core package

### ISSUE THREAD

**Issue by volekerb** [nspcc-dev/neo-go#398]
Discovered several big issues we've already opened:
#368, #367, #366, #365
Can't imagine we can fix in a proper way without refactoring main core package.
It has much files which references each other and it's hard to pull something to separate package since it starts to be in circular dependency.
I believe first point to refactor should be:
`blockchain.go` with #367

Opened this issue to have offline discussion about what should be responsible for what.
There are main parts which can't be separated as of now:
transactions
mempool
blocks
cache

**Comment by fyrchik** [comment]
interops can have a separate package too, though there are circular dependencies in tests.

**Comment by roman-khimov** [comment]
I think this one is no longer relevant, all issues mentioned above were fixed, interops moved out of `core` mostly, native contracts are in their own package, `core` definitely got smaller than it used to be. It can still be improved, but it doesn't require any substantial "change everything" effort now.
