### ISSUE TITLE
Configurable log path and IP address to bind

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neo-go#460]
To run Neo Go node in production, we need a way to configure at least these two options:
- a path to log file
- an IP address for a node to bind, for a hosts with multiple IP addresses on an interface

The options should be set via the config file.

**Comment by volekerb** [comment]
1. As a workaround we can use pipe to stdout everything to some file.
2. Can you provide some example? Or point out to some configuration like that?
Am I right that we're talking about docker config here?

**Comment by roman-khimov** [comment]
1) I think logrus should have some options for that, if that's the case it should be trivial to add.
2) Certainly useful, not hard to implement.

**Comment by volekerb** [comment]
@aprasolova @roman-khimov can you please point out me to example for 2) bullet. Or explain a bit what you mean here. ty!
