### ISSUE TITLE
io: implement missing routines

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#494]
There are some things that can be address to simplify encoding/decoding in other code:
- [x] implement `io.Serializable` for `Uint256` to simplify encoding/decoding of array of hashes.
- [ ] implement `io.BinReader.ReadMap` and `io.BinWriter.WriteMap`

**Comment by fyrchik** [comment]
I am not sure about second case, because there not many maps, but they are very different, like:
- map from some type to a slice of serializables (which should be serialized by `WriteArray`)
- map with simple types serialized by `WriteLE`
- map with default types (uint64) serialized by `WriteLE`

It won't be so simple to implement all cases at once and I am not sure doing so will simplify out code a lot. I'd rather first refactor everything to a point where we have `map[a]b` with `a` and `b` implementing `io.Serializable` and then implement a simple `WriteMap`.

**Comment by roman-khimov** [comment]
I think we're fine with the current map handling, changing that can also make things more slow, so it's not worth the trouble.
