### ISSUE TITLE
Add TriggerType constants

### ISSUE THREAD

**Issue by volekerb** [nspcc-dev/neo-go#509]
In the code we have variables representing TriggerTypes. For example one place:
```
if ic.trigger != 0x10 && ic.trigger != 0x11 {
...
```
https://github.com/nspcc-dev/neo-go/blob/5e8122bfac212ea6dc46e68d751e5450e43817f5/pkg/core/interop_system.go#L400

In reference C# implementation there is an Enum:
https://github.com/neo-project/neo/blob/c64748ecbac3baeb8045b16af0d518398a6ced24/neo/SmartContract/TriggerType.cs#L3
It's good to have such constants in our code as well with such a good doc too.

**Comment by roman-khimov** [comment]
The only thing I'm not sure about at the moment is what is the proper place for them. `smartcontract`? `vm`? `core`? I hope not `core`, although that's where it's used now, `vm` doesn't care much about this context, but interops do.
