### ISSUE TITLE
Remove errors from some function signatures

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#514]
`io.BufBinWriter` actually can never encounter errors. This means that e.g. `BlockBase.GetHashableData` will never return an error. This in turn lowers our test coverage and makes code unnecessary verbose.
I suggest to make it and similar functions to return no error.
Thoughts? @roman-khimov @volekerb

**Comment by roman-khimov** [comment]
We probably can do that, although it requires very careful review in each of the cases. It might also require `Bytes()` simplification to not put error into the `bw.Err` (just following regular `bytes.Buffer` semantics wrt `Bytes()` and read/writes), it needs to be documented (and commented in every case of buffer usage that doesn't check for error). But yes, that would be a nice simplification.
