### ISSUE TITLE
io: array decoding/encoding | slice with nil can't be converted

### ISSUE THREAD

**Issue by volekerb** [nspcc-dev/neo-go#519]
`binaryReader.ReadArray()`
Doesn't encodes/decodes properly slices == nil.

Unit test (fails):
```
accountState := &entities.AccountState{}
buf := io.NewBufBinWriter()
a.EncodeBinary(buf.BinWriter)
assert.Nil(t, buf.Err)

aDecode := &AccountState{}
r := io.NewBinReaderFromBuf(buf.Bytes())
aDecode.DecodeBinary(r)

assert.Equal(t, a, aDecode)
```

**Comment by volekerb** [comment]
Related issue we have with structs having nil pointers:
```
type AssetState struct {
	ID         util.Uint256
	AssetType  transaction.AssetType
	Name       string
	Amount     util.Fixed8
	Available  util.Fixed8
	Precision  uint8
	FeeMode    uint8
	FeeAddress util.Uint160
	Owner      *keys.PublicKey
...
```
while encoding/decoding `&AssetState{}` we will panic

**Comment by fyrchik** [comment]
There is some ambiguity in both cases. Both `nil` and empty slice and both `Infinity` public key and `nil` pointer are encoded similarly. So when we decode, we need to stick with one of this cases.
When decoding public key, we can copy C# implementation behavior, where key is unmarshaled to `Infinity`.

Panic in the second case can be fixes though.
