### ISSUE TITLE
create setup with running privnet based on neo-go

### ISSUE THREAD

**Issue by volekerb** [nspcc-dev/neo-go#524]
To make subj we have to:
1. Dump 6000 or so blocks from privnet (in order to have account with Gas)
2. Change compose file and makefile to accept param to restore blockchain from that dump and start bc from 6000th block.

**Comment by roman-khimov** [comment]
[6000-privnet-blocks.acc.gz](https://github.com/nspcc-dev/neo-go/files/3897384/6000-privnet-blocks.acc.gz)

I think these are the blocks in question.

**Comment by roman-khimov** [comment]
They're corresponding to the neo-local setup where everything is owner by the `AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y` with a WIF of `KxDgvEKzgSBPPfuVfw67oPQBSjidEiqTHURKSDL1R7yGaGYAeYnr`.

**Comment by roman-khimov** [comment]
To restore: `./bin/neo-go db restore -i 6000-privnet-blocks.acc`

**Comment by im-kulikov** [comment]
As I understand, we should run nodes in two steps:
- restore from the archive if it's a clean start
- running node in normal mode 

I propose to add `docker-entrypoint.sh` like in [Postgres](https://github.com/docker-library/postgres/blob/34df4665bfdccf28deac2ed2924127b94489a576/12/docker-entrypoint.sh#L248)

**Comment by im-kulikov** [comment]
@fyrchik can you provide config with NeoCLI private keys?
