### ISSUE TITLE
Add unit tests for compiler/emit

### ISSUE THREAD

**Issue by volekerb** [nspcc-dev/neo-go#534]
We have weak coverage and it's good to have them to check yourself while doing refactoring.

**Comment by roman-khimov** [comment]
Maybe we're better solving #449 first and then see what's left for this one.

**Comment by volekerb** [comment]
hm. I would prefer to have unit tests before refactoring

**Comment by roman-khimov** [comment]
I mean I want to avoid merging two implementations and then throwing one test set away. We have at least some coverage for `vm` that could be reused.
