### ISSUE TITLE
release flow: Add release flow with pushing docker images to hub

### ISSUE THREAD

**Issue by volekerb** [nspcc-dev/neo-go#573]
It will be nice to have description of the release process so everyone knows how to do that.
As an additional thing I would like to suggest having docker images on our hub:
"nspccdev/neo-go" since now we have only https://hub.docker.com/r/cityofzion/neo-sharp which looks like not used and newcomers/users can't get an image.

**Comment by roman-khimov** [comment]
Like this one? https://github.com/nspcc-dev/neo-go/blob/master/docs/release-instruction.md

**Comment by volekerb** [comment]
@roman-khimov somehow missed that. Yeah, exactly. So there is only one point left then: add docker build/push strategy there
