### ISSUE TITLE
private key sign bug

### ISSUE THREAD

**Issue by mesment** [nspcc-dev/neo-go#592]
PrivateKey.Sign method  in  keys package
assignment mismatch:  rfc6979.SignECDSA returns 2 values but asign to 3 variables

<img width="526" alt="signbug20200113112201" src="https://user-images.githubusercontent.com/19592580/72231569-2e684100-35f7-11ea-8e8f-14be647c7f6a.png">

![signbug20200113112806](https://user-images.githubusercontent.com/19592580/72231694-da119100-35f7-11ea-8f8d-88932d7bba19.png)
<img width="1140" alt="signbug20200113112112" src="https://user-images.githubusercontent.com/19592580/72231699-e0a00880-35f7-11ea-98fc-90d4f7d49a34.png">

**Comment by roman-khimov** [comment]
What is the version (git commit) you're trying to build? And what is the `rfc6979` package you're trying to use? It certainly works here as of 565c1940e31b87a0e68fe5ba776359407f838264 with `rfc6979` v0.1.0 from https://github.com/nspcc-dev/rfc6979 that has three variables returned from this function:
```
vendor/github.com/nspcc-dev/rfc6979/ecdsa.go:func SignECDSA(priv *ecdsa.PrivateKey, hash []byte, alg func() hash.Hash) (r, s *big.Int, err error) {
```

**Comment by roman-khimov** [comment]
Maybe something is wrong with your go modules setup, because we have rfc6979 v0.1.0 used at the moment to build neo-go, even though I do see now that more recent versions of rfc6979 don't have error returned from `SignECDSA`. Not sure it's worth upgrading for us, the changes there are cosmetic.

**Comment by mesment** [comment]
Thanks for your reply
We are using govendor as dependency management tool 
github.com/nspcc-dev/neo-go      commit 565c1940e31b87
github.com/nspcc-dev/rfc6979     commit 24b8ce9606a001

**Comment by roman-khimov** [comment]
We use Go modules and expect you to use Go 1.12+, but anyway we'll move to v0.2.0 of rfc6979 (https://github.com/nspcc-dev/rfc6979/releases/tag/v0.2.0) as it allows us to simplify error handling in our own code.
