### ISSUE TITLE
compiler: implement builtins for signature checking

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#616]
Implement builtins for signature checking.
Something like `util.CheckSignature([]byte, []byte)` and `util.CheckMultisig([][]byte, [][]byte, []byte)`

**Comment by roman-khimov** [comment]
Related:
https://docs.neo.org/developerguide/en/api/Neo.Cryptography.Crypto.html

**Comment by roman-khimov** [comment]
I guess that should be `crypto` package as per our current interop implementation.
