### ISSUE TITLE
compiler: ensure stack is cleaned properly

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#683]
Make sure that `for`, `switch`, function calls etc. leave no garbage on stack.
This can lead to bugs in certain circumstances when there are multiple levels of nesting.
This task is about implementing some generic mechanism for cleanup on encountering branching instructions.

**Comment by roman-khimov** [comment]
Is it still a problem?

**Comment by fyrchik** [comment]
The only thing that left is properly processing functions that return arguments, but are not assigned to anything.
