### ISSUE TITLE
compiler: slice of structs definition with `var` keyword compiles incorrectly

### ISSUE THREAD

**Issue by AlexVanin** [nspcc-dev/neo-go#695]
I defined slice of structures with `var foo []bar` statement. When I tried to append new element to the slice I got an error: `APPEND: not of underlying type Array`. When I changed slice definition to 
`foo := []bar{}` it worked fine. 

This issue reproduces at least with slices of structures and ints. These tests **fails**:
- slice of structures
```go
	{
		"define slice of structs",
		`
		package foo

		type token struct {
			x int
		}

		func Main() token {
			t := token{
				x: 10,
			}

			var foo []token
			foo = append(foo, t)

			return foo[0]
		}
		`,
		[]vm.StackItem{
			vm.NewBigIntegerItem(10),
		},
	},
```
- slice of ints
```go
	{
		 "define slice of ints",
		`
		package foo
		func Main() int {
			var a []int
			a = append(a, 1)
			return a[0]
		}`,
		big.NewInt(1),
	},
```

But slice of bytes works fine. This test **passes**:
```go
{
		 "define slice of bytes",
		`
		package foo
		func Main() []byte {
			var a []byte
			a = append(a, 2)
			a = append(a, 3)
			return a
		}`,
		[]byte{2, 3},
	},
```

**Comment by fyrchik** [comment]
The problem is that default value for any variable in neoVM is `0` or `null`.
Byte slices are appended with `CAT` so no problem occur because 0 can be seen as an empty bytearray.
All other slices are appended with `APPEND` and an error occur, because 0 can't be converted to an array.
