### ISSUE TITLE
Use go 1.14 T.Cleanup() in tests

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#717]
```
 The testing package now supports cleanup functions, called after a test or benchmark has finished, by calling T.Cleanup or B.Cleanup respectively. 
```
https://tip.golang.org/doc/go1.14

Very useful, we have some cases of tests writing to disk in `storage`, `compiler`, `wallet` and `io` packages (search for `os.RemoveAll` there) and it's a perfect fit for those.

Of course this could only be done when we're to require go 1.14 support (not now).

**Comment by fyrchik** [comment]
This should also be done for all `(*Blockchain).Close()` in `core` and `rpc`.
