### ISSUE TITLE
makeStackItem() could not parse trigger type

### ISSUE THREAD

**Issue by AlexVanin** [nspcc-dev/neo-go#776]
In https://github.com/nspcc-dev/neo-go/commit/7d46404e2db9aa0a836bf9f55a18cb29e9252b7c trigger constants were defined with the type `Type`, which is a `byte` alias. However `makeStackItem()` can't explicitly convert `Type` as `uint8`
```go
func makeStackItem(v interface{}) StackItem {
	switch val := v.(type) {
	case int:
	case int64:
	case uint8:
	case uint16:
	case uint32:
	case uint64:
	case []byte:
	case string:
	case bool:
	case []StackItem:
	case *big.Int:
	case StackItem:
	case []int:
	default:
	}
}
```

Therefore code snippets like this lead to an error. 
```go
v.Estack().PushVal(trigger.Application)
```
Is it correct behaviour?

**Comment by roman-khimov** [comment]
Kinda at the moment, but it's a useful use case and it's so easy to fix that we should do it.
