### ISSUE TITLE
Move crypto from VM to interops

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#777]
Following NEO 3.0 changes we need to remove crypto-related opcodes from VM and move them into interop functions. This will also affect verification scripts.

See also:
https://github.com/neo-project/neo-vm/pull/146
https://github.com/neo-project/neo-vm/pull/149

**Comment by fyrchik** [comment]
We should probably wait until https://github.com/neo-project/neo/pull/1419/ is finalized and merged.

**Comment by roman-khimov** [comment]
I don't think so. To me that one is essentially an extension of the previous work. And it might not get merged or merged in a different way.

**Comment by roman-khimov** [comment]
@fyrchik --- isn't this one done already?
