### ISSUE TITLE
core/state: use more compact representation for state.AppExecResult.Stack

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#782]
RN `state.AppExecResult` contains `Stack string` which is vm's stack marshalled to indented (!) JSON (!). Because it is saved in DB, it is better to have some compact binary representation and marshal to JSON when returning to use (i.e. in RPC).

**Comment by roman-khimov** [comment]
It was done to quickly add functionality before the stack parameter types merge was done. I think now we can reuse `(*Stack).ToContractParameters` and store those. IIRC it already has the right JSON output format for this thing.
