### ISSUE TITLE
Contract invocation failed: "error encountered at instruction 1850 (THROW)"

### ISSUE THREAD

**Issue by anatoly-bogatyrev** [nspcc-dev/neo-go#797]
On attempt to invoke NEP-5 smart contract in single node NeoGo privnet:  {"tx": "6617673e42893c62a3866928903ec3098e7e6d3c04fcef5544d26806d61fc0f9", "block": 2472, "error": "error encountered at instruction 1850 (THROW): THROW"}.

**Comment by fyrchik** [comment]
As I understand, you are talking about this contract https://github.com/nspcc-dev/neofs-local/blob/master/neofs-local/privnet/neofs_privnet.avm .
1850 instruction is right after `runtime.CheckWitness` which means that most likely transaction was signed with the wrong key.

**Comment by anatoly-bogatyrev** [comment]
Yes, it looks like issue with incorrect key. Thanks.
