### ISSUE TITLE
Use native contract GAS for system and network fees

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#831]
Doing so requires P2P format changes first because at this point we're removing UTXO and making Sender pay for everything, thus the Sender has to exist first.

**Comment by roman-khimov** [comment]
Relates to #779.

**Comment by fyrchik** [comment]
First we need to support verification of arbitrary containers like it is done in the reference implementation: https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/InteropService.Crypto.cs#L36 .
Smth like `interface Verifiable { GetSignedPart() []byte }`.
Related #783 .
