### ISSUE TITLE
Dynamic AppCall compilation

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#914]
It's not possible to normally generate a dynamic `APPCALL` using our compiler at the moment. The option, if possible, would be to autogenerate it for dynamic (not known at compile time) `scriptHash` parameters, if that's not possible then we need a `DynAppCall()` interop probably.

CC: @AlexVanin.

**Comment by fyrchik** [comment]
One possible caveat is globally defined contract address: if it is not constant, we must use dynamic appcall, even though `Go` doesn't allow to `[]byte` constants.
I prefer separate interops for static/dynamic calls perhaps with string argument in static case:
1. It helps readability.
2. Usage of dynamic appcalls is a special smart-contract permission, so we better be explicit.

**Comment by roman-khimov** [comment]
Yeah, I've also thought about the second point and it has some value, so a separate call can make things more predictable.

**Comment by roman-khimov** [comment]
Fixed in master-2.x, not relevant for master.
