### ISSUE TITLE
Slices with implicit type definition pass incorrectly to the function 

### ISSUE THREAD

**Issue by AlexVanin** [nspcc-dev/neo-go#933]
neo-go master-2.x branch
neo-go version 0.74.1-pre-148-ge097e86b

Slices pass to the function incorrectly if function has implicit type definition of the arguments, e.g.

```go
func foo(a, b []int)
```

Explicit type definition works correctly.

```go
func foo(a []int, b []int)
```

In this example `foo()` should return `4` but it returns `0`.
```go
package foo

func foo(a, b []int) int {
	ln := len(b)
	return ln
}

func Main() int {
	a := []int{1,2}
	b := []int{1,2,3,4}
	return foo(a,b)
}
```

**Comment by fyrchik** [comment]
Closed via #935.
