### ISSUE TITLE
Change interop calls code-generation to a more standard one

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#941]
At the moment our interop packages are just stubs that declare some functions without real implementation. Calls to these stubs get replaced by syscalls in the compiler which maintains a map of functions to interop names. In general, this mechanism is far from perfect, see #397 and #913.

What's proposed here is to make our interop packages work the same way ordinary ones do by completely removing internal compiler mapping and moving syscall logic into interop packages implementation. This can be done if we're to define one low-level syscall function (compiler intrinsic) and then use it to implement interops.

So instead of
```go
// Log instucts the VM to log the given message.
func Log(message string) {}

// Notify an event to the VM.
func Notify(arg ...interface{}) int {
        return 0
}
```
we'll have something like this in interops:
```go
// Log instucts the VM to log the given message.
func Log(message string) {
    neogointernal.Syscall("Neo.Runtime.Log", message)
}

// Notify an event to the VM.
func Notify(arg ...interface{}) int {
    neogointernal.Syscall("Neo.Runtime.Notify", arg...)
    return 0
}
```

`neogointernal` package should then be declared as neo-go specific package that can't be overriden (and we'll provide a stub for it made the same way all our current interops are), we can move other intrinsics like `AppCall`, `FromAddress`, `ToByteArray`, etc. there and provide regular interop APIs for them too.

This should simplify our compiler a bit, solve both #397 and #913 and help solving #296 in longer term.

@fyrchik?

**Comment by fyrchik** [comment]
I like the idea, it will make adding new pretty straitforward. Maybe `neogointernal` should also mirro  functions declared in `emit`, so it's used like "inline assemly".

The only problem I can imagine is a presence of opaque types like `Asset` or `Contract`, but those can stay, and be processed in `neogointernal` like interop items.

**Comment by fyrchik** [comment]
By "inline assemly" I understand some `interop` package with low-level interops which can or can not be used in regular contracts. I.e. there will be a single package with a pretty stable interface and simple to compile, and another interop and builtin packages implemented on top of this.

**Comment by fyrchik** [comment]
There can be a problem with syscalls which must be invoked by id. We can generate ID in constants via `go:generate` for all provided interops.

**Comment by fyrchik** [comment]
Even if syscalls are defined as functions, make sure we inline them (like it is done now).
