### ISSUE TITLE
Check Neo 3 debugger compatibility

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#947]
For some reason I think that [the debugger](https://github.com/neo-project/neo-debugger/) is not yet ready for Neo 3, so it's hard to check for compatibility at the moment. But we'll need to do that in the future, both debug info format and abi.json are to be checked.

**Comment by roman-khimov** [comment]
It's ready for preview2, but we have #1088 for that, so let's keep this one as a reminder for 0.91.0 (preview3).

**Comment by roman-khimov** [comment]
Turns out the debugger is already there for quite some time:
https://github.com/neo-project/neo-debugger/releases/tag/1.2.25-preview

No format changes, so it should just work, but of course we need to check that.

**Comment by AnnaShaleva** [comment]
The following example from the paper cannot be properly debugged:
```
package storage

import (
   "github.com/nspcc-dev/neo-go/pkg/interop/runtime"
   "github.com/nspcc-dev/neo-go/pkg/interop/storage"
)

func Main() interface{} {
   ctx := storage.GetContext()
   itemKey := "test-storage-key"
   itemValue := storage.Get(ctx, itemKey).(int)
   msg := "Value read from storage"

   runtime.Notify(msg)

   if itemValue == 0 {
       runtime.Notify("Storage key not yet set. Setting to 1")
       itemValue = 1
   } else {
       runtime.Notify("Storage key already set. Incrementing by 1")
       itemValue += 1
   }

   storage.Put(ctx, itemKey, itemValue)
   runtime.Notify("New value written into storage")
   return itemValue
}
```

The reason is `Engine State Faulted` on the first `runtime.Notify(msg)` instruction. The same thing happens with the following example:
```
package storage

import (
	"github.com/nspcc-dev/neo-go/pkg/interop/runtime"
)

func Main() {
	runtime.Notify("Hello, world!")
}
```

However, the debugger can handle the storage example without notifications as far as an example with other runtime syscall:
```
package storage

import (
	"github.com/nspcc-dev/neo-go/pkg/interop/runtime"
)

func Main() {
	runtime.Log("Hello, world!")
}
```

So I'm investigating this behaviour.

**Comment by AnnaShaleva** [comment]
Turns out it was outdated go modules problem (the old version of runtime.Notify does not have `name` argument, so resulting VM operations are different for this case). All works fine after go modules update and we're able to debug our `storage` contract.

**Comment by roman-khimov** [comment]
I think we're done here.
