### ISSUE TITLE
Add assign and sub assign don't work with struct fields

### ISSUE THREAD

**Issue by AlexVanin** [nspcc-dev/neo-go#953]
Branch: master-2.x
Version: 0.74.1-pre-168-g1d5734c8

`+=` and `-=` operators work like assignment operator with structure fields. 

This code returns 2 instead of 7.

```go
package foo
type Foo struct { x int }

func Main() int {
	foo := Foo{x:5}
	foo.x += 2
	return foo.x 
}
```

This code returns 3 instead of 2.

```go
package foo
type Foo struct { x int }

func Main() int {
	foo := Foo{x:5}
	foo.x -= 3
	return foo.x 
}
```

**Comment by fyrchik** [comment]
Closed via #954.
